Idletimeout default clarification
istio/api pull request #1665
Opened 2020-09-30 21:18 UTC by linsun

We are actually not have it disabled:

https://github.com/istio/istio/blob/master/pilot/pkg/model/context.go#L482

Also, from my envoy sidecar default config:

```
            "stream_idle_timeout": "0s",
```

2020-09-30 21:46 UTC, nrjpoddar commented on networking/v1alpha3/destination_rule.proto
> +    // The default is disabled. When the idle timeout is set and the timeout value
What does disabled mean? I'm guessing no idle time out? What happens in that case? Does the connection remains open for ever?

2020-09-30 21:46 UTC, nrjpoddar commented on networking/v1alpha3/destination_rule.proto
> +    // Note that request based timeouts mean that HTTP/2 PINGs will not
Is this accurate? HTTP/2 PING frames are sent over the same connection and used to determine if a connection is still active or not.

Is Envoy ensuring that any PING HTTP/2 frames doesn't reset TCP level idle timer?

2020-10-01 01:06 UTC, linsun commented on networking/v1alpha3/destination_rule.proto
> +    // The default is disabled. When the idle timeout is set and the timeout value
yes disabled means no timeout.  It would remain open forever.

2020-10-01 01:18 UTC, nrjpoddar commented on networking/v1alpha3/destination_rule.proto
> +    // The default is disabled. When the idle timeout is set and the timeout value
Do you think adding that in doc will be good? I always get confused by what disabled means in different contexts.

2020-10-01 02:03 UTC, linsun commented
After a big more digging, I believe we are using the default idle timeout which is 1 hour, so the doc is correct.  I got confused from the code comment https://github.com/istio/istio/blob/master/pilot/pkg/model/context.go#L480 and the value of stream_idle_timeout which we don't expose users to configure it today.

@howardjohn let me know if I'm wrong here.

2020-10-01 02:12 UTC, linsun commented
cc @GregHanson since you are looking at some of these as well

2020-10-01 02:28 UTC, linsun commented on networking/v1alpha3/destination_rule.proto
> +    // Note that request based timeouts mean that HTTP/2 PINGs will not
There is no evidence this is no longer accurate. :)  Given this is an http level configuration, pings are not http so would not apply here.

2020-10-01 02:34 UTC, linsun commented on networking/v1alpha3/destination_rule.proto
> +    // Note that request based timeouts mean that HTTP/2 PINGs will not
I assume here it means it is different request, so if you are running HTTP/2 pings on the side, it can keep the pings request alive but not your other request.

2020-10-01 02:35 UTC, linsun commented on networking/v1alpha3/destination_rule.proto
> +    // The default is disabled. When the idle timeout is set and the timeout value
probably if you are confused. :)

2020-10-01 07:18 UTC, ramaraochavali commented on networking/v1alpha3/destination_rule.proto
> +    // The default is disabled. When the idle timeout is set and the timeout value
Are you sure if not specified it is disabled i.e. no idle timeout? If we do not specify any value the default is 1 hour in Envoy https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/protocol.proto.html?highlight=idle_timeout#core-httpprotocoloptions

The code comment is https://github.com/istio/istio/blob/master/pilot/pkg/model/context.go#L480 is incorrect. It was the original behaviour in Envoy i.e. when not set no idle timeout. Later it has been changed to 1 hour.

stream_idle_timeout is a different timeout from idle_timeout. idle_timeout applies at the connection level where as stream_idle_timeout is for individual streams carried by the http connection. https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts.html?highlight=timeouts#how-do-i-configure-timeouts

I think changing this is not ocrrect.

2020-10-01 07:19 UTC, ramaraochavali requested changes
It seems the current document is correct unless I am missing some thing. Can you please review my comments?

2020-10-01 13:39 UTC, linsun commented on networking/v1alpha3/destination_rule.proto
> +    // The default is disabled. When the idle timeout is set and the timeout value
@ramaraochavali I think you are correct.  I came to similar conclusion earlier too for idle_timeout.

https://github.com/istio/api/pull/1665#issuecomment-701744044

Thanks for the clarification on stream_idle_timeout, which we don't allow users to set today.

2020-10-01 14:25 UTC, ramaraochavali approved these changes

2020-10-01 15:53 UTC, nrjpoddar commented on networking/v1alpha3/destination_rule.proto
> +    // Note that request based timeouts mean that HTTP/2 PINGs will not
I don't think that's how it will work. PING should be send on the same underlying TCP connection as HTTP/2 by default only creates a single connection.

@PiotrSikora am I not misunderstanding something here? A TCP level timer should be reset if any Layer 7 packets are send.

2020-10-01 17:41 UTC, PiotrSikora commented on networking/v1alpha3/destination_rule.proto
> +    // Note that request based timeouts mean that HTTP/2 PINGs will not
But this is not a TCP-level timer, this is timeout for a HTTP-level timer, and each HTTP request gets it's own.

HTTP/2 PINGs are connection-level events that are not associated with any particular HTTP request, so this descriptions sounds about right and it matches Envoy's documentation.

2020-10-01 17:59 UTC, nrjpoddar commented on networking/v1alpha3/destination_rule.proto
> +    // Note that request based timeouts mean that HTTP/2 PINGs will not
Damn I got confused by 2 of @linsun PRs and thought this one was for TCP setting. Sorry about the churn.

2020-10-01 18:12 UTC, linsun commented on networking/v1alpha3/destination_rule.proto
> +    // Note that request based timeouts mean that HTTP/2 PINGs will not
thanks @PiotrSikora for the clarification!  isn't HTTP/2 pings ping based on http2? :)  If it is TCP only, yep, it won't impact idle_timeout which is for http(2) protocol.

2020-10-01 18:58 UTC, nrjpoddar approved these changes

2020-10-01 18:58 UTC, PiotrSikora commented on networking/v1alpha3/destination_rule.proto
> +    // Note that request based timeouts mean that HTTP/2 PINGs will not
HTTP/2 PING is HTTP/2 frame, yes. But it's associated with the whole HTTP/2 connection, which carries many independent HTTP/2 streams (request/response pairs), and the timeouts are set on a per-stream basis.

2020-10-01 19:04 UTC, merged

2020-10-01 20:29 UTC, nrjpoddar commented on networking/v1alpha3/destination_rule.proto
> +    // Note that request based timeouts mean that HTTP/2 PINGs will not
That's what I thought. This idle timeout talks about connections and not per HTTP/2 stream timeout afaict.

This is the current comment:

// Note that request based timeouts mean that HTTP/2 PINGs will not keep the connection alive.

Why won't a PING frame keep the underlying connection alive? I must be missing something basic here.

2020-10-02 01:19 UTC, linsun commented on networking/v1alpha3/destination_rule.proto
> +    // Note that request based timeouts mean that HTTP/2 PINGs will not
There is also stream_idle_timeout, which HTTP/2 Pings won't impact.   If idle_timeout is not associated with any particular HTTP request as the doc has indicated, sounds like HTTP/2 Pings can keep the connection from hitting idle_timeout.

@PiotrSikora @ramaraochavali thoughts?

2020-10-02 05:20 UTC, ramaraochavali commented on networking/v1alpha3/destination_rule.proto
> +    // Note that request based timeouts mean that HTTP/2 PINGs will not
The way idle timeout is implemented in Envoy is the timer is started on new connection and is disabled a new request starts and enabled when the request ends. So it is always at the request level. If there are no requests on the connection - it will be treated as idle.

2020-10-02 13:24 UTC, linsun commented on networking/v1alpha3/destination_rule.proto
> +    // Note that request based timeouts mean that HTTP/2 PINGs will not
@ramaraochavali based on what you said, iiuc, continuous http/2 pings will be the active request to keep the connection from idle.   Safe to delete this?

```
Note that request based timeouts mean that HTTP/2 PINGs will not keep the connection alive.
```

2020-10-03 04:09 UTC, ramaraochavali commented on networking/v1alpha3/destination_rule.proto
> +    // Note that request based timeouts mean that HTTP/2 PINGs will not
Http2 ping is not considered a request and hence the above comment is correct.

2020-10-05 01:25 UTC, linsun commented on networking/v1alpha3/destination_rule.proto
> +    // Note that request based timeouts mean that HTTP/2 PINGs will not
I see.  That was what I was not sure earlier given it is not regular ping, it is Http2 ping.   I think we are good now!