update external action API
istio/api pull request #1698
Opened 2020-10-16 23:52 UTC by yangminzhu

Updated to move the external config to MeshConfig based on discussions from the TOC meeting.

2020-10-16 23:53 UTC, istio-testing commented
@yangminzhu: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build_api | bb5dfbf66047ad14abbbce139380b0307a3fe0a0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/1698/build_api/1323) | `/test build_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-17 00:09 UTC, louiscryan commented on security/v1beta1/authorization_policy.proto
> +    // The configuration of the external server is specified in the `external_auth` field in the MeshConfig.
@smawson @costinm @nrjpoddar @howardjohn 

To John's point in the TOC meeting this a.m I wonder if we want to make a strong statement about logical de-coupling from implementation here. In theory this can be CUSTOM/EXTERNAL and defined to be a binding to a default or named authz system declared in mesh-config without implying anything else in the contract. This would enable it to be generic and accommodate use-cases like WASM. Then the 'ext_authz' filter is just an example rather than a concrete part of this contract.

2020-10-17 00:34 UTC, mandarjog commented on security/v1beta1/authorization_policy.proto
> +    // The configuration of the external server is specified in the `external_auth` field in the MeshConfig.
I think from the perspective of user journey we need to state "what" it is by pointing to mesh config.
This is identical to tracer. Here we are saying when to trigger tracing and in some other place we say *how* to trace.
We need to specify where that other place is.

With that in mind the mesh config specified here should change. It *should* concrete, and some enum should say that it is `ext_authz` and not just text.

2020-10-17 00:44 UTC, yangminzhu commented on security/v1beta1/authorization_policy.proto
> +    // The configuration of the external server is specified in the `external_auth` field in the MeshConfig.
@mandarjog I wonder should we do that when we actually need that flexibility? That means add this when a different place other than MeshConfig and a different implementation other than ext_authz is actually used. 
The API can be added in a later version without breaking existing user by having proper default values. Before that we are not sure what the concrete API would look like, we could try to make the API as generic as possible but it still seems would be diverged from the real user case arises, and it's much harder to fix that if we added the generic API too early.

2020-10-17 01:21 UTC, mandarjog commented on security/v1beta1/authorization_policy.proto
> +    // The configuration of the external server is specified in the `external_auth` field in the MeshConfig.
Since we are actively doing this indirection to support “more than one” now would be good.

But sure we can introduce enum later and deprecate the current field in mesh config.

2020-10-18 01:29 UTC, yangminzhu commented on security/v1beta1/authorization_policy.proto
> +    // The configuration of the external server is specified in the `external_auth` field in the MeshConfig.
In MeshConfig, I pushed a commit to make the API more generic. It is a list of external server identified by a unique name (only 1 is allowed for now) and the detail configuration is in its own struct organised under the oneof (can easily add other type of external server).

My only concern is that will this be too early to say that the AuthzPolicy is the integration point for things like WASM?

In AuthorizationPolicy, I'm not sure do we want to just make the comment more generic, or add the fields to allow configuring the name of the external server (i.e. state "what" it is), and one more field to state "where" it is (currently only MeshConfig)? Like the following:
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ext-auth
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: EXTERNAL
  external:
    server: "default" # the unique name of the server (defined in MeshConfig)
    source: MESH_CONFIG # the place of the definition, this is an enum and can be omitted for now as the default is MESH_CONFIG
```

2020-10-19 17:53 UTC, liminw commented on mesh/v1alpha1/config.proto
> +        // List of headers from the external server that should be added to the original request and forwarded to the
Is it "add" only? I think external_authz filter spec also allows you to remove/replace headers in addition to "add".

2020-10-19 17:53 UTC, liminw commented on mesh/v1alpha1/config.proto
> +        repeated string forward_to_downstream = 4;
How about call it "headers_on_deny"?

2020-10-19 17:53 UTC, liminw commented on mesh/v1alpha1/config.proto
> +        repeated string forward_to_upstream = 3;
Do we want to call it "headers_on_allow"? I think it is better to call out this is "headers".

2020-10-19 17:53 UTC, liminw commented on mesh/v1alpha1/config.proto
> +        GRPC grpc = 4;
Do you still need users to configure "http" vs "grpc"? I think the feedback was that this should be implementation details.

2020-10-19 17:53 UTC, liminw commented on mesh/v1alpha1/config.proto
> +      Authz authz = 2;
Calling it authz is too limited. In the use cases of RC token, group resolver, do we still use "authz" type? Also, in API, it is better to use the full name like "Authorization" instead of "authz".

2020-10-19 18:08 UTC, smawson commented on mesh/v1alpha1/config.proto
> +        GRPC grpc = 4;
I think it is OK, this is the platform admin configuring what type of external authz service this is. I like having that explicit instead of implicit based on ports or whatever.

2020-10-19 18:08 UTC, smawson commented on mesh/v1alpha1/config.proto
> +  repeated ExternalServer external_servers = 56;
We may want to pick a name other than "external" for this, because it is external to the envoy proxy, not external to the mesh. Or maybe we should make that clear in the comments that these can be inside the mesh and don't need to be external to it.

I'd actually prefer something like "extension_servers" and call the message "ExtensionServer." Actually maybe service is better: ExtensionService and extension_services.

Inside authz proto we can still call it external because it is an external authz call, which goes to one of the extension servers.

2020-10-19 18:08 UTC, smawson commented on security/v1beta1/authorization_policy.proto
> +    // The configuration of the external server is specified in the `external_auth` field in the MeshConfig.
I think this should just be a named external service, so we should include a field to indicate which external service to call (there may be more than one defined).

Then we can just require unique names if we expand the set of types, or we can introduce a type field here to distinguish later.

2020-10-19 18:16 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +        GRPC grpc = 4;
I think this is a bit different, the http/grpc here specifies the API used to talk to the external server

1. the feedback is that we shouldn't distinguish the user traffic (tcp v.s. http) which is orthogonal to the API used to talk to the external server, this means each of the following combination should be possible:
user traffic HTTP + external server HTTP API
user traffic HTTP + external server gRPC API
user traffic TCP + external server HTTP API (not supported today)
user traffic TCP + external server gRPC API

2. the configuration for HTTP and gRPC API is different, the `forward_to_upstream`, `forward_to_downstream` are only applicable to HTTP API, in the future, there may be more differences in the two API

2020-10-19 18:25 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +        // List of headers from the external server that should be added to the original request and forwarded to the
for HTTP API (the protocol used to talk to external server, not user traffic), I don't see it supports remove, doc here: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto.html#extensions-filters-http-ext-authz-v3-authorizationresponse.

It will override (replace) if the header already exists.

2020-10-19 18:41 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +        GRPC grpc = 4;
Or in other words, we will always need this `http`/`grpc` field to supply the detail configuration of the check request/response.

2020-10-19 19:26 UTC, istio-testing commented
@yangminzhu: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2020-10-19 19:27 UTC, istio-testing commented
@yangminzhu: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build_api | 225a9e16176fb0b462a0713b1fa3428dc659fb64 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/1698/build_api/1333) | `/test build_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-19 19:27 UTC, istio-testing commented
@yangminzhu: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build_api | 225a9e16176fb0b462a0713b1fa3428dc659fb64 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/1698/build_api/1333) | `/test build_api`
gencheck_api | 225a9e16176fb0b462a0713b1fa3428dc659fb64 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/1698/gencheck_api/1263) | `/test gencheck_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-19 19:28 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +        string path_prefix = 1;
Updated comments, this is to append an extra path prefix when sending the authorization check request to the external server.

2020-10-19 19:28 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +        repeated string forward_to_downstream = 4;
updated to `headers_to_downstream_on_deny`

2020-10-19 19:29 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +        repeated string forward_to_upstream = 3;
updated to `headers_to_upstream_on_allow`

2020-10-19 19:30 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +      Authz authz = 2;
Updated to use the full name, I think we can just use the `authorization` type for RC token or group resolver, this is the specific extension service implementation but not limited to the high-level use case.

2020-10-19 19:30 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +  repeated ExternalServer external_servers = 56;
Thanks, updated to use ExtensionService and extension_services.

2020-10-19 19:37 UTC, yangminzhu commented on security/v1beta1/authorization_policy.proto
> +    // The configuration of the external server is specified in the `external_auth` field in the MeshConfig.
Thanks Sven, updated and the example now looks like the following:
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ext-auth
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: EXTERNAL
  external:
    service: "default" # the unique name of the external service to call (defined in MeshConfig)
```

2020-10-19 19:44 UTC, yangminzhu commented
@liminw @smawson @mandarjog @louiscryan @costinm @howardjohn @nrjpoddar I updated the PR to address the comments so far, can we take another look? thanks.

2020-10-19 22:49 UTC, louiscryan commented on security/v1beta1/authorization_policy.proto
> +    // The configuration of the external server is specified in the `external_auth` field in the MeshConfig.
@smawson 

How about 'provider' instead of 'service'? 

Also do we need to nest ?

action: EXTERNAL
provider: "reference to named thing somewhere"

Do we expect a need to parameterize these 'calls' beyond what resides in some centralized config?

2020-10-19 22:56 UTC, louiscryan commented on mesh/v1alpha1/config.proto
> +  message ExtensionService {
Better name? 'ExternalAuthorizer' ?

2020-10-19 22:57 UTC, louiscryan commented on mesh/v1alpha1/config.proto
> +    // REQUIRED. Specifies detail configurations of the extension service.
Specifies detailed configuration for the external authorizer

2020-10-19 23:00 UTC, louiscryan commented on mesh/v1alpha1/config.proto
> +    message Authorization {
Better name? This proto represents an 'external' authorizer implementation based on ext_authz filter in Envoy. Do we consider this feature a standard or a part of Envoy or something else?

2020-10-19 23:01 UTC, louiscryan commented on mesh/v1alpha1/config.proto
> +    // Authorization supplies the detail configuration of the external authorization server.
Almost duplicate with 513 above. If this is 'oneof' the possible authorizers then you should document it concretely rather than abstractly. E.g.

'Configures an Envoy ext_authz filter as an external authorizer"

2020-10-19 23:02 UTC, louiscryan commented on mesh/v1alpha1/config.proto
> +      // Note, the `service.port` must always be configured explicitly even if the service exposes only a single port.
Why? To avoid hijacking? Is this a security concern.

What is the service has a HTTP port and a GRPC one. Which would we pick?

2020-10-19 23:04 UTC, smawson commented on security/v1beta1/authorization_policy.proto
> +    // The configuration of the external server is specified in the `external_auth` field in the MeshConfig.
Provider is fine. I think we can add things like parameterization later if we leave the external block in there.

2020-10-19 23:06 UTC, louiscryan commented on mesh/v1alpha1/config.proto
> +        // List of headers that should be included in the authorization check request to the external auth server.
s/authorization check request to the external auth server./authorization request sent to the external authorizer.

2020-10-19 23:06 UTC, smawson commented on mesh/v1alpha1/config.proto
> +  message ExtensionService {
ExtensionProvider or ExternalProvider?

I think Yangmin's goal here was to make this a holder for multiple types of external providers (so we could add things like rate limiting providers or whatever here too). But we could also make it specialized and remove the oneof.

2020-10-19 23:07 UTC, louiscryan commented on mesh/v1alpha1/config.proto
> +        // 1. *Host*, *Method*, *Path* and *Content-Length* are automatically included to the list.
s/are automatically included to the list./are automatically sent

2020-10-19 23:09 UTC, smawson commented on mesh/v1alpha1/config.proto
> +  message ExtensionService {
If specialized to type it could be:

message ExternalAuthorizer {
  string name = 1;
  Destination service = 2;
  Duration timeout = 3;
  oneof type (grpc | http)
}

That's probably the simplest approach.

2020-10-19 23:09 UTC, louiscryan commented on mesh/v1alpha1/config.proto
> +        // the downstream. When a header is included in this list, *Path*, *Status*, *Content-Length*, *WWWAuthenticate*
Why would Path be in this list? What about a response payload ?

2020-10-19 23:14 UTC, louiscryan commented on mesh/v1alpha1/config.proto
> +    message Authorization {
The more I read below of the Envoy quirks the more I think we should explicitly tie this to Envoy and also follow Envoy's versioning. 

@smawson AFAICT the only reason to use the Envoy type here in 'Any' like fashion is because we want to use Destination

2020-10-19 23:18 UTC, smawson reviewed
I think I agree with Louis that we should make this more specific, and not try to build in abstraction/indirection through a wrapper type.

So just have a list of ExternalAuthorization objects in mesh config with names, and refer to them by name from AuthorizationPolicy. We can later add other types of extensions by just adding more lists into mesh config.

2020-10-19 23:18 UTC, smawson commented on mesh/v1alpha1/config.proto
> +        string path_prefix = 1;
So the API for this is to make an HTTP request with /prefix/<actual path>?

That is a pretty bizarre API, but OK that's what is in envoy authz api then that's what we're exposing.

2020-10-19 23:23 UTC, louiscryan commented on mesh/v1alpha1/config.proto
> +  message ExtensionService {
I agree there's not a lot of value in trying to make a wrapper message around a bunch of oneof's for different use-cases generic. OTOH we suspect that we would need more than one for each use-case which is why I didn't propose flattening entirely

2020-10-19 23:43 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +  message ExtensionService {
@louiscryan , this was to make it a bit more generic but I guess it is probably a bit over-designed at this moment. I will change it to just ExternalAuthorizer, and keep the oneof but renaming it to be entirely tied with Envoy (`envoy_ext_authz`) as your other comment suggests.

2020-10-19 23:44 UTC, smawson commented on mesh/v1alpha1/config.proto
> +  message ExtensionService {
Well name, service, and timeout are all pretty generic, we just need to decide where to put the specific stuff. Here are a few different possible models:

1) Generic Service

    message ExternalService {
      name, service, timeout
      oneof type (GrpcExternalAuthorizationService | HttpExternalAuthorizationService)
    }

Extension is to just add to the oneof to introduce new types.

2) Specific Services

    message GrpcExternalAuthorizationService {
      name, service, timeout
    }

    message HttpExternalAuthorizationService {
      name, service, timeout, prefix, headers, ...
    }

Extension is to add new types.

3) Generic Named Thing

    message ExternalThing {
      string name
      oneof (gRPCExternalAuthorizationService | HttpExternalAuthorizationService)
    }

Extension is to just add to the oneof

4) Nesting Genericness

    message ExternalThing {
      string name
      oneof (ExternalAuthorizationService)
    }

    message ExternalAuthorizationService {
      destination, timeout
      oneof (gRPCExternalAuthorizationService | HttpExternalAuthorizationService)
    }

Given that copy-paste is cheap I would suggest we go with the fully specific one and just copy the name, timeout, duration into each object. Actually we should pull out name only since everything needs a name. Wrap the whole thing with a oneof, so something like:

    repeated ExternalService external_services = x;

    message ExternalService {
      string name = 1;
      oneof (ExternalHttpAuthorizationService, ExternalGrpcAuthorizationService)
    }

    message ExternalHttpAuthorizationService {
      timeout, duration, path, headers
    }

    message ExternalGrpcAuthorizationService {
      timeout, duration
    }


That's close to what is there now but we can just flatten the Authorization message down into the grpc and http oneof to simplify.

2020-10-19 23:47 UTC, louiscryan commented
+1 to Sven's suggested layout


On Mon, Oct 19, 2020 at 4:44 PM Sven Mawson <notifications@github.com>
wrote:

> *@smawson* commented on this pull request.
> ------------------------------
>
> In mesh/v1alpha1/config.proto
> <https://github.com/istio/api/pull/1698#discussion_r508124549>:
>
> > @@ -505,7 +506,76 @@ message MeshConfig {
>    CA ca = 55;
>
>    // $hide_from_docs
> -  // Next available field number: 57
> +  message ExtensionService {
>
> Well name, service, and timeout are all pretty generic, we just need to
> decide where to put the specific stuff. Here are a few different possible
> models:
>
>    1.
>
>    Generic Service
>
>    message ExternalService {
>    name, service, timeout
>    oneof type (GrpcExternalAuthorizationService |
>    HttpExternalAuthorizationService)
>    }
>
> Extension is to just add to the oneof to introduce new types.
>
>    1.
>
>    Specific Services
>
>    message GrpcExternalAuthorizationService {
>    name, service, timeout
>    }
>
>    message HttpExternalAuthorizationService {
>    name, service, timeout, prefix, headers, ...
>    }
>
> Extension is to add new types.
>
>    1.
>
>    Generic Named Thing
>
>    message ExternalThing {
>    string name
>    oneof (gRPCExternalAuthorizationService |
>    HttpExternalAuthorizationService)
>    }
>
> Extension is to just add to the oneof
>
>    1.
>
>    Nesting Genericness
>
>    message ExternalThing {
>    string name
>    oneof (ExternalAuthorizationService)
>    }
>
>    message ExternalAuthorizationService {
>    destination, timeout
>    oneof (gRPCExternalAuthorizationService |
>    HttpExternalAuthorizationService)
>    }
>
> Given that copy-paste is cheap I would suggest we go with the fully
> specific one and just copy the name, timeout, duration into each object.
> Actually we should pull out name only since everything needs a name. Wrap
> the whole thing with a oneof, so something like:
>
> repeated ExternalService external_services = x;
>
> message ExternalService {
>   string name = 1;
>   oneof (ExternalHttpAuthorizationService, ExternalGrpcAuthorizationService)
> }
>
> message ExternalHttpAuthorizationService {
>   timeout, duration, path, headers
> }
>
> message ExternalGrpcAuthorizationService {
>   timeout, duration
> }
>
> That's close to what is there now but we can just flatten the
> Authorization message down into the grpc and http oneof to simplify.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/api/pull/1698#discussion_r508124549>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACFAUPBC2MFY4FRMZ7U6NK3SLTFNJANCNFSM4ST6HEBQ>
> .
>

2020-10-19 23:49 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +    message Authorization {
Will rename to make it more specific that this is ext_authz filter in Envoy.

I agree it is probably very unlikely that a different external authorization system would have an API compatible with the Envoy ext_authz filter, and it's hard (and probably impossible) to define an API generic enough that would be implemented by every external authorization system, so it's best to call out the current one is just the Envoy ext_authz API, others could be added in the future to the oneof.

2020-10-19 23:56 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +        string path_prefix = 1;
yes, that's the existing API in the Envoy ext_authz.

2020-10-20 00:26 UTC, costinm commented on mesh/v1alpha1/config.proto
> +  message ExtensionService {
We already use RemoteService - any reason to invent a new proto, just for this case - where we use RemoteService for the other ?

2020-10-20 00:27 UTC, costinm commented on mesh/v1alpha1/config.proto
> +  repeated ExtensionService extension_services = 57;
Please follow the same pattern use use for RemoteService - I don't think all 'extension services' in Istio will be of this type.

2020-10-20 00:32 UTC, costinm commented on security/v1beta1/authorization_policy.proto
> +    //  external:
Do we expect that all 'external services' we'll use for authz will use this particular interface and nothing else ? 

Should we use instead:

ext_authz: 
   service: "default" 

so it is clear what 'external service' we are talking about?  In Istio we also have other kinds of external services, like logging, tracing, etc. 

Unfortunately security is using some very broad and generic words without taking into account other uses.

2020-10-20 00:33 UTC, costinm commented on security/v1beta1/authorization_policy.proto
> +    //  action: EXTERNAL
Do we need both 'action:EXTERNAL' and the 'external: ' section ? Isn't it implicit that if you have external: {} we will have an external action ? I don't think user typing the same thing 2x just to confirm he means it will help.

2020-10-20 00:35 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +      // Note, the `service.port` must always be configured explicitly even if the service exposes only a single port.
not for hijacking, previously I was just trying to make the configuration more consistent for service with single port or multiple ports and easier for us to generate the Envoy configuration in istiod so that in the authz code path we don't need to look up in the service registry to find the port number and can just use what the user provides.

In case there are multiple ports (HTTP and GRPC), the user will need to explicitly specify it here (same as the current behavior of the `Destination`).

2020-10-20 00:38 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +        // the downstream. When a header is included in this list, *Path*, *Status*, *Content-Length*, *WWWAuthenticate*
That is the current Envoy ext_authz behavior (doc: https://github.com/envoyproxy/envoy/blob/415af040e09a1f6993c15ffc022793d39ecf5e8e/api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto#L253), I'm not sure about the reason for that. 
The response body (from the external authorizer) will be sent back to downstream, this is not clearly documented but I found it in the code.

2020-10-20 00:42 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +  message ExtensionService {
There are a couple of reasons we cannot reuse it, the RemoteService uses a `string address` that doesn't really fit the use case here, the service should be in Istio service registry, and can be controlled with DestinationRule for things like subset, which means we should not have the duplicate `ClientTLSSettings` because it should be configured by DestinationRule. also the `tcp_keepalive` doesn't really apply here (not supported by Envoy ext_authz)

Also different provider may have it's own requirement for specifying the address format and that is not bound to the ExternalProvider here.

2020-10-20 00:43 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +  repeated ExtensionService extension_services = 57;
see latest PR and my replies [here ](https://github.com/istio/api/pull/1698#discussion_r508141631), I don't think we can or should use the same RemoteService for all different providers.

2020-10-20 00:43 UTC, yangminzhu commented on security/v1beta1/authorization_policy.proto
> +    //  action: EXTERNAL
the `action: EXTERNAL` is enum and we cannot change it without breaking backward compatibility.

2020-10-20 00:46 UTC, yangminzhu commented on security/v1beta1/authorization_policy.proto
> +    //  external:
there may be external authz interface other than the envoy ext_authz one. The concrete type is defined in the ExternalProvider in MeshConfig now, the comments also refer the user to check the MeshConfig to decide the type of the external provider.

2020-10-20 00:48 UTC, smawson reviewed
LGTM, one small nit but otherwise I think it looks pretty clean. Happy to approve once Louis signs off.

2020-10-20 00:48 UTC, smawson commented on mesh/v1alpha1/config.proto
> +    oneof config {
nit: provider?

2020-10-20 00:51 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +  message ExtensionService {
@smawson thanks for the very detailed suggestion, updated to use `ExternalProvider`, `ExternalHttpAuthorizationProvider` and `ExternalGrpcAuthorizationProvider`. I also added the service to the both HTTP and GRPC message and updated the name with "Envoy" prefix to make it super clear it's the concrete implementation of Envoy ext_authz filter.

2020-10-20 00:58 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +    oneof config {
thanks, fixed.

2020-10-20 01:07 UTC, yangminzhu commented
@louiscryan mind to take a look for another round? I have updated PR to address all comments so far, thanks.

2020-10-20 04:46 UTC, costinm commented on mesh/v1alpha1/config.proto
> +  message ExtensionService {
We can't define a new proto just because one field is optional/not used, for something that is 99% identical.

2020-10-20 04:47 UTC, costinm requested changes
I would like to see more opinions on non reusing RemoteService... 

I don't think introducing a new pattern - just for his particular service - is a good idea.

2020-10-20 04:51 UTC, costinm commented on security/v1beta1/authorization_policy.proto
> +    //  action: EXTERNAL
I don't see the problem. 
If 'external' is present, the 'action' field can be just ignored ( the default value is 'allow'). 
I don't think any user will be confused that he doesn't have to add an action for 'external' services, quite 
the opposite, they may appreciate not having to type 2x external.

Or maybe use the action as a default, in case the external service is unreachable - I noticed the fail open/fail close is also
missing in the API. I remember for mixer it was a big thing.

2020-10-20 04:52 UTC, costinm commented on security/v1beta1/authorization_policy.proto
> +    //  external:
Sounds good.

2020-10-20 04:57 UTC, costinm commented
Another thing I noticed - if we use this pattern of using the 'name', and finding the actual resource definition in istio-system, it may
make sense to create a regular ServiceEntry in istio-system with that name, and use the DestinationRule and standard first class Istio APIs. 

Is there anything missing in Istio APIs that would prevent us describing all that is needed to connect ? If yes, are they general enough things we should add the the main API ? I don't see how the external authz service would be any different than any other mesh service we support.

We discussed this in the past, when we reviewed RemoteService - which is my second choice, for consistency. Same thing - if we need to add something to RemoteService, we can. 

But defining a 3rd way to define the address and few properties of  service ( if we don't count the K8S Service too with all its variants) seems extreme.

2020-10-20 06:11 UTC, liminw commented on mesh/v1alpha1/config.proto
> +        // List of headers from the external server that should be added to the original request and forwarded to the
Ok. Maybe just document it as "add or replace"?

2020-10-20 06:30 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +  message ExtensionService {
There is a key difference in the two use cases that I don't think simplify reusing RemoteService is a good idea.

The RemoteService is for services not really part of the mesh (Istio service registry) and configured in bootstrap stage. I guess that's why it needs `tls_settings` and `tcp_keepalive` instead of using the DestinationRule. 

However the ext_authz service is a real service in the Istio service registry (thus using EDS) and configured by the DestinationRule, that's why we don't need (and shouldn't) have any a separate `tls_settings` or `tcp_keepaplive`, not to mention that we need the `subset` to make it fully work with DestinationRule.

Unless we decide that we don't want the benefits of DestinationRule to configure the cluster for ext_authz but rather prefer a pretty static cluster generated from RemoteService, we can't just use RemoteService. It seems the RemoteService should use `Destination` in the fist place but it cannot because of some limitation in the bootstrap.

2020-10-20 06:39 UTC, yangminzhu commented on security/v1beta1/authorization_policy.proto
> +    //  action: EXTERNAL
I think ignoring the `action` field is not a very user friendly change because it changes the existing semantics. It could fail existing analyze tools because the tool doesn't know the `external` field. And the explicit `EXTERNAL` action provides a very good protection from applying the policy in old Istio version that doesn't support EXTERNAL: a new field is ignored silently but a new enum value will be caught by the webhook validation.

Last, I think the proper long term change is add other fields (`allow,`deny` and `audit`) to the actionDetails and then deprecate the current enum, that's better but can do in later version.

2020-10-20 06:52 UTC, yangminzhu commented
> Another thing I noticed - if we use this pattern of using the 'name', and finding the actual resource definition in istio-system, it may
> make sense to create a regular ServiceEntry in istio-system with that name, and use the DestinationRule and standard first class Istio APIs.
> 
> Is there anything missing in Istio APIs that would prevent us describing all that is needed to connect ? If yes, are they general enough things we should add the the main API ? I don't see how the external authz service would be any different than any other mesh service we support.
> 

See https://github.com/istio/api/pull/1698#discussion_r508243869 for my other reply. 

What's the benefit of using it if we already have the service abstraction well defined in `Destination` which is also used in VirtualService? we already have the TLS setting (either auto mTLS or manual setting in DR), subset for testing/migrating between external service and probably some other stuff without needing to add any new fields (not like RemoteService).

The more subtle difference is do we consider the external service as a static config that needs to be configured in bootstrap and out of Istio's xDS dynamic update? Is that the main reason we have this RemoteService instead of using Destination in the fist place?

> We discussed this in the past, when we reviewed RemoteService - which is my second choice, for consistency. Same thing - if we need to add something to RemoteService, we can.
> 
> But defining a 3rd way to define the address and few properties of service ( if we don't count the K8S Service too with all its variants) seems extreme.

We are using the existing `istio.networking.v1alpha3.Destination` to refer to existing service, not defining anything. Is the RemoteService going to replace the `istio.networking.v1alpha3.Destination` in the VirtualService?

2020-10-20 14:51 UTC, costinm commented on mesh/v1alpha1/config.proto
> +      repeated string headers_to_upstream_on_allow = 4;
Very strange API - so it's a different list of headers that are sent depending on the status code ? Any real use case where you would send different set of headers ? Can we have a single list ?  

I'm not even sure why a list is needed - if the server decides to send back headers, all could be sent ( and simplify the API).

2020-10-20 14:51 UTC, costinm commented on mesh/v1alpha1/config.proto
> +  message ExternalProvider {
Too generic name. There are many other things beyond security that can use 'external providers'. Like Config providers.

Our APIs are too hard too read and write - too many layers of redundant text, too deep ( and error prone ).

2020-10-20 14:51 UTC, costinm commented on mesh/v1alpha1/config.proto
> +      EnvoyExternalHttpAuthorizationProvider envoy_ext_authz_http = 2;
I'm very uncomfortable with this pattern - a bool 'useHTTP' or reusing the protocol ( that we have in other protos) would be far more intuitive for a user.

Why don't you use map, with name as a key ?

2020-10-20 14:51 UTC, costinm commented on mesh/v1alpha1/config.proto
> +      google.protobuf.Duration timeout = 2;
Given all the work we've done to resolve the timeout mess and how to set the defaults - this seems to make it worse. 

Why 1s ? Is this the default that envoy recommends ? What did Mixer Policy use ?

2020-10-20 14:51 UTC, costinm commented on security/v1beta1/authorization_policy.proto
> +    //  action: EXTERNAL
action has a default value - it is not required. Tools that don't know about external proto will fail either way.

Audit is actually a reasonable addition - it fits with 'allow' and 'deny', it represents a typical outcome of the rule. 
'external' is an implementation detail - use the ext_authz. What will be the evolution ? Action will be a list of implementation options ( 'wasm', 'foo' ) and outcomes ?

2020-10-20 14:51 UTC, costinm commented on security/v1beta1/authorization_policy.proto
> +    string provider = 1;
Maybe use ExtAuthzService ? Please don't take over generic words and use them in very narrow scope. It prevents or makes it very difficult to use them in other parts of the API.

2020-10-20 14:59 UTC, costinm commented
Where does the RemoteService proto does it specify that it must be used in
bootstrap ? Or that it must not be part
of the mesh - many of them are.

ExtAuthz also doesn't have to be part of the mesh AFAIK, and with
ServiceEntry every service used can be in or out.
I think it would be extremely bad to require that ExtAuthz runs in-cluster
and prevent out-of-cluster - given that many
clusters can't be properly secured, and ExtAuthz is extremely critical I
would suspect running it in an isolated or
managed env would be a far better practice ( just like CA )

Creating new protos just because we find some differences doesn't make
sense - users would end up with a
different way to configure every single part, with each developer using a
different set of keywords. It's usually called NIH.

On Mon, Oct 19, 2020 at 11:31 PM Yangmin Zhu <notifications@github.com>
wrote:

> *@yangminzhu* commented on this pull request.
> ------------------------------
>
> In mesh/v1alpha1/config.proto
> <https://github.com/istio/api/pull/1698#discussion_r508240136>:
>
> > @@ -505,7 +506,76 @@ message MeshConfig {
>    CA ca = 55;
>
>    // $hide_from_docs
> -  // Next available field number: 57
> +  message ExtensionService {
>
> There is a key difference in the two use cases that I don't think simplify
> reusing RemoteService is a good idea.
>
> The RemoteService is for services not really part of the mesh (Istio
> service registry) and configured in bootstrap stage. I guess that's why it
> needs tls_settings and tcp_keepalive instead of using the DestinationRule.
>
> However the ext_authz service is a real service in the Istio service
> registry (thus using EDS) and configured by the DestinationRule, that's why
> we don't need (and shouldn't) have any a separate tls_settings or
> tcp_keepaplive, not to mention that we need the subset to make it fully
> work with DestinationRule.
>
> Unless we decide that we don't want the benefits of DestinationRule to
> configure the cluster for ext_authz but rather prefer a pretty static
> cluster generated from RemoteService, we can't just use RemoteService. It
> seems the RemoteService should use Destination in the fist place but it
> cannot because of some limitation in the bootstrap.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/api/pull/1698#discussion_r508240136>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAUR2UDSPMUM57AVC3EWITSLUVCZANCNFSM4ST6HEBQ>
> .
>

2020-10-20 15:07 UTC, costinm commented
On Mon, Oct 19, 2020 at 11:52 PM Yangmin Zhu <notifications@github.com>
wrote:

> Another thing I noticed - if we use this pattern of using the 'name', and
> finding the actual resource definition in istio-system, it may
> make sense to create a regular ServiceEntry in istio-system with that
> name, and use the DestinationRule and standard first class Istio APIs.
>
> Is there anything missing in Istio APIs that would prevent us describing
> all that is needed to connect ? If yes, are they general enough things we
> should add the the main API ? I don't see how the external authz service
> would be any different than any other mesh service we support.
>
> See #1698 (comment)
> <https://github.com/istio/api/pull/1698#discussion_r508243869> for my
> other reply.
>
> What's the benefit of using it if we already have the service abstraction
> well defined in Destination which is also used in VirtualService? we
> already have the TLS setting (either auto mTLS or manual setting in DR),
> subset for testing/migrating between external service and probably some
> other stuff without needing to add any new fields (not like RemoteService).
>
> The more subtle difference is do we consider the external service as a
> static config that needs to be configured in bootstrap and out of Istio's
> xDS dynamic update? Is that the main reason we have this RemoteService
> instead of using Destination in the fist place?
>

Bootstrap is an implementation detail of envoy. It is not relevant to the
Istio API. I think Envoy is already moving things out of bootstrap, and
bootstrap
itself is generated dynamically and we can reload envoy if we want.

IMO main reason for RemoteService - just like ConfigSource and many other
things - is that API reviews didn't sufficiently consider API consistency
and developer don't look at the big picture but focus on a specific feature
in isolation.

Now that we have it - we're stuck, we should at least not repeat the
mistakes.


> We discussed this in the past, when we reviewed RemoteService - which is
> my second choice, for consistency. Same thing - if we need to add something
> to RemoteService, we can.
>
> But defining a 3rd way to define the address and few properties of service
> ( if we don't count the K8S Service too with all its variants) seems
> extreme.
>
> We are using the existing istio.networking.v1alpha3.Destination to refer
> to existing service, not defining anything. Is the RemoteService going to
> replace the istio.networking.v1alpha3.Destination in the VirtualService?
>

I don't know - there have been discussions to replace DestinationRule, and
discussions to use DR instead of RemoteService.
Let's not make this even more complicated by adding a 4rd way.

2020-10-20 15:19 UTC, smawson commented
Using RemoteService is an interesting idea but it doesn't quite fit here as-is. The problem is that we need to specify additional configuration options beyond just the address. It would maybe work for the grpc api but not the http api.

I think we should look at refactoring to merge RemoteService and ExternalProvider though since they are serving similar purposes. We basically need an any to define additional parameters to the remote service, and we also need to think about how those services are configured (using destination vs. what remote service does). There is definitely an opportunity for convergence.

So I think the question is whether we get this in as-is and then iterate to converge or we try to figure out a convergence story up front.

2020-10-20 15:20 UTC, smawson commented on mesh/v1alpha1/config.proto
> +  message ExternalProvider {
Do you have an alternative? This is meant to capture any named plugins to Envoy.

2020-10-20 15:20 UTC, smawson commented on mesh/v1alpha1/config.proto
> +      EnvoyExternalHttpAuthorizationProvider envoy_ext_authz_http = 2;
The name is about what type of extension this is, not just about what protocol it uses. This is specifically an ExternalAuthz filter service that uses the HTTP external authz protocol defined by Envoy.

A map could work, we'd just move the name field up to the map. Only real benefit is preventing duplicates right? Is the yaml better or worse with map vs. list of named items?

2020-10-20 15:20 UTC, smawson commented on mesh/v1alpha1/config.proto
> +      google.protobuf.Duration timeout = 2;
Can timeout be specified in DestinationRule? If so maybe we don't need this here?

2020-10-20 15:20 UTC, smawson commented on mesh/v1alpha1/config.proto
> +      repeated string headers_to_upstream_on_allow = 4;
See https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/ext_authz/v2/ext_authz.proto

2020-10-20 15:20 UTC, smawson commented on security/v1beta1/authorization_policy.proto
> +    //  action: EXTERNAL
I would much rather this be explicit and slightly repetitive than rely on a magic behavior of using whatever is in action_detail if action is empty.

For anything that fits in ExternalProvider external will work. So wasm authz could fit in this model without needing a new action type. So this is more about the type of action (call an external service) and not how to implement that action (use envoy's ext_authz api with a grpc call to service x).

So I think the abstraction is the right one here.

2020-10-20 15:20 UTC, smawson commented on security/v1beta1/authorization_policy.proto
> +    string provider = 1;
This is the indirection, it is not specifically ExtAuthzService, it is one of the named ExternalProviders (and this is External/provider).

2020-10-21 06:03 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +      repeated string headers_to_upstream_on_allow = 4;
that's what in the Envoy ext_authz filter and gets used by people today, whether you think it's good or not is a different thing. The MeshConfig just includes a list of different concrete providers, and for now we only support Envoy ext_authz filter. If we ever need a different concrete provider, it can be added and named accordingly.

2020-10-21 06:05 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +      EnvoyExternalHttpAuthorizationProvider envoy_ext_authz_http = 2;
The benefit is probably a slighter benefit in preventing duplicate, note it's different than a CRD as this is in MeshConfig which means it cannot be rejected in webhook validation anyway. We can change to use map, it doesn't affect the yaml output too much.

2020-10-21 06:07 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +      google.protobuf.Duration timeout = 2;
We could remove the timeout here and rely on the one in DR.

2020-10-21 06:17 UTC, yangminzhu commented
> ExtAuthz also doesn't have to be part of the mesh AFAIK, and with
ServiceEntry every service used can be in or out.
I think it would be extremely bad to require that ExtAuthz runs in-cluster
and prevent out-of-cluster

No one says the ExtAuthz has to be in the mesh, you can deploy it anywhere as needed, with mesh or out of mesh, with or out of sidecar. How is that even related to this PR?

> I don't know - there have been discussions to replace DestinationRule, and
discussions to use DR instead of RemoteService.
Let's not make this even more complicated by adding a 4rd way.

Not adding a 3rd way, it's either RemoteService or the Destination. This PR just choose to use Destination.

I think there are 2 primary issues for this PR:
1. In MeshConfig when configuring how to talk to the external server, do we want the API more generic (ExtensionProvider) or more specific (ExternalAuthorizer)? 
2. Also in MeshConfig when configuring where to talk to the external server, do we use the RemoteService or the Destination? This PR

The PR currently picks the more generic way (ExtensionProvider) and the Destination based on previous comments and suggestions.  @louiscryan do you have any suggestions? thanks.

2020-10-21 14:06 UTC, costinm commented
On Tue, Oct 20, 2020 at 8:20 AM Sven Mawson <notifications@github.com>
wrote:

> Using RemoteService is an interesting idea but it doesn't quite fit here
> as-is. The problem is that we need to specify additional configuration
> options beyond just the address. It would maybe work for the grpc api but
> not the http api.
>

Common problem for all services - the fact that a service has some
additional setting doesn't mean they need to be crammed into RemoteService
( just like in K8S, Service is mostly used for configuring properties of
the service ).

It appears for grpc API we actually don't even need RemoteService - if the
Policy external address is using the actual service, which
makes the grpc case super clean and simple.



I think we should look at refactoring to merge RemoteService and
> ExternalProvider though since they are serving similar purposes. We
> basically need an any to define additional parameters to the remote
> service, and we also need to think about how those services are configured
> (using destination vs. what remote service does). There is definitely an
> opportunity for convergence.
>
I would go one step further - we need a mechanism to define additional
parameters for any 'feature' or 'service'.
I think Nate already added something a few releases back for a similar use
case, for DestinationRule ?

If we do this - in most cases we'll not need either RemoteService nor
ExternalProvider, instead we can use the 'natural'
name of the service ( authz.istio-system:9080), as we do in the common
Istio APIs.



> So I think the question is whether we get this in as-is and then iterate
> to converge or we try to figure out a convergence story up front.
>
We had an offline chat - it appears we are in pretty strong agreement that
adding the Policy EXTERNAL is useful, and the gRPC case
is the simplest and most useful.

We can just add gRPC support in 1.8, and have more time for 1.9 to decide
how ( and if ) we support http.
Most of our protocols are gRPC based, so was the original mixer Policy that
this API replaces. We also need
to reconsider the caching and performance/overhead.

I think this will unblock the most important use case, and we are not even
tied to the specifics of ext_auth current
behavior.



>

2020-10-23 04:10 UTC, yangminzhu commented
@louiscryan @smawson @mandarjog @costinm @justinpettit @nrjpoddar @linsun @liminw I have updated the PR based the feedback and discussions, can you take a look at again, thanks.

2020-10-23 22:18 UTC, louiscryan commented on mesh/v1alpha1/config.proto
> +      // The format is "[<Namespace>/]<Service>". The <Namespace> will have the default value "istio-system" if it is
@costinm I don't think we need to explicitly state that the default value of Namespace=istio-system here. Can just state that namespace can be used to more explicitly qualify which service to use if the service name is ambiguous.

2020-10-23 22:19 UTC, louiscryan commented on mesh/v1alpha1/config.proto
> +      // Specifies the port of the service. Can be omitted if it can be decided unambiguously for the service (e.g. the
s/decided unambiguously for/derived unambiguously from

2020-10-23 22:20 UTC, louiscryan commented on mesh/v1alpha1/config.proto
> +      bool fail_open = 4;
@costinm 
@smawson 

should this setting be hoisted a level? Isn't this generic for all possible providers

2020-10-23 22:29 UTC, louiscryan commented on mesh/v1alpha1/config.proto
> +      // omitted. The <Service> is the name of the service object (k8s service or ServiceEntry).
same comment as above

2020-10-23 22:31 UTC, louiscryan commented on mesh/v1alpha1/config.proto
> +  repeated ExtensionProvider extension_providers = 57;
I think this was updated in docs to be 'extended_authorizers' ?

@smawson

2020-10-23 22:31 UTC, louiscryan commented on security/v1beta1/authorization_policy.proto
> +    // The EXTENDED action lets an extension to handle the user request if the  matching rules evaluate to true.
s/lets/allows

2020-10-23 22:33 UTC, louiscryan commented on security/v1beta1/authorization_policy.proto
> +    // The detail extension is referred to by its provider name defined in the MeshConfig.
reword?

Extension behavior is defined by the named providers declared in MeshConfig

2020-10-23 22:34 UTC, louiscryan commented on security/v1beta1/authorization_policy.proto
> +    // We're actively working to improve it based on user feedbacks.
s/feedbacks/feedback

2020-10-23 22:34 UTC, louiscryan commented on security/v1beta1/authorization_policy.proto
> +    // We're actively working to improve it based on user feedbacks.
actually, this is true for all features. Just remove, saying it's experimental is enough

2020-10-23 22:36 UTC, louiscryan commented on security/v1beta1/authorization_policy.proto
> +    // The following authorization policy applies to ingress gateway and delegates the authorization check to the extension
The following authorization policy applies to an ingress gateway and delegates the authorization check to a named extension

2020-10-23 22:38 UTC, louiscryan commented
Generally LGTM. Some doc and naming nits and one question about where to model fail-open in the hierarchy that I could be persuaded either way on.

2020-10-23 22:42 UTC, smawson commented on mesh/v1alpha1/config.proto
> +      // The format is "[<Namespace>/]<Service>". The <Namespace> will have the default value "istio-system" if it is
I think we should just require namespace to be specified. Service names can start unambiguous and become ambiguous later, so we wouldn't want to have a search.

2020-10-23 22:43 UTC, smawson commented on mesh/v1alpha1/config.proto
> +      bool fail_open = 4;
I'm not sure, would a telemetry provider have fail open vs. fail closed?

2020-10-23 22:44 UTC, smawson commented on mesh/v1alpha1/config.proto
> +  repeated ExtensionProvider extension_providers = 57;
No I think we had it as extension_providers since this list can be reused for other types of providers.

2020-10-23 22:59 UTC, smawson reviewed
Looking good, a few last items to resolve.

2020-10-23 22:59 UTC, smawson commented on mesh/v1alpha1/config.proto
> +      // service has defined only 1 port).
So if this is not specified, and the user adds a second port to the service, authz will break? Making it explicit is probably less dangerous.

2020-10-23 22:59 UTC, smawson commented on security/v1beta1/authorization_policy.proto
> +    // Specifies the name of the extension provider. The list of available providers are defined in the MeshConfig.
```suggestion
    // Specifies the name of the extension provider. The list of available providers is defined in the MeshConfig.
```

2020-10-23 23:04 UTC, smawson commented on mesh/v1alpha1/config.proto
> +      // The format is "[<Namespace>/]<Service>". The <Namespace> will have the default value "istio-system" if it is
Louis and I chatted, I'm OK with local resolution meaning "in the same namespace as mesh-config resides". So if namespace is not specified, it is relative to the namespace the config is in. That should be safe.

So reword to say:

If <Namespace> is omitted then the <Service> is resolved within the same namespace as this configuration resource.

Or something like that (don't love the wording).

2020-10-23 23:06 UTC, smawson commented on mesh/v1alpha1/config.proto
> +      bool fail_open = 4;
Chatted with Louis and since it doesn't actually save our users any typing we can leave this down here on the hope that extension providers is useful beyond authorization.

2020-10-24 17:01 UTC, nrjpoddar commented
@yangminzhu is this API hidden from docs because it’s not implemented or we think that in future a newer better first class API will be created for this feature? If it’s the second one then are we going to advertise this feature to users and given them a migration path?

2020-10-26 01:37 UTC, hzxuzhonghu commented on mesh/v1alpha1/config.proto
> +      string status_on_error = 5;
This only covers http protocol, what's it for the others?

2020-10-26 19:39 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +      string status_on_error = 5;
other protocol you mean TCP? I think the ext_authz filter doesn't provide this feature for TCP. Note this is the user traffic and it should be either HTTP or TCP based.

2020-10-26 19:47 UTC, yangminzhu commented
> @yangminzhu is this API hidden from docs because it’s not implemented or we think that in future a newer better first class API will be created for this feature? If it’s the second one then are we going to advertise this feature to users and given them a migration path?

it's not implemented for now, the API will be made public once implemented (will also have new task on istio.io). There might be further API changes and the first class API (like a new CRD) is more likely for the changes in MeshConfig and not for changes in AuthZ, but it's too early to decide anything now and we need some more feedback later.

Later if we have a different API, there will be a way to migrate the core use case even the current API is marked as experimental and subject to breaking changes.

2020-10-26 19:47 UTC, yangminzhu commented on security/v1beta1/authorization_policy.proto
> +    // We're actively working to improve it based on user feedbacks.
removed.

2020-10-26 19:52 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +  repeated ExtensionProvider extension_providers = 57;
yes, I think we had it as extension provider later from the discussion. The example in the design doc is little bit out-of-date (just updated).

2020-10-26 19:52 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +      // omitted. The <Service> is the name of the service object (k8s service or ServiceEntry).
updated.

2020-10-26 19:56 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +      // The format is "[<Namespace>/]<Service>". The <Namespace> will have the default value "istio-system" if it is
+1 to make this default to the namespace of the mesh-config, updated.

2020-10-26 19:57 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +      bool fail_open = 4;
yeah, I also prefer to leave it to the specific type as some other extension provider may doesn't need or have a different interpretation or default value for the `fail_open` concept.

2020-10-26 20:03 UTC, nrjpoddar commented on security/v1beta1/authorization_policy.proto
> +    EXTENDED = 3;
EXTENDED name here for an action seems off and probably a bit confusing. Other suggestion:

1. DELEGATE

2020-10-26 20:07 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +      // service has defined only 1 port).
That's a very good point. Previously this was to follow the convention of the `Destination` and also try to make it a bit simpler to configure. Note it shouldn't be more dangerous as we will always fall back to a deny-all config if we encounter any errors like this.

I think it's probably expected that something might break if you change the name or modify the existing port of a service, but probably a bit surprise that something could break just because you add a new port to a service? 
I now prefer to make the port required to avoid such surprises, @louiscryan  do you have any suggestions?

2020-10-26 20:33 UTC, yangminzhu commented on security/v1beta1/authorization_policy.proto
> +    EXTENDED = 3;
I think we're trying to be a little bit more generic here but I get your point why the name EXTENDED seems a bit off when comparing to ALLOW/DENY. 

But I'm a little worried that the name DELEGATE is a bit too specific for a generic API that integrates different extensions to Istio, many extensions might be doing things different than the "delegate" concept. Note this is not saying the Authz policy will become such generic API but I think it's the name and convention we used here should be generic. This also aligns with the naming in MeshConfig where we had the `extension_providers`.

 cc @louiscryan @smawson

2020-10-26 20:52 UTC, louiscryan commented on mesh/v1alpha1/config.proto
> +      // service has defined only 1 port).
It hasn't been much of an issue with Destination so far so I don't think we need to be overly concerned. In terms of blast radius a user could just as easily remove the port or improperly declare its supported protocol.

That said either is fine with me.

2020-10-26 20:54 UTC, louiscryan commented on mesh/v1alpha1/config.proto
> +      string status_on_error = 5;
For gRPC it should derive the gRPC status from it's canonical HTTP mapping.

2020-10-26 20:54 UTC, louiscryan commented on mesh/v1alpha1/config.proto
> +  repeated ExtensionProvider extension_providers = 57;
ok, sgtm.

2020-10-26 20:57 UTC, louiscryan commented on security/v1beta1/authorization_policy.proto
> +    EXTENDED = 3;
TBH I'm not a fan of DELEGATE as it suggest 'as an alternative to' DENY/ALLOW.

I prefer EXTENDED but would be comfortable with CUSTOM. I believe EXTERNAL was discussed but it's implied 'out of process' semantics wasn't liked.

2020-10-26 21:01 UTC, nrjpoddar commented on security/v1beta1/authorization_policy.proto
> +    EXTENDED = 3;
I see both your points. I don't mind "CUSTOM" as it fits the extension mechanism here and leaves room for doing improvements in future.

2020-10-26 22:43 UTC, yangminzhu commented on security/v1beta1/authorization_policy.proto
> +    EXTENDED = 3;
yes, `EXTERNAL` was discussed but not used because it implies that an extension is always `out of process`. 

I still kind more prefer the `EXTENDED` because it aligns with the terms we used in the MeshConfig (`extendion_provider`), and `CUSTOM` doesn't seem any different from the `EXTENDED` but it lost the connection with the related fields in MeshConfig.

2020-10-26 22:54 UTC, yangminzhu commented on mesh/v1alpha1/config.proto
> +      // service has defined only 1 port).
thanks, changed the document to mark the port as required.

2020-10-27 16:18 UTC, nrjpoddar commented on security/v1beta1/authorization_policy.proto
> +    EXTENDED = 3;
I understand the linkage but an "EXTENDED" action in this API doesn't sound right to me. I would advocate for "CUSTOM".

PS: I know naming and driving consensus is hard so thanks for being patient as all of us give you this feedback.

2020-10-27 16:19 UTC, nrjpoddar commented
@yangminzhu I see that this PR is marked for "release-1.8". I don't think it's a good idea to change APIs and add features after the branch has been created for stability. I would strongly recommend against adding this feature to 1.8.

2020-10-27 17:46 UTC, istio-testing commented
@yangminzhu: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_api | e0206e6bfcdf055759a3181c6a225d14e007bb3e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/1698/gencheck_api/1292) | `/test gencheck_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-27 17:55 UTC, smawson approved these changes
Good enough for me :)

2020-10-27 17:59 UTC, yangminzhu commented
> @yangminzhu I see that this PR is marked for "release-1.8". I don't think it's a good idea to change APIs and add features after the branch has been created for stability. I would strongly recommend against adding this feature to 1.8.

There is a bit more context here. The current API (i.e. the EXTERNAL action and other fields) was merged before 1.8 release and it becomes part of the authz CRD that will be installed in user's cluster. As you can see this PR updates the API a lot and we really should cherry-pick this to the 1.8 to make sure the CRD in user cluster is the same to avoid upgrade issues later.

We only need to cheery-pick the API to 1.8 to fix the CRD and will NOT cherry-pick the implementation. For 1.8, the API is hidden in the doc and there is no implementation for it as well. @nrjpoddar let me know if this sounds good to you, thanks.

2020-10-27 18:00 UTC, yangminzhu commented on security/v1beta1/authorization_policy.proto
> +    EXTENDED = 3;
I see, then let's make it "CUSTOM", thanks for the review Neeraj!

2020-10-27 18:30 UTC, costinm approved these changes

2020-10-27 18:32 UTC, merged

2020-10-27 18:32 UTC, istio-testing commented
In response to a cherrypick label: #1698 failed to apply on top of branch "release-1.8":
```
Applying: update external action API
Using index info to reconstruct a base tree...
M	kubernetes/customresourcedefinitions.gen.yaml
M	mesh/v1alpha1/config.pb.go
M	mesh/v1alpha1/config.proto
M	mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
M	proto.lock
M	python/istio_api/mesh/v1alpha1/config_pb2.py
M	security/v1beta1/authorization_policy.pb.go
M	security/v1beta1/authorization_policy.proto
Falling back to patching base and 3-way merge...
Auto-merging security/v1beta1/authorization_policy.proto
Auto-merging security/v1beta1/authorization_policy.pb.go
Auto-merging python/istio_api/mesh/v1alpha1/config_pb2.py
CONFLICT (content): Merge conflict in python/istio_api/mesh/v1alpha1/config_pb2.py
Auto-merging proto.lock
Auto-merging mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
Auto-merging mesh/v1alpha1/config.proto
CONFLICT (content): Merge conflict in mesh/v1alpha1/config.proto
Auto-merging mesh/v1alpha1/config.pb.go
CONFLICT (content): Merge conflict in mesh/v1alpha1/config.pb.go
Auto-merging kubernetes/customresourcedefinitions.gen.yaml
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0001 update external action API
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

```

2020-10-27 18:32 UTC, istio-testing commented
In response to a cherrypick label: new issue created for failed cherrypick: #1713

2020-10-27 19:17 UTC, nrjpoddar commented
Yes it does, thanks!

2020-10-27 19:19 UTC, nrjpoddar commented
@yangminzhu have we discussed about "default" extension provider selection works for your mesh in cases when you have multiple ones defined or there's no concept of "default", and you only select/attach per workload?

2020-10-27 19:34 UTC, yangminzhu commented
> @yangminzhu have we discussed about "default" extension provider selection works for your mesh in cases when you have multiple ones defined or there's no concept of "default", and you only select/attach per workload?

currently there is no default extension provider and you have to select it per Authz policy (it can apply to multiple workloads), the initial implementation will also restrict to allow at most 1 extension provider, this means effectively all authz policy can only use the same extension provider (for the initial implementation)