Add config to enable application logs formatted for stackdriver
istio/api pull request #1755
Opened 2020-11-13 22:51 UTC by gargnupur

2020-11-13 22:51 UTC, istio-testing commented
@gargnupur: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_api | a956d9b5b0495576eb12f39f35950f07c58518c1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/1755/release-notes_api/1327383569856729088) | `/test release-notes_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-11-13 22:59 UTC, howardjohn commented on mesh/v1alpha1/config.proto
> +  bool enable_stackdriver_formatted_app_logs = 58;
Does this apply only to Envoy logs? What about istiod/agent logs?

2020-11-13 22:59 UTC, howardjohn commented on mesh/v1alpha1/config.proto
> +  // stackdriver. See [Stacdriver Application Log](https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/application_logging#stackdriver-logging-with-gke)
Does SD support reading json logs rather than some magic `'%L%m%d %T.%e %t envoy] [%t][%n]%v'` format? Is there a reference onb the formats it can parse?

2020-11-13 23:03 UTC, howardjohn commented on mesh/v1alpha1/config.proto
> +  // stackdriver. See [Stacdriver Application Log](https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/application_logging#stackdriver-logging-with-gke)
```
  parsers.conf: |-
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

    [PARSER]
        Name        containerd
        Format      regex
        Regex       ^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

    [PARSER]
        Name        json
        Format      json

    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S

    [PARSER]
        Name        glog
        Format      regex
        Regex       ^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source_file>[^ \]]+)\:(?<source_line>\d+)\]\s(?<message>.*)$
        Time_Key    time
        Time_Format %m%d %H:%M:%S.%L

    [PARSER]
        Name        network-log
        Format      json
        Time_Key    timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
```

Can we just use json logging?

2020-11-13 23:05 UTC, gargnupur commented on mesh/v1alpha1/config.proto
> +  bool enable_stackdriver_formatted_app_logs = 58;
I am hoping to apply it to istiod/agent logs too...

2020-11-13 23:08 UTC, howardjohn commented on mesh/v1alpha1/config.proto
> +  bool enable_stackdriver_formatted_app_logs = 58;
I would rather recommend users to use JSON, or convince the GKE team to add parsing for `zap` logs (our format) than adding another flag and complexity into mesh config to workaround the limitations of a single platform+logging ingestion pipeline.

2020-11-13 23:09 UTC, howardjohn requested changes
I don't think SD-on-GKE logging limitations should impact our APIs like this

2020-11-18 00:21 UTC, gargnupur commented
Closing as we would be instead using log-as-json option.

2020-11-18 00:21 UTC, closed without merging

2020-11-18 00:57 UTC, douglas-reid commented
@gargnupur can you validate that log-as-json will address the support concerns that were addressed by the glog format?  i'm concerned that we might lose some of the built-in bits around ease of connection tracing and envoy labelling that came with the recommended glog format string. if there are some defaults that we need to suggest/require, I think we could reconsider next steps here.

2020-11-30 22:19 UTC, gargnupur commented
@douglas-reid : Using log-as-json does solve problems of logs getting split into multiple lines and log not getting marked correctly as error if it is an error. Ex: https://screenshot.googleplex.com/AdyyxCxtAhDoGrM.