Base component only allows overlays field
istio/api pull request #1760
Opened 2020-11-19 11:44 UTC by shamsher31

To fix https://github.com/istio/istio/issues/27240

Based on https://github.com/istio/istio/issues/27240#issuecomment-692059502,  https://github.com/istio/istio/issues/27240#issuecomment-692634227 and [this](https://github.com/istio/istio/blob/4e9e07c3fb322d947e896f88987fa6bf1db0d7d1/operator/cmd/mesh/testdata/manifest-generate/input/pilot_override_kubernetes.yaml#L13).

I'm not sure but I run `protolock commit --force` before I running `make gen`.

2020-11-22 04:27 UTC, costinm requested changes
Any change should include info about upgrade and migration.

Also since the operator API is likely to need major changes, to remove unused and make consistent with helm - we should evaluate carefully what we want to keep.

2020-11-22 04:27 UTC, costinm commented on operator/v1alpha1/operator.proto
> +    // Overlays for k8s resources.
Is it backward compatible ? Upgrade story ?

2020-11-23 06:33 UTC, shamsher31 commented on operator/v1alpha1/operator.proto
> +    // Overlays for k8s resources.
`BaseComponentSpec` only supported `overlay` and not the complete resource spec. Not sure if backward compatibility matters here?

2020-12-10 06:46 UTC, shamsher31 commented
Please see the issue https://github.com/istio/istio/issues/27240 and let me know if this PR needs any updates. Thanks.

2020-12-10 07:36 UTC, richardwxn requested changes
This change doesn't seem to solve the problem, it would only allow overlays field. I am not sure what went wrong but the original API definition looks correct and aligns with other component, so probably it is not an API issue but somewhere in the operator code.

2021-01-30 21:01 UTC, istio-testing commented
@shamsher31: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-02-10 11:08 UTC, shamsher31 commented
Closing as this is not a valid solution.

2021-02-10 11:08 UTC, closed without merging