Add default revision to operator
istio/api pull request #1806
Opened 2021-01-08 14:45 UTC by Monkeyanator

Introduces `bool default_revision` as a top level field in the operator. This change (pending corresponding changes in `istio/istio`) will let us:

1. Fix validation for revisions (specify `istioctl install --revision canary --default-revision` and install will create `istiod-default` service from base pointing to revision)
2. Fix mutating webhook `istio-injection` targeting (we'll only create webhook targeting `istio-injection` if there is no revision specified or the revision is the default revision)

Not sure a top level field in the operator is the correct place for this, to me it makes sense keeping it consistent with where `revision` is defined but would appreciate suggestions.

Per environments WG discussion around revision tags @zerobfd @howardjohn

2021-01-08 14:45 UTC, istio-testing commented
@Monkeyanator: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_api | 66a0a60c048ce0aab9715de9364ffc1e73181e31 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/1806/release-notes_api/1347554991048495104) | `/test release-notes_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-08 16:04 UTC, howardjohn commented on operator/v1alpha1/operator.proto
> +    bool default_revision = 17;
Do we want a `defaultRevision` field? Or a `tags` field, which can contain a special `default` value?

2021-01-08 16:49 UTC, Monkeyanator commented on operator/v1alpha1/operator.proto
> +    bool default_revision = 17;
As I understand it, `tags` (as proposed, anyway) correspond directly to `MutatingWebhooks` pointing to revisions (purely concerned with injection). This is not quite what the `defaultRevision` here tries to address.

`defaultRevision` would just be there to give reasonable semantics around (1) where the `ValidationWebhook` points, and (2) which revision `istio-injection` labels will point to by default. It will do this by creating a new default `Service` rather than a `MutatingWebhookConfiguration`.

I can see where having `defaultRevision` and eventually `revisionTags` both in the operator might be confusing for users. At the same time, I'm a fan of keeping `revisionTags` relatively dumb and having them correspond 1-to-1 with mutating webhooks (rather than having `default` value that does something different). Also not sure how helm installations would be able to handle a special value in `revisionTags` (might be possible, not sure)

2021-01-08 16:51 UTC, howardjohn commented on operator/v1alpha1/operator.proto
> +    bool default_revision = 17;
I agree they are two different concepts, the idea was just having one field (tags) with a special value (default), or having two fields (default_revision and tags). I don't have a strong opinion either way.

I don't think we need to let the implementation details around Service and webhooks drive the API though, we should find the best UX and make the implementation work for that (within reason :slightly_smiling_face: )

2021-01-08 17:50 UTC, Monkeyanator commented on operator/v1alpha1/operator.proto
> +    bool default_revision = 17;
100% agree we shouldn't let the implementation details drive the API here. From UX standpoint I think I'm still leaning towards having two fields (default_revision and tags), although both approaches make sense I think. @zerobfd any thoughts on this?

2021-01-08 19:11 UTC, istio-testing commented
@Monkeyanator: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_api | 6cfbdb556e8200042e5547de485a38c0eb0856de | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/1806/release-notes_api/1347622032048656384) | `/test release-notes_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-08 19:13 UTC, istio-testing commented
@Monkeyanator: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_api | 6cfbdb556e8200042e5547de485a38c0eb0856de | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/1806/release-notes_api/1347622032048656384) | `/test release-notes_api`
build_api | 6cfbdb556e8200042e5547de485a38c0eb0856de | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/1806/build_api/1347622031989936128) | `/test build_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-08 19:24 UTC, istio-testing commented
@Monkeyanator: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build_api | 6cfbdb556e8200042e5547de485a38c0eb0856de | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/1806/build_api/1347622031989936128) | `/test build_api`
release-notes_api | 8fbc39b9aefc89a868dcf31860e5f7c5486ddff5 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/1806/release-notes_api/1347625230595526656) | `/test release-notes_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-08 21:14 UTC, zerobfd reviewed
Just because I'm not very familiar with all of the options: is IstioOperator the right place for the default_revision bool? Maybe there's no other higher-level resource for a singleton accessed by all control planes, but I'm worried that two revisions might get `default_revision` set to `true` at the same time.

2021-01-08 21:14 UTC, zerobfd commented on operator/v1alpha1/operator.proto
> +    bool default_revision = 17;
I think we should have two different fields: I can imagine someone wanting to do something like this:

0) mesh exists with prod and canary tags
1) start a canary deploy by installing new canary revision
2) change the default revision to point to "canary" to test things like validatingwebhook etc. that use the default revision
3) finally, tag the canary revision with "prod" and clean up

If all we have is a special name, I feel like we lose some flexibility.

2021-01-08 21:14 UTC, zerobfd commented on operator/v1alpha1/operator.proto
> +    repeated string revision_tags = 18;
I thought that the decision was to hold off on putting the tags in the Operator for the first iteration? Is this field necessary for the basic implementation?

2021-01-08 21:36 UTC, howardjohn commented on operator/v1alpha1/operator.proto
> +    repeated string revision_tags = 18;
How revision works (and so should this) is that it maps to to the helm values.revision_tags. So its not strictly required, as they can always use the helm passthrough API.

2021-01-08 21:37 UTC, Monkeyanator commented on operator/v1alpha1/operator.proto
> +    repeated string revision_tags = 18;
You're right, we can add this in later

2021-01-08 21:39 UTC, istio-testing commented
@Monkeyanator: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_api | 3612423f91fab580bdfc2ab78b9feab0faeb9d74 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/1806/release-notes_api/1347658559894065152) | `/test release-notes_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-01-08 23:22 UTC, smawson requested changes
I don't like this field showing up in operator spec because what happens if two specs both claim to be the default?

I'm fine with istioctl install to take a flag specifying that a particular revision is the default because it is imperative, and so last one wins, but that doesn't work well for declarative config.

I think we need a separate resource to indicate the default (and general tag mapping). Either a clsuter-scoped config map or a cluster-scoped singleton CRD to specify the mapping.

2021-01-08 23:33 UTC, howardjohn commented
@smawson I disagree and agree. I think we have effectively already done what you are proposing. Trying to work backwards here - adding new resources opens a lot of new problems. What really matters, at the end of the day, is the webhook configs. So we need *something* to actuate the configuration (whether its IstioOperator with istioctl, values.yaml with helm, or I suppose some custom controller with configmap).

I do not consider a custom controller/tool to do this viable, so that leaves IstioOperator or values.yaml.

I don't think making it only IstioOperator makes sense, as we want to support helm, so that leaves values.yaml (Optionally, IstioOperator can wrap around values.yaml, as proposed here).

If we want a global option, configured through helm values.yaml, that would mean we need dedicated chart for this that is shared between revisions and configures these global objects (webhooks). We actually already have exactly that - the `base` chart, which is what will be modified by the `default_revision` option.

For Helm, this works great, because the charts are decoupled. For IstioOperator, they are all bundled so its less great - but its *already* broken if they re-apply an old base (consider upgrading from 1.7 to 1.8, then tweaking the 1.7 IstioOperator - the `base` will drop the CRD versions from 1.8 to 1.7). So in some ways, this just adds to an existing issue, that `base` is a singleton but it isn't treated as such in the API. If we are going to make some sort of singleton, I think we may need to do a bigger change than just this single `default_revision` field.

I feel like I went in circles a bit, let me know if that made sense...

2021-01-14 16:39 UTC, Monkeyanator commented
@smawson agreed that ideally this would fit in better with the declarative API but IMO the problems this solves in the short-to-mid term offsets that. 

Having an `istiod-default` service in base that gets overwritten based on which installation claims to be `default` makes a lot of sense to in the mid-to-short term.  We could handle this solely in `istioctl` with `--default-revision` but this would leave users using operator and helm in the dust for revisioned upgrades for the near future.

Introducing custom resources for this mapping solves the declarative problem but adds quite a few others, and as John mentioned, I think adding a CRD that specifies all common resources between revisions would have to be a whole separate design (including but not limited to revision tags and default revision).

Revision-based upgrades, our recommended upgrade path, is currently [just broken](https://github.com/istio/istio/issues/27501) with validation and this seems to be the most pragmatic approach to solve that. The next best approach IMO would be revisioning the validationwebhook ([like here](https://github.com/istio/istio/pull/27578)) which would redirect validation from a stable install to a new revision

Looping in @costinm who I think has looked into this before

2021-01-15 01:27 UTC, smawson commented
Makes sense @howardjohn thanks. Given base overrides is already broken in OperatorSpec I'm OK with this as a temporary solution. I'd like to make sure we track extracting out the base parts from IstioOperatorSpec and include the revision map as part of that. Can someone file an issue tracking this and someone in environments take on fixing this problem?

At least this is marked experimental but I hate adding fields we know are in the wrong place...so lets see if we can fix it the right way sooner rather than later.

2021-01-20 17:32 UTC, smawson approved these changes
Approving, please start putting together the plan for getting base config out of operator spec.

2021-01-20 17:44 UTC, zerobfd commented
Opened #1834 to track removing the base config from operator spec.

2021-01-30 21:01 UTC, istio-testing commented
@Monkeyanator: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-02-04 02:13 UTC, linsun commented on operator/v1alpha1/operator.proto
> +    bool default_revision = 17;
Is it whoever specify the default_revision newest wins?  It seems possible for user to specify an IOP default revision while the cluster had a default revision already.

2021-02-04 02:14 UTC, linsun commented on releasenotes/notes/default-revision.yaml
> +    should handle validation and default injection.
Is this intended for server side operator as well?

2021-02-17 00:49 UTC, howardjohn approved these changes

2021-02-17 13:05 UTC, merged

2021-07-08 13:45 UTC, joberdick commented
@Monkeyanator Was this tested against CNI? :) It seems many times we can't use features when they are released because we use CNI injection for security reasons.