docs: Update sidecar docs to explain outbound traffic restrictions
istio/api pull request #1813
Opened 2021-01-12 18:05 UTC by howardjohn

This clears up some very common misunderstandings around these fields

2021-01-12 18:19 UTC, mandarjog commented on mesh/v1alpha1/config.proto
> +      // to unknown resources. This is helpful to fail-fast to misconfigurations or avoid accidental calls
It encourages explicit declaration of dependencies.

2021-02-11 13:43 UTC, nrjpoddar requested changes

2021-02-11 13:43 UTC, nrjpoddar commented on mesh/v1alpha1/config.proto
> +      // required alternative mechanisms are required.
```suggestion
      // Note: This configuration is not a security policy, but instead an explicit declaration of dependencies
      // which configures how the sidecar proxy responds to unknown destinations.
      // This is helpful in scenarios where failing fast is preferred for  misconfigurations or preventing
      // accidental requests to unknown destinations.
      // Applications can still bypass these restrictions, so if strict enforcement is
      // required alternative mechanisms like Kubernetes network policies should be configured.
```

2021-02-11 13:43 UTC, nrjpoddar commented on mesh/v1alpha1/config.proto
> +      // there are no services or `ServiceEntry` configurations for the destination port.
```suggestion
      // there are no services or `ServiceEntry` resources for the destination port.
```

2021-02-11 13:43 UTC, nrjpoddar commented on networking/v1beta1/sidecar.proto
> +  // traffic, alternatives such as `NetworkPolicy` must be used.
```suggestion
  // **WARNING:** This list is not a firewall or security policy. Destinations which are not listed here
  // can still be reached if the `outboundTrafficPolicy` is set to `ALLOW_ANY`, or by bypassing the
  // sidecar proxy traffic interception.
  // Instead, this allows you to restrict the set of configuration sent to the proxy and should only used
  // for this purpose. To securely control traffic, alternatives such as Kubernetes `NetworkPolicy` should be used.
```

2021-02-11 13:43 UTC, nrjpoddar commented on networking/v1beta1/sidecar.proto
> +  // traffic, alternatives such as `NetworkPolicy` must be used.
How does NetworkPolicy help here?

2021-02-11 16:28 UTC, howardjohn commented on networking/v1beta1/sidecar.proto
> +  // traffic, alternatives such as `NetworkPolicy` must be used.
Only allow traffic to the egress gateway, then it cannot be bypassed: https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/#apply-kubernetes-network-policies

2021-02-11 23:16 UTC, louiscryan commented on mesh/v1alpha1/config.proto
> +      // required alternative mechanisms are required.
I would suggest a phrasing which talks about 'preventing unintended dependencies' rather than 'unknown desintations'

It's also probably appropriate to say that while this is not a hard security boundary it can be a useful part of a layered security approach as it allows for auditing and other security related controls

2021-02-11 23:18 UTC, louiscryan commented on mesh/v1alpha1/config.proto
> +      // Outbound traffic to unknown destinations will be allowed, in case
s/unknown destination/any endpoint or service ?

2021-02-11 23:19 UTC, louiscryan commented on networking/v1alpha3/sidecar.proto
> +  // **WARNING:** This list does not act as a firewall; destinations not listed may still be reached
@justinpettit You probably want to review too

2021-02-12 18:12 UTC, howardjohn commented
@mandarjog @nrjpoddar @louiscryan I updated the PR, thanks for the suggestions.

2021-02-13 03:06 UTC, nrjpoddar commented on networking/v1alpha3/sidecar.proto
> +  // **WARNING:** This list does not act as a firewall; destinations not listed may still be reached
Can we not use the word firewall but instead similar wording as used in MeshConfig comments?

2021-02-13 03:07 UTC, nrjpoddar commented on networking/v1alpha3/sidecar.proto
> +  // Instead, this acts only to restrict the set of configuration sent to the proxy. To secure control
```suggestion
  // Instead, this acts only to restrict the set of configuration sent to the proxy. To securely control
```

2021-02-13 03:07 UTC, nrjpoddar commented on networking/v1alpha3/sidecar.proto
> +  // traffic, alternatives such as `NetworkPolicy` must be used.
```suggestion
  // traffic, alternatives such as Kubernetes `NetworkPolicy` must be used.
```

2021-02-23 20:26 UTC, howardjohn commented
@nrjpoddar PTAL, I think i have addressed all comments

2021-03-11 20:53 UTC, istio-testing commented
@howardjohn: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-03-12 04:08 UTC, linsun commented on mesh/v1alpha1/config.proto
> +      // Outbound traffic will be restricted to services defined in the
when registry_only is enabled, correct?

2021-03-12 04:10 UTC, howardjohn commented on mesh/v1alpha1/config.proto
> +      // Outbound traffic will be restricted to services defined in the
this comment is for registry only field

2021-03-12 04:11 UTC, howardjohn commented on mesh/v1alpha1/config.proto
> +      // required alternative mechanisms like Kubernetes `NetworkPolicy` should be configured.
authz policy cannot block egress traffic since they can just entirely bypass the sidecar

2021-03-12 13:58 UTC, linsun commented on mesh/v1alpha1/config.proto
> +      // Outbound traffic will be restricted to services defined in the
```suggestion
      // When `REGISTRY_ONLY` is configured, outbound traffic will be restricted to services defined in the
```

2021-03-12 13:59 UTC, linsun commented on mesh/v1alpha1/config.proto
> +      // required alternative mechanisms like Kubernetes `NetworkPolicy` should be configured.
I see, is this for your change in sidecar.proto also or just for external traffic?

2021-03-12 15:51 UTC, howardjohn commented on mesh/v1alpha1/config.proto
> +      // required alternative mechanisms like Kubernetes `NetworkPolicy` should be configured.
That is just how authz works, its only on the inbound side.

2021-03-12 15:51 UTC, howardjohn commented on mesh/v1alpha1/config.proto
> +      // Outbound traffic will be restricted to services defined in the
We don't follow this form in other APIs, for example https://istio.io/latest/docs/reference/config/networking/destination-rule/#ClientTLSSettings-TLSmode

2021-03-13 02:53 UTC, nrjpoddar approved these changes

2021-03-13 03:10 UTC, linsun commented on mesh/v1alpha1/config.proto
> +      // required alternative mechanisms like Kubernetes `NetworkPolicy` should be configured.
Thanks!  Makes total sense now

2021-03-13 03:10 UTC, linsun approved these changes

2021-04-29 17:57 UTC, closed without merging