rename document_url to documentUrl
istio/api pull request #1867
Opened 2021-02-01 03:12 UTC by adiprerepa

Didn't expect it to require an api change.

for [istio/istio#30514](https://github.com/istio/istio/issues/30514)

cc @howardjohn

2021-02-01 03:12 UTC, istio-testing commented
@adiprerepa: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build_api | 4995a571cfd88f40353b803f1bbc0874283649d0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/1867/build_api/1356078027888398336) | `/test build_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-01 03:13 UTC, istio-testing commented
@adiprerepa: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build_api | 4995a571cfd88f40353b803f1bbc0874283649d0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/1867/build_api/1356078027888398336) | `/test build_api`
release-notes_api | 4995a571cfd88f40353b803f1bbc0874283649d0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/1867/release-notes_api/1356078027938729984) | `/test release-notes_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-01 16:04 UTC, howardjohn requested changes
All proto fields are snake_case, the generated json/yaml will still be camel case though

2021-02-02 04:48 UTC, adiprerepa commented
ah, right. forgot.

2021-02-02 04:48 UTC, closed without merging