Change `http2MaxRequests` setting to `maxRequests`
istio/api pull request #1871
Opened 2021-02-03 10:58 UTC by kailun-qin

The combination of H1 and H2 conn_pool implementations makes `max_requests` to
work for both H1 and H2 in Envoy proxy
(https://github.com/envoyproxy/envoy/issues/9215).

In accordance with this change, this patch updated the field `http2MaxRequests`
of `ConnectionPoolSettings.HTTPSettings` in DestinationRule API to `maxRequests`
to resolve the outdated H1 only implications/misunderstandings for the field.

Addresses https://github.com/istio/istio/issues/27473

Signed-off-by: Kailun Qin <kailun.qin@intel.com>

2021-02-03 10:59 UTC, istio-testing commented
@kailun-qin: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_api | 903f20c26cf1d6aa30178981f4032613c4fa4ca2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/1871/release-notes_api/1356920063591976960) | `/test release-notes_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-03 14:21 UTC, ramaraochavali commented on networking/v1alpha3/destination_rule.proto
> +    int32 max_requests = 2;
We can not change these names now as it will break existing deployments. We have to follow the deprecation process

2021-02-03 15:56 UTC, howardjohn requested changes
Adding a new field is probably a good idea, and hiding the old one - but we must support both indefinitely

2021-02-03 15:56 UTC, howardjohn commented on networking/v1alpha3/destination_rule.proto
> +    int32 max_requests = 2;
strong +1 here

2021-02-03 16:33 UTC, costinm commented on networking/v1alpha3/destination_rule.proto
> +    int32 max_requests = 2;
I assume this and http1_max_pending_requests will also need to be deprecated, new field added - and some tooling in istioctl before we even consider removing the old field and behavior. 

An alternative is to just change the documentation - "Istio may upgrade HTTP/1.1 requests to HTTP/2 internally, this setting will cover both HTTP/1.1 and HTTP/2 requests". That's what we plan to do with BTS AFAIK, everything including TCP will be over H2. 

If we add a new field - we should also consider BTS, and move it up, since TCP will also be treated as a long-lived H2.

2021-02-03 16:50 UTC, ramaraochavali commented on networking/v1alpha3/destination_rule.proto
> +    int32 max_requests = 2;
I was thinking about update the doc as @costinm mentioned. IMO, that is better - it is not worth the churn to add a new field and retain the old field forever.

2021-02-03 17:19 UTC, kailun-qin commented on networking/v1alpha3/destination_rule.proto
> +    int32 max_requests = 2;
[http1_max_pending_requests](https://github.com/envoyproxy/envoy/blame/main/docs/root/intro/arch_overview/upstream/circuit_breaking.rst#L26) might be slightly different since it involves extra settings to cover behaviors of H2.

Anyway, marking BTS related issues here: https://github.com/istio/istio/issues/24540, https://github.com/istio/istio/issues/25713.

2021-03-04 00:03 UTC, istio-testing commented
@kailun-qin: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2024-05-15 23:32 UTC, closed without merging