Fix broken links for locations
istio/api pull request #1919
Opened 2021-03-17 07:13 UTC by shamsher31

Similar to https://github.com/istio/api/pull/1907

Other `kubectl explain kind` are also have a broken links.

```
$ k explain Gateway.spec
KIND:     Gateway
VERSION:  networking.istio.io/v1beta1

RESOURCE: spec <Object>

DESCRIPTION:
     Configuration affecting edge load balancer. See more details at:
     https://istio.io/docs/reference/config/networking/gateway.html
```

```
$ k explain WorkloadGroup.spec
KIND:     WorkloadGroup
VERSION:  networking.istio.io/v1alpha3

RESOURCE: spec <Object>

DESCRIPTION:
     Describes a collection of workload instances. See more details at:
     https://istio.io/docs/reference/config/networking/workload-group.html
```

2021-03-17 15:53 UTC, howardjohn approved these changes
we should add a redirect if possible as well

2021-03-17 15:57 UTC, shamsher31 commented
> we should add a redirect if possible as well

I found later today that If we remove the `.html` extension, the redirect happens automatically (even though `/latest` was not there in the URL). But both achieve the same thing so I'm keeping `/latest` in the URL for now.

2021-03-17 16:33 UTC, ericvn commented
Note my comment in another thread that latest caused an issue in the docs where we can't consume the change and I will look at that at some point.

2021-03-17 17:16 UTC, ericvn commented
Looking at the scrapping code, it only pulls files whose location contains `https://istio.io/docs`. The logic basically converts the location to be a directory within the istio repo, and that repo does not have `latest` within it's directory structure so no reason to try copying the file. We would need to update the code which copies the files to also strip `latest` from the location the file is placed.

Earlier, I had made some changes so links within the docs could be updated to include `latest` and we strip that portion out of the URLs after copying the file so links point to actual locations (there is no redirection).

2021-03-17 17:26 UTC, ericvn commented
@shamsher31 Based on the above, I think if you removed `latest`, the istio.io script copying the file would work correctly, and removing the `.html` will make the location: value be a link that someone could put in a browser and it would be found. So something like:
```
https://istio.io/docs/reference/config/istio.analysis.v1alpha1
```
seems to make sense. I haven't verified that the removal of the .html won't break something else.

2021-03-17 18:40 UTC, ericvn commented
As a quick test, I created a branch with a revert of the earlier PR (so I can get the linter to pass) plus one of the changes in this PR: https://github.com/ericvn/api/commit/ebc3381af07df6a4cabd53e684dbaf1e4d666501

I then ran the istio.io code against that branch, which copied the files. I ran a `make lint` which passed as well as a `make serve` and tested the pages.

Based on that, it seems that simply removing the `.html` will work.

If it doesn't make sense to remove the `.html`, maybe @davidhauck can help with the redirection, or I will need to do some change in the scrapping script to also pull pages with a `location:` containing `latest` and remove that during the copy.

2021-03-17 19:07 UTC, davidhauck commented
The logic for the redirect adds a redirect for every page by removing "/latest" from the path and redirecting it to the path.

E.g. there is a redirect for:
docs/reference/config/networking/gateway -> latest/docs/reference/config/networking/gateway

There is not a redirect for:
docs/reference/config/networking/gateway.html -> latest/docs/reference/config/networking/gateway

If adding this redirect will make things easier, I could add it. We should try to ensure page names should be formatted like `docs/reference/config/networking/gateway` and NOT like `docs/reference/config/networking/gateway.html`

2021-03-17 21:17 UTC, ericvn commented
@davidhauck We have code today to strip the `.html` from the end of the location if it exists when copying the file.

I created https://github.com/istio/istio.io/pull/9287 which will allow the location to have `latest` or not, the file will still be scraped. Once merged, we should allow locations with to without `latest` and if there is a `.html` at the end, it is removed from the destination file location.

`location: https://istio.io/latest/docs/reference/config/security/authorization-policy.html` -> `docs/reference/config/security/authorization-policy`

`location: https://istio.io/docs/reference/config/security/authorization-policy.html` -> `docs/reference/config/security/authorization-policy`

`location: https://istio.io/docs/reference/config/security/authorization-policy.` -> `docs/reference/config/security/authorization-policy`

2021-03-17 21:32 UTC, ericvn commented
We will want to revert the other PR to remove `latest` (maybe just do here).

2021-03-18 04:51 UTC, shamsher31 commented
> We will want to revert the other PR to remove `latest` (maybe just do here).

Yup, I will also update https://github.com/istio/api/pull/1907 here.

2021-03-18 04:59 UTC, shamsher31 commented
> @shamsher31 So, once that PR is done, I think the locations can basically stay the same (without latest and with .HTML).

I will keep this PR open for now. Once redirect is done. We can either close this or merge.

2021-03-18 18:22 UTC, ericvn commented
@shamsher31 So the redirection PR is in for istio.io release-1.9 and the original locations like: `https://istio.io/docs/reference/config/istio.analysis.v1alpha1.html` no longer get a 404, but actually end up on pages.

2021-03-19 05:24 UTC, shamsher31 commented
@ericvn Thanks for verifying.

2021-03-19 13:11 UTC, ericvn requested changes

2021-03-19 13:11 UTC, ericvn commented on security/v1beta1/authorization_policy.proto
> +// $location: https://istio.io/latest/docs/reference/config/security/authorization-policy
@shamsher31 Remove the `latest` here.

2021-03-19 13:13 UTC, ericvn commented
As for adding back the `.html` location, it doesn't need to be removed anymore.

2021-03-19 14:17 UTC, shamsher31 commented on security/v1beta1/authorization_policy.proto
> +// $location: https://istio.io/latest/docs/reference/config/security/authorization-policy
Done.

2021-03-19 14:19 UTC, shamsher31 commented
> As for adding back the `.html` location, it doesn't need to be removed anymore.

@ericvn Updated the PR to only remove `latest` and keeping `.html` as it is (will be handle by redirect rule). Thanks.

2021-03-19 14:44 UTC, ericvn approved these changes
LGTM. Basically this is a revert of #1907. The fix for the original issue was adding istio.io redirects.

2021-03-19 15:11 UTC, shamsher31 commented
redirect rule PR: https://github.com/istio/istio.io/pull/9288

2021-03-22 13:40 UTC, ericvn commented
@istio/technical-oversight-committee Looking for approval for this one to remove the blockage of reference doc updates into istio.io. As noted, this is a revert of #1907 and the original issue was fixed instead by istio/istio.io#9288.

2021-03-22 14:41 UTC, nrjpoddar approved these changes

2021-03-22 14:50 UTC, merged