Add WasmExtension API
istio/api pull request #1940
Opened 2021-04-06 14:41 UTC by dgn

Implementing [Design Doc: Wasm Extensions API](https://docs.google.com/document/d/15GQnhOpLfvgyOZ8VDF5KD-q2cjXEMLdTQMm0YPswIu0/)

This also extends the `FilterClass` enum we currently have in EnvoyFilter. We might want to move it over to `extensions/` instead.

2021-04-06 14:41 UTC, istio-testing commented
Skipping CI for Draft Pull Request.
If you want CI signal for your change, please convert it to an actual PR.
You can still manually trigger a test run with `/test all`

2021-04-06 14:42 UTC, dgn commented
/test all

2021-04-06 14:42 UTC, istio-testing commented
@dgn: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_api | e8897d4892648edb625dd295cb5ff88161920749 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/1940/release-notes_api/1379444382570123264) | `/test release-notes_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-06 14:47 UTC, dgn commented
/test all

2021-04-09 20:52 UTC, linsun commented on extensions/v1alpha1/wasm.proto
> +  istio.type.v1beta1.WorkloadSelector workload_selector = 5;
The way the proposed API is only designed for local workloads correct? What is the thought process to selectively select the workload for a or two other clusters?

You may be thinking we could leverage the MCS expose + import service API but I don't think that makes sense as I could be deploying Wasm extensions to workloads that are not exposed outside of the cluster.

2021-04-12 07:38 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  istio.type.v1beta1.WorkloadSelector workload_selector = 5;
do we have such cluster/mesh selectors anywhere else? I would imagine you would label them differently, that would certainly work with this API

2021-04-12 14:40 UTC, howardjohn commented on extensions/v1alpha1/wasm.proto
> +  istio.type.v1beta1.WorkloadSelector workload_selector = 5;
@linsun what makes you think its local workloads? Everything else selects across all clusters - since the config only lives in one cluster?

2021-04-13 01:55 UTC, linsun commented on extensions/v1alpha1/wasm.proto
> +  istio.type.v1beta1.WorkloadSelector workload_selector = 5;
So the reason I am asking this question is we have a similar Solo API called [WasmDeployment](https://docs.solo.io/gloo-mesh/main/guides/wasm_extension/#deploy-the-filter) and that API allows users to specify which cluster this WasmDeployment is for.  So I'm trying to understand how this could be mapped to Istio API.

IIUC, @dgn, in this API, the workload selector is only for the local cluster in multi primary user case so basically Istio selects the matching workload based on the selector and apply the Wasm extension to the workload. This means if I have reviews in cluster 1 and cluster 2, and if I want this Wasm extension to be applied to reviews in both of these clusters, I would deploy a  Wasm resource to both clusters

@howardjohn I think you are referring to primary-remote scenario, which I agree the Istio config is applied to all clusters.

2021-04-13 01:58 UTC, howardjohn commented on extensions/v1alpha1/wasm.proto
> +  istio.type.v1beta1.WorkloadSelector workload_selector = 5;
In all Istio APIs currently, which I would assume this follows suite, workload selectors apply to all clusters. If we were to change it I would want to change it to all APIs which is a major undertaking - but this one should be consistent?

2021-04-13 02:21 UTC, linsun commented on extensions/v1alpha1/wasm.proto
> +  istio.type.v1beta1.WorkloadSelector workload_selector = 5;
Perhaps I am missing something, workload selectors apply to all clusters today.. that is not in multi-primary scenario, right?

In multi-primary, can I test this Wasmn resource with reviews in cluster 1 first and not impact reviews in cluster 2?  Do I have to create 2 different labels which I would rather avoid?

2021-04-13 02:23 UTC, howardjohn commented on extensions/v1alpha1/wasm.proto
> +  istio.type.v1beta1.WorkloadSelector workload_selector = 5;
Pilot doesn't care whether its multi-primary or not. It will apply the config to all workloads with the label in any cluster.

However, if you only create the WASM in cluster 1, and only pods from cluster 1 connect to the istiod running cluster 1, then you would effectively have it apply only to a single cluster.

2021-04-13 09:01 UTC, hzxuzhonghu commented on extensions/v1alpha1/wasm.proto
> +  repeated string image_pull_secrets = 4;
if no namespace specified, use that in this config namespace?

2021-04-13 09:13 UTC, hzxuzhonghu commented on extensions/v1alpha1/wasm.proto
> +  google.protobuf.Int64Value priority = 7;
We donot have this for any other apis

2021-04-13 09:40 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  google.protobuf.Int64Value priority = 7;
that's right. for other APIs, we generally use the creation time to order them (usually one overrrides the other). if you have multiple extension that depend on each other and are in the same phase, both are valid though and an explicit ordering is necessary

2021-04-13 10:01 UTC, hzxuzhonghu commented on extensions/v1alpha1/wasm.proto
> +  google.protobuf.Int64Value priority = 7;
I understand for wasm extensions, pilot-agent fetches them all, how does the order matter? Not sure i miss some context.

2021-04-13 10:47 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  google.protobuf.Int64Value priority = 7;
this is about the order of filters in the filter chain. there are two levels for ordering: the `phase` which is above this determines roughly where in the filter chain the wasm extension will end up ("before stats", "before authz"). if you have multiple wasm extensions with the same `phase` deployed to the same workload, you can use `priority` to determine the ordering within a `phase`, should this be necessary. it will not be necessary in most cases

2021-04-13 10:47 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  repeated string image_pull_secrets = 4;
that's right, will add

2021-04-13 10:48 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  google.protobuf.Int64Value priority = 7;
Order matters when one filter produces a piece of information like metadata or header that another filter uses. 
in EnvoyFilter api we use name relative ordering. Here instead of name relative, we use the int value for ordering. When it is not specified or specified to the same value  we will have to define some behavior though, or state that the order is undefined.

2021-04-13 10:51 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  google.protobuf.Int64Value priority = 7;
good point, I will add a comment. the idea is that if `priority` is not set, the ordering will still always be deterministic- ie it will be derived from the information in the `WasmExtension` by istiod, so the same two `WasmExtensions` will always be in the same order

2021-04-13 10:56 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  istio.type.v1beta1.WorkloadSelector workload_selector = 5;
@linsun we do not have any other api that is cluster specific today. This api uses an existing istio.type.v1beta1.WorkloadSelector message. If you want to propose cluster awareness (or location, or anything other than labels) you should do it as a separate proposal.

2021-04-13 10:58 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  google.protobuf.Int64Value priority = 7;
@dgn can you update the comment to cover unspecified or specified as the same value?

2021-04-13 12:00 UTC, hzxuzhonghu commented on extensions/v1alpha1/wasm.proto
> +  google.protobuf.Int64Value priority = 7;
understood

2021-04-13 12:04 UTC, hzxuzhonghu commented
How could i apply this to a specific service port? inbound and outbound?

2021-04-13 12:19 UTC, istio-testing commented
@dgn: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_api | 7ac22e357b51003ec9e80d3f1d19e238629f05cc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/1940/gencheck_api/1381944983157739520) | `/test gencheck_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-13 12:53 UTC, dgn commented
> How could i apply this to a specific service port? inbound and outbound?

Very good question. In my current PoC, it will be applied to all inbound HTTP filter chains of the service ports. We might want to limit it to specific ports, but I considered this an extension we can add later.

I don't think we should apply to outbound listeners as it makes the system quite complex to reason about (different behaviour depending on which service is sending the request)

2021-04-13 13:14 UTC, linsun commented on extensions/v1alpha1/wasm.proto
> +  istio.type.v1beta1.WorkloadSelector workload_selector = 5;
> Pilot doesn't care whether its multi-primary or not. It will apply the config to all workloads with the label in any cluster.

@howardjohn What is the value to apply the config to all workloads with the label in ANY cluster if each cluster has its own Istiod?

2021-04-13 13:15 UTC, linsun commented on extensions/v1alpha1/wasm.proto
> +  istio.type.v1beta1.WorkloadSelector workload_selector = 5;
> @linsun we do not have any other api that is cluster specific today. This api uses an existing istio.type.v1beta1.WorkloadSelector message. If you want to propose cluster awareness (or location, or anything other than labels) you should do it as a separate proposal.

@mandarjog I am not proposing adding cluster to this API yet.  I am trying to understand the semantics of this API... wanted to see if we could translate Solo's Wasmdeployment resource to this new Wasm resource.

2021-04-13 13:53 UTC, linsun commented on extensions/v1alpha1/wasm.proto
> +  string image = 2;
What about non OCI compliant image?

2021-04-13 13:55 UTC, linsun commented on extensions/v1alpha1/wasm.proto
> +  string image = 2;
We had users wanted to explore local files for our Wasm filters - see https://github.com/solo-io/gloo-mesh/blob/v1.0.1/api/enterprise/networking/v1beta1/wasm_deployment.proto#L45

2021-04-13 14:49 UTC, howardjohn commented on extensions/v1alpha1/wasm.proto
> +  repeated string image_pull_secrets = 4;
How does this actually work? How does the proxy get the secret to pull the image?

2021-04-13 14:49 UTC, howardjohn commented on extensions/v1alpha1/wasm.proto
> +  string image = 2;
Perhaps a oneof makes sense here?

2021-04-13 14:49 UTC, linsun commented
Another q: If I have multiple Wasm images, do I need to create one Wasm resource for each Wasm image/Wasm filter for a given workload?

2021-04-13 17:10 UTC, smawson commented on extensions/v1alpha1/wasm.proto
> +  istio.type.v1beta1.WorkloadSelector workload_selector = 5;
Just mentioning that the semantics here are not just for this API, but for all of Istio. We need to be consistent in our configuration application across the project. So maybe uplevel the conversation out of this PR and into a discussion in TOC or something if we want to talk about how config gets applied to particular endpoints and how to take cluster etc. into account.

2021-04-13 17:10 UTC, smawson commented on extensions/v1alpha1/wasm.proto
> +  istio.networking.v1alpha3.EnvoyFilter.Patch.FilterClass phase = 6;
Let's not take a dependency on EnvoyFilter and pull that enum out into its own thing that we can define here.

I think the values/semantics are actually pretty good (which phase to run this was extension during) but this shouldn't depend on EnvoyFilter proto.

2021-04-13 17:10 UTC, smawson commented on extensions/v1alpha1/wasm.proto
> +  istio.networking.v1alpha3.EnvoyFilter.Patch.FilterClass phase = 6;
Also do we need an option to run an extension before the istio authentication filters?

2021-04-13 17:57 UTC, asraa commented on extensions/v1alpha1/wasm.proto
> +  string image = 2;
if we have a oneof we can package the url and OCI-specific `image_pull_secrets` into a message, and include a way to specify a public key to verify a container signature

a message specific for local files could analogously (if people want to extend this) have a path to a signature file/public key

2021-04-13 18:42 UTC, louiscryan commented on extensions/v1alpha1/wasm.proto
> +  // Can be one of `IfNotPresent`, `Always`. Only relevant when images
should be enum

2021-04-13 18:49 UTC, louiscryan commented on extensions/v1alpha1/wasm.proto
> +  istio.networking.v1alpha3.EnvoyFilter.Patch.FilterClass phase = 6;
enum likely also needs refinement  @mandarjog

2021-04-13 18:52 UTC, bianpengyuan commented
> I don't think we should apply to outbound listeners as it makes the system quite complex to reason about (different behaviour depending on which service is sending the request)

@dgn I disagree. Manipulate request at outbound (including gateway) and refresh routing accordingly are probably one of the most common use cases that user would want with Wasm extensions. I think for now, at outbound, we can make it only support injecting filters at listener level. Envoy Wasm extension does not yet support per route config anyway.

2021-04-13 19:32 UTC, louiscryan commented on extensions/v1alpha1/wasm.proto
> +message WasmExtension {
@istio/technical-oversight-committee 

I understand this has probably been discussed but there doesn't seem much reason from this API mechanism not to support something other than WASM. I know we want to promote WASM but I don't want to have too many APIs for extensions.

Can we push the wasm-config into a oneof and validate that we can support 'providers' as the other option ?

@mandarjog

2021-04-13 19:59 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  string image = 2;
@linsun @dgn @knrc I think we need to re-open the one off discussion.

Others: We had a split verdict on if OCI was the only way, or we should support other means.
It was possible to deliver HTTP based solution in 1.10, but during the compromise we delayed it to 1.11, kept it as OCI and we will add http (or other means) later.

2021-04-13 19:59 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  istio.networking.v1alpha3.EnvoyFilter.Patch.FilterClass phase = 6;
@smawson @louiscryan we will relocate the FilterClass and amend enums in a separate PR after some more discussion here.

2021-04-13 19:59 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +message WasmExtension {
@dgn @knrc @linsun @nrjpoddar We have discussed it at length in the wasm-sig. 
We also validated it against wasm, lua and to a lesser extent rate-limit api.

The user interface here is the `CR` not the message, and up leveling the placement configuration and pushing the inner configuration inside the WasmExtension message would make sense.

The only issue one of UX / and visibility of `Wasm` itself. A top level CRD called Wasm raises the visibility.
Can we have structural inheritance (by proto templates ?) so that the we only maintain one structure by get around proto  inheritance limitations.

2021-04-13 20:10 UTC, dgn commented
> > I don't think we should apply to outbound listeners as it makes the system quite complex to reason about (different behaviour depending on which service is sending the request)
> 
> @dgn I disagree. Manipulate request at outbound (including gateway) and refresh routing accordingly are probably one of the most common use cases that user would want with Wasm extensions. I think for now, at outbound, we can make it only support injecting filters at listener level. Envoy Wasm extension does not yet support per route config anyway.

My comment was really only about sidecar inbound vs outbound listeners - I agree `WasmExtensions` should also work on gateway outbound listeners. But are you suggesting we should also support injecting into sidecar outbound listener filter chains?

2021-04-14 02:45 UTC, linsun commented on extensions/v1alpha1/wasm.proto
> +  istio.type.v1beta1.WorkloadSelector workload_selector = 5;
Agreed, it is across all APIs.  The question came up specifically here is because the comments were not clear.

I can try create some doc for this.  If anyone else is interested, let me know!

2021-04-14 02:48 UTC, linsun commented on extensions/v1alpha1/wasm.proto
> +message WasmExtension {
wouldn't Wasm deserve its own custom resource given the importance of it?  Or do we expect vendors to build some abstraction on top of it?  If it is later, I have no issue to be a generic provider custom resource.

2021-04-14 04:37 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +message WasmExtension {
I think Wasm does need it own top level `CRD` so we can have `wasm.istio.io/blah` or something similar.
However there is still a need to have consistency between all configuration resources that describe `when and where` a specific function or feature is enabled. 

`workload selection, filterchain selection, port selection, direction selection` should all be common. 
If we define a common message that includes the above, with a definition of overrides work, we can use that in the place of `workloadselector`

2021-04-15 23:57 UTC, louiscryan commented on extensions/v1alpha1/wasm.proto
> +  istio.type.v1beta1.WorkloadSelector workload_selector = 5;
Does k8s intend to standardize a synthetic cluster label just like they have for namespace IIRC

2021-04-16 00:12 UTC, louiscryan commented on extensions/v1alpha1/wasm.proto
> +message WasmExtension {
I think I'm fine with a type-per if there aren't going to be too many. Right now are we expecting anything more than wasm and provider?

Since workloadSelector is a common top-level type can we push all of the other selection stuff into a nested type so it can be shared?

2021-04-16 14:34 UTC, linsun commented on extensions/v1alpha1/wasm.proto
> +  istio.type.v1beta1.WorkloadSelector workload_selector = 5;
Does anyone know more about this synthetic cluster label?  that is interesting. @howardjohn @smawson @nmittler

2021-04-19 08:42 UTC, dgn commented
> Another q: If I have multiple Wasm images, do I need to create one Wasm resource for each Wasm image/Wasm filter for a given workload?

yes

2021-04-19 08:44 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  repeated string image_pull_secrets = 4;
in the current design, the agent is responsible for fetching and unpacking the OCI images, so the agent would have to fetch the secrets using client-go prior to that

2021-04-19 14:32 UTC, howardjohn requested changes
I don't think this is implementable in its current state due to the secret reading.

2021-04-19 14:32 UTC, howardjohn commented on extensions/v1alpha1/wasm.proto
> +  repeated string image_pull_secrets = 4;
I do not think this is viable. Importing client-go into the agent adds major overhead (ie invert this: https://mobile.twitter.com/karlstoney/status/1367134238613663744). Additionally, this would require giving ~every pod RBAC permissions for secrets. The load from every single pod in the cluster opening k8s watches is also likely to kill and non-trivial cluster.

2021-04-19 14:44 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  repeated string image_pull_secrets = 4;
> I do not think this is viable. Importing client-go into the agent adds major overhead (ie invert this: https://mobile.twitter.com/karlstoney/status/1367134238613663744). 

that would be an argument for moving the pulling of images to a central component, either istiod itself or something else. I don't think it means the API is unimplementable.

>Additionally, this would require giving ~every pod RBAC permissions for secrets. The load from every single pod in the cluster opening k8s watches is also likely to kill and non-trivial cluster.

All pods have access to secrets in their namespace by default. For secrets outside the pod namespace, yes, users would have to make sure they have access

2021-04-19 14:53 UTC, howardjohn commented on extensions/v1alpha1/wasm.proto
> +  repeated string image_pull_secrets = 4;
> I don't think it means the API is unimplementable.

I agree, but I would not feel comfortable approving an API that doesn't also have a planned implementation?

> All pods have access to secrets in their namespace by default. 

For mounting yes, but not for reading through the API, right? Since this is dynamic, they would need to read through the API.

2021-04-19 14:54 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  repeated string image_pull_secrets = 4;
I would also like to understand the overhead being introduced by client-go that you mentioned. Is this a concern regarding binary size? I wouldn't think of the agent as becoming a full-fledged controller, but rather use individual API calls to fetch the Secrets. There shouldn't really be runtime penalties in that, but maybe I'm missing something

2021-04-19 14:55 UTC, howardjohn commented on extensions/v1alpha1/wasm.proto
> +  repeated string image_pull_secrets = 4;
Yes, just compiling in the library adds to the RAM in the tweet, and binary size.

2021-04-19 14:56 UTC, howardjohn commented on extensions/v1alpha1/wasm.proto
> +  repeated string image_pull_secrets = 4;
It is also fairly incompatible with VMs.

2021-04-19 15:07 UTC, howardjohn commented
Thanks @mandarjog . Can you send the link to the design doc for those implementation ideas? I have potential concerns with all 3 options and want to make sure we don't approve an un-implementable API

2021-04-19 15:24 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  repeated string image_pull_secrets = 4;
> > All pods have access to secrets in their namespace by default.
> 
> For mounting yes, but not for reading through the API, right? Since this is dynamic, they would need to read through the API.

That's right, nevermind. I had assumed that this was the case by default. Makes sense that it isn't though. So yes, a user would have to guarantee that all pods that need to use an Extension have access to the pullSecret, should a pullSecret be required. It's not a blocker for me personally, but I understand the concern. Pulling from a central component would alleviate this

2021-04-19 15:45 UTC, bianpengyuan commented on extensions/v1alpha1/wasm.proto
> +  repeated string image_pull_secrets = 4;
For istio-agent based fetching, we can make Wasm API only referencing local mounted secrets. That would remove concern of client-go and incompatibility with VMs. Although user would need a way to indicate secret mount, which I original thought ExtensionProvider would be a great fit for this.

2021-04-19 16:59 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  // If set to `Always`, istiod will always pull the latest version of
We should remove language about `istiod`, The API does not dictate that this be done in istiod.

2021-04-19 17:18 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  // <namespace>/<name>. Names that do not contain forward-slashes are
We should remove the "current namespace" part from here.
In one of  the designs we had an `ExtensionClass` that specified where how to get this information from. 
That explicitly detaches it from the point of use, I think it is cleaner that way.

2021-04-20 06:52 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  // If set to `Always`, istiod will always pull the latest version of
Fixed

2021-04-20 06:53 UTC, istio-testing commented
@dgn: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_api | ce3d91d0dc4a663b1b3d12d30e2bc12c5ce67d86 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/1940/gencheck_api/1384399608871915520) | `/test gencheck_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-20 06:54 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  // <namespace>/<name>. Names that do not contain forward-slashes are
why remove the local namespaces part? tbh I was considering removing the `<namespace>/<name>` syntax and just keeping the local references, because that is how it works in the `PodSpec`

2021-04-20 14:29 UTC, howardjohn commented on extensions/v1alpha1/wasm.proto
> +  // <namespace>/<name>. Names that do not contain forward-slashes are
I think the desired implementation is pretty important here. If we have some CSI driver, we probably want the secret in the namespace the daemonset runs in. But if its handled by the agent directly a centralized namespace seems pretty hard to implement

2021-04-20 15:08 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  // <namespace>/<name>. Names that do not contain forward-slashes are
@dgn we decided to start simple and keep the “where and how to get the extension from” and “where to apply the extension” in the same CR, but the semantics of “registration” and use are different. Implicit Local namespace makes sense for “use”, but not for “registration” imo.

2021-04-20 15:18 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  // <namespace>/<name>. Names that do not contain forward-slashes are
> Implicit Local namespace makes sense for “use”, but not for “registration” imo.

From the user's perspective, that doesn't matter. From an implementation perspective, adding in the `WasmExtension`'s `metadata.namespace` isn't hard to do, either, so not sure I understand. You can always construct the full NamespacedName easily

2021-04-20 15:29 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  // <namespace>/<name>. Names that do not contain forward-slashes are
If we have one extension deployed everywhere, which is common, we will have to distribute those secrets to every namespace.

2021-04-20 15:35 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  // <namespace>/<name>. Names that do not contain forward-slashes are
but maybe you're right @howardjohn and this field doesn't make so much sense: if we go for a central solution (like the CSI driver), it's probably easier to configure global pullSecrets when setting that up

2021-04-20 15:59 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  // <namespace>/<name>. Names that do not contain forward-slashes are
I don’t think global secrets is the answer either. We may need to pull extensions from different repos with different creds. Perhaps we can split the CR into registration and use? Or if we must keep it like this then we can use istiod to distribute secrets. It can distribute secrets to the csi driver or agent as well with the introduction of new xds (raw config) type since sds may not be easily usable.

2021-04-20 21:15 UTC, douglas-reid commented on extensions/v1alpha1/wasm.proto
> +message WasmExtension {
FWIW, the early proposals for Telemetry API tried to define a simplified common selection type. We, ultimately, did not include that in the Tracing bits for now, but we will need that functionality soon. We should make sure that whatever we use here meets the needs of the Telemetry API.

2021-04-20 21:22 UTC, douglas-reid commented on extensions/v1alpha1/wasm.proto
> +  istio.type.v1beta1.WorkloadSelector workload_selector = 5;
nit: in the Telemetry API, we used `selector` instead of `workload_selector`. we should be consistent.

2021-04-21 16:17 UTC, kyessenov commented on extensions/v1alpha1/wasm.proto
> +  repeated string image_pull_secrets = 4;
Maybe we can separate concerns for accessing the extension provider from the use of the extension? E.g. add a Wasm extension provider with pull secrets that is globally defined in MeshConfig, and reference the Wasm provider from this API. We could support both inlined and referenced Wasm extension provider with the intent to allow using secrets only from the referenced provider.

2021-05-12 17:58 UTC, istio-testing commented
@dgn: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build_api | 0a8d0e25438737f0e70dd94282fbb3b7ebe272d1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/1940/build_api/1392539358480830464) | `/test build_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-12 18:16 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  istio.type.v1beta1.WorkloadSelector workload_selector = 5;
updated

2021-05-12 18:18 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  // Can be one of `IfNotPresent`, `Always`. Only relevant when images
it's an enum now, but it's not ideal. The linter wants the values to be UPPER_SNAKE_CASE which would contradict k8s terminology, so I added an ignore line. Now that shows up in the docs. I don't really like it

2021-05-12 18:18 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  string image = 2;
there's a `oneof` now that allows to use either a Wasm module directly (either from local file:// or from http://) or an OCI image. when using an OCI image, you can also supply a signing_key now

2021-05-12 20:04 UTC, howardjohn commented on extensions/v1alpha1/wasm.proto
> +    string signing_key = 4;
is this the right terminology? From some googling "The signing key is the private key used in a digital signature. Contrast with verification key. See digital signature and public key cryptography." Also https://csrc.nist.gov/glossary/term/Key_Signing_Key.

Seems like this generally refers to the private key, not the public key.

Also if this is a URL, what protocol/format is used here? is HTTP valid or only HTTPS?

2021-05-12 20:04 UTC, howardjohn commented on extensions/v1alpha1/wasm.proto
> +  // <namespace>/<name>. Names that do not contain forward-slashes are
I am still not sure how this secret mechanism is implementable:
* The current implementation is fetching OCI in agent, which cannot reference secrets
* Secrets will exist in the namespace of the WASM yaml, which may be different from workloads, requiring ClusterRoleBindings to give permissions, which doesn't seem viable
* A WASM yaml can reference an arbitrary Secret in any namespace, which is not secure (for example, if I reference the root key in istio-system). How will we authorize this?

2021-05-12 21:44 UTC, mandarjog commented on networking/v1alpha3/envoy_filter.proto
> +      ROUTER = 4;
I think we **should not combine** this change in the Wasm PR.

2021-05-12 21:46 UTC, PiotrSikora commented on extensions/v1alpha1/wasm.proto
> +  google.protobuf.Struct config = 1;
I think we should have 2 set of configurations:
- configuration passed to the plugin (i.e. `configuration` in Envoy's `PluginConfig`),
- WasmVM (sandbox) configuration (i.e. Envoy's `VmConfig`, fail open and capability restrictions).

2021-05-12 21:46 UTC, PiotrSikora commented on extensions/v1alpha1/wasm.proto
> +    string signing_key = 4;
Agreed, I think it should be `signature_public_key` or something similar.

Also, since it's a string, what encoding do we exepect the public key to be provided in? Base64? Hex?

2021-05-12 21:46 UTC, PiotrSikora commented on extensions/v1alpha1/wasm.proto
> +  }
Wasm signatures are in the same - if not better - state as container signatures (i.e. there are existing tools, but there is no industry-wide standard, although we're working on it as part of WebAssembly CG), so support for them should be probably included here as well.

2021-05-12 21:55 UTC, douglas-reid commented on extensions/v1alpha1/wasm.proto
> +// WasmExtensions provides a mechanism to extend the functionality provided by
can we add a few example uses to the documentation here? maybe ones that demonstrate anticipated uses of `phase` and `priority` ?

2021-05-13 13:47 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +    // Credentials to use for image pulling.
Why a list ?

2021-05-13 13:58 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  // <namespace>/<name>. Names that do not contain forward-slashes are
We restrict the secret and the wasm config to be in the same namespace. This means whoever has access to the secrets can distribute them to workloads that need it.

This works fine for root namespace and individual namespaces as well.

for out-of-namespace secrets, istiod will have to enforce rbac. if that is not possible we will drop support for arbitrary secrets.

2021-05-13 15:14 UTC, howardjohn commented on extensions/v1alpha1/wasm.proto
> +  // <namespace>/<name>. Names that do not contain forward-slashes are
That does not seem to match the API comments:
```
// If the name contains a forward-slash, it will be interpreted as
// <namespace>/<name>.
```

is Istiod going to distribute the pull secrets to the agent? When a proxy connects and asks for a secret X, how will you determine if it can access it appropriately? Proxy identity only has namespace and SA, but WASM can reference arbitrary label selectors. We may have to have a known limitation that you can only scope the secret access to a full namespace?

2021-05-13 15:44 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  // <namespace>/<name>. Names that do not contain forward-slashes are
Fully qualified secret name is subject to being able to apply rbac. We can drop it to start with.

Wasm is a workload bound api. A wasm configuration in one namespace cannot inject filters in to arbitrary namespaces. namespace scoping is inherent for correct behavior.

root namespace behaves differently, consistent with other apis like EnvoyFilter. An admin can decide to inject filters into any namespace.

2021-05-13 15:47 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  // <namespace>/<name>. Names that do not contain forward-slashes are
That said, is there another way to send these secrets other than sds? Essentially we don’t want the proxy to “ask”, istiod should just send.

2021-05-13 15:48 UTC, howardjohn commented on extensions/v1alpha1/wasm.proto
> +  // <namespace>/<name>. Names that do not contain forward-slashes are
Embed them in the ECDS message perhaps? That is probably much easier to implement as well

2021-05-13 15:53 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  // <namespace>/<name>. Names that do not contain forward-slashes are
Let’s do that since, sds can ask for anything, where as inline secrets are better.

2021-05-13 15:55 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  // <namespace>/<name>. Names that do not contain forward-slashes are
I am wondering what is the size threshold at which istiod can’t just shove inline bytes.

2021-05-18 21:42 UTC, mandarjog commented on releasenotes/notes/add-wasm-extensions-api.yaml
> +area: telemetry
area: extensions

2021-05-25 16:49 UTC, istio-testing commented
@dgn: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_api | 6e914a8b82ac260ee50aa0da5bd99a94b1e746de | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/1940/release-notes_api/1397233244348354560) | `/test release-notes_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-25 16:49 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +message WasmExtension {
added

2021-05-25 16:52 UTC, istio-testing commented
@dgn: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-notes_api | 2930f8e0940b161626b1e6a749bf923f77b80187 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/1940/release-notes_api/1397233934839844864) | `/test release-notes_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-25 16:58 UTC, dgn commented
I just updated the PR with the set of latest changes, as discussed on our last SIG call. The changes are:
* Renamed `signing_key` to `verification_key`
* Renamed API to `WasmPlugin` (from `WasmExtension`). This is to better align with proxy-wasm where `plugin` is used.
* Made `pull_secret` a single string, and only allow referencing namespace-local secrets. This is to solve potential security issues with referencing secrets outside the namespace.
* Renamed `config` to `plugin_config` and also added `sandbox_config` (currently empty) to hold all Wasm VM-related settings

2021-05-25 16:58 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +    // Credentials to use for image pulling.
made it a simple string now

2021-05-25 16:58 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  }
done

2021-05-25 17:00 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  google.protobuf.Struct config = 1;
done

2021-05-25 17:02 UTC, dgn commented on networking/v1alpha3/envoy_filter.proto
> +      ROUTER = 4;
reverted

2021-05-25 17:28 UTC, PiotrSikora commented on extensions/v1alpha1/wasm.proto
> +// the Istio proxy through Web Assembly filters.
Nit: `Web Assembly` -> `WebAssembly`

2021-05-25 17:28 UTC, PiotrSikora commented on releasenotes/notes/add-wasm-extensions-api.yaml
> +    **Added** experimental WasmPlugin API to support extending proxy functionality with custom Web Assembly filters.
Nit: `Web Assembly` -> `WebAssembly`

2021-05-25 17:28 UTC, PiotrSikora commented on extensions/v1alpha1/wasm.proto
> +  google.protobuf.Struct plugin_config = 6;
Should this be `Struct` (vs `Any` or `string` or `bytes`)?

2021-05-26 09:25 UTC, dgn commented on releasenotes/notes/add-wasm-extensions-api.yaml
> +    **Added** experimental WasmPlugin API to support extending proxy functionality with custom Web Assembly filters.
fixed

2021-05-26 09:25 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +// the Istio proxy through Web Assembly filters.
fixed

2021-05-26 09:25 UTC, istio-testing commented
@dgn: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_api | 30a718bd53ecebb19cfde5d19e0bdf571255e4d8 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/1940/gencheck_api/1397483943359418368) | `/test gencheck_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-26 09:34 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  google.protobuf.Struct plugin_config = 6;
using `Struct` here allows users to use YAML when entering config so you don't need pipes in the k8s resources. I think it's a big UX improvement

2021-05-26 11:50 UTC, mathetake commented on extensions/v1alpha1/wasm.proto
> +  google.protobuf.Struct plugin_config = 6;
Please note that some languages (e.g. TinyGo and AssemblyScript) don't have standardized way of deserializing json/yaml/protobuf. See https://github.com/AssemblyScript/assemblyscript/issues/292 https://github.com/tinygo-org/tinygo/issues/447 for example.

2021-05-26 17:36 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  google.protobuf.Struct plugin_config = 6;
Are you suggesting that it could be toml or something else too? what is tinygo or assemblyscript using as configuration format today?


@dgn i like the yaml argument so we can accept yaml at input but send json into the plug-in, however like said earlier proxy-wasm does not mandate a structure. 
@PiotrSikora @kyessenov is mandating json reasonable ?

2021-05-26 19:36 UTC, PiotrSikora commented on extensions/v1alpha1/wasm.proto
> +  google.protobuf.Struct plugin_config = 6;
I agree that YAML input in Istio is a nice UX, but since Proxy-Wasm itself doesn't mandate JSON, it feels a bit restrictive. 

Although I'm not a big fan of it, perhaps we need a `oneof`?

2021-05-26 20:11 UTC, kyessenov commented on extensions/v1alpha1/wasm.proto
> +  google.protobuf.Struct plugin_config = 6;
It might be OK to mandate JSON. It forces a standard user experience, instead of mish-mash of TOML/JSON/whatever else.

2021-05-28 07:03 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  google.protobuf.Struct plugin_config = 6;
mandating JSON might have the benefit of us being able to parse it in the host and making the structure available to the plugin through the VM - then not every plugin developer has to worry about config parsing. FWIW envoy already has code to parse JSON efficiently

2021-06-01 21:42 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  google.protobuf.Struct plugin_config = 6;
WE discussed it in the Wasm-sig. The consensus is that we use `google.protobuf.struct` now. If we get user feedback we will add another field like `plugin_config_unstrcutured` of type `string`.

2021-06-06 23:47 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  google.protobuf.Struct plugin_config = 6;
Since we are keeping it as is, resolving the conversation.

2021-06-10 15:42 UTC, howardjohn commented on extensions/v1alpha1/wasm.proto
> +  string pull_secret = 4;
Sorry for keeping my hold on for so long, but I still do not understand how this is going to be implementable, and it doesn't seem like the POC does implement it?

2021-06-10 16:15 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  string pull_secret = 4;
I think the last agreement was that istiod reads the K8s secret and sends it through xDS where the agent intercepts it (it never actually reaches envoy) and uses it to pull

2021-06-10 16:15 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  string pull_secret = 4;
we restricted to same-namespace-as-resource to make sure that the user can not pull in secrets from other namespaces

2021-06-10 16:55 UTC, howardjohn commented on extensions/v1alpha1/wasm.proto
> +  string pull_secret = 4;
I see. And the secret would be in the same *cluster* as the WasmPlugin (ie config cluster) as well then I would think? Since we are not going to have permissions to read all secrets in all clusters

2021-06-10 17:01 UTC, howardjohn commented on extensions/v1alpha1/wasm.proto
> +  string pull_secret = 4;
And for root-namespace WASM, we would give access to any proxy requesting. For other namespaces, only those in that namespace (verified by identity).

SGTM. We may want to add a note about this in the API to warn users that they are essentially giving access to the Secret they reference. So `create` RBAC on WasmConfig also implies `read` Secret (in terms of behavior, not literally in the k8s RBAC  model)

2021-06-10 19:47 UTC, mandarjog commented
@smawson @louiscryan @linsun this is ready to go.

2021-06-16 16:30 UTC, smawson commented on extensions/v1alpha1/wasm.proto
> +  // The pull behaviour to be applied when fetching a OCI image. Only
```suggestion
  // The pull behaviour to be applied when fetching an OCI image. Only
```

2021-06-16 16:30 UTC, smawson commented on extensions/v1alpha1/wasm.proto
> +  PullPolicy pull_policy = 3;
If not specified, default is IfNotPresent?

2021-06-16 16:30 UTC, smawson commented on extensions/v1alpha1/wasm.proto
> +  // `rootID`). This is used to select a Wasm plugin from a module that
I don't understand the rootID comment, will users of this API understand what it means?

2021-06-16 16:30 UTC, smawson commented on extensions/v1alpha1/wasm.proto
> +  istio.type.v1beta1.WorkloadSelector selector = 9;
I think we usually put this at the top of the config?

2021-06-16 16:30 UTC, smawson commented on extensions/v1alpha1/wasm.proto
> +  istio.networking.v1alpha3.EnvoyFilter.Patch.FilterClass phase = 10;
I don't like this dependency on EnvoyFilter, can we move FilterClass out somewhere reusable instead?

Put it in type with WorkloadSelector

2021-06-16 16:30 UTC, smawson commented on extensions/v1alpha1/wasm.proto
> +  istio.networking.v1alpha3.EnvoyFilter.Patch.FilterClass phase = 10;
Since you refer to phase when talking about priority, maybe this should be Phase?

2021-06-17 00:59 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  istio.networking.v1alpha3.EnvoyFilter.Patch.FilterClass phase = 10;
@smawson I agree this is not a good dependency.
Can we have a follow up refactor once the user visible API gets in?

2021-06-17 01:55 UTC, hzxuzhonghu commented on extensions/v1alpha1/wasm.proto
> +  string sha256 = 2;
Is this a must, i donot see it in PodSpec

2021-06-17 01:55 UTC, hzxuzhonghu commented on extensions/v1alpha1/wasm.proto
> +  string verification_key = 5;
As a pure user, i am not sure what should i set for it

2021-06-18 12:11 UTC, asraa commented on extensions/v1alpha1/wasm.proto
> +  string verification_key = 5;
I imagine it could be optional to set, but if so it could be your organizations/trusted public key to verify a signature on OCI images if specifying one. I can help to implement one created by cosign (https://github.com/sigstore/cosign). If it's fetched by HTTP and the signature is embedded in the module, the verification could be checked at load by the runtime.

2021-06-28 05:57 UTC, mathetake commented on extensions/v1alpha1/wasm.proto
> +  // `rootID`). This is used to select a Wasm plugin from a module that
> This is used to select a Wasm plugin from a module that

this comment doesn't apply to Rust and Go SDK, so I suggest just delete the comment. At least the API should be SDK-agonistic.  cc @PiotrSikora

2021-06-28 06:00 UTC, mathetake commented on extensions/v1alpha1/wasm.proto
> +  // `rootID`). This is used to select a Wasm plugin from a module that
or maybe add something like `This is used to select a Wasm plugin from a module that contains multiple plugins built with AssemblyScript or C++ SDK.`

2021-06-28 10:24 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  string sha256 = 2;
it is required when deploying `.wasm` modules directly, but not when using OCI images

2021-06-28 15:06 UTC, istio-testing commented
@dgn: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_api | a7200fed0a3661430608eef114fe969ba2a01102 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/1940/gencheck_api/1409528254745808896) | `/test gencheck_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-06-28 15:10 UTC, linsun commented on extensions/v1alpha1/wasm.proto
> +  string sha256 = 2;
could we give some hints in the doc on how to get the value for sha256 from the .wasm module?

2021-06-28 15:11 UTC, linsun commented on extensions/v1alpha1/wasm.proto
> +  string pull_secret = 4;
could I specify the secret globally?  seems odd to require this w/ every Wasm deployment config.

2021-06-28 15:17 UTC, linsun commented on extensions/v1alpha1/wasm.proto
> +  SandboxConfig sandbox_config = 8;
how is this different from the plugin_config?

2021-06-28 15:19 UTC, linsun commented on extensions/v1alpha1/wasm.proto
> +  string pull_secret = 4;
Ok I see we can specify this globally in root namespace, if so, can we clarify that if it is specified globally or namespace, then no need to specify in the workload level unless you need to overwrite it?

2021-06-28 15:20 UTC, linsun commented on extensions/v1alpha1/wasm.proto
> +  istio.type.v1beta1.WorkloadSelector selector = 9;
+1, this should be the first thing to be configured (scope).

2021-06-28 18:07 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  SandboxConfig sandbox_config = 8;
This is [VM config](https://github.com/istio/istio/blob/3be04d7bdf922e308fb8b955b8e43e6651d05ca6/manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.11.yaml#L539).  `config.configuration` is consumed by the plugin and `config.vm_config` is consumed by the sandbox.

The expectation is that when a wasm plugin is published, it will contain doc (and metadata) to tell the user where to place the yaml snippet.

2021-06-28 18:11 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  string pull_secret = 4;
@linsun the secret is needed to pull the specific plugin from a registry. As such every registry/plugin can have a different key. 

We can add it to meshconfig and extend the provider concept to include "named fetchers", but I am not sure if that has better ergonomics than this.

2021-06-28 19:19 UTC, PiotrSikora commented on extensions/v1alpha1/wasm.proto
> +  // `rootID`). This is used to select a Wasm plugin from a module that
I don't think we should be mentioning specific SDKs, since the current state is unlikely to persist (either Rust/Go/Zig SDKs are going to add support for multiple plugins, or AS/C++ SDKs are going to remove it).

We could probably clarify the comment it a little bit, e.g.:
```
Some .wasm modules might require this value to select Wasm plugin to execute.
```

2021-06-29 20:52 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  string verification_key = 5;
inlined would work too, I guess

2021-06-29 21:01 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  istio.type.v1beta1.WorkloadSelector selector = 9;
makes sense. Should I then move phase and priority up as well, just after it?

2021-06-29 21:05 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  // `rootID`). This is used to select a Wasm plugin from a module that
Thanks, I updated the comment

2021-06-29 21:13 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  // Configuration for the Wasm sandbox the plugin will run in.
wasm-sig: hide from doc to start with.
We want to followup and add Env support right after.

2021-06-29 21:14 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  istio.networking.v1alpha3.EnvoyFilter.Patch.FilterClass phase = 10;
We will refactor this once the PR gets in. it will not be an API change.

2021-06-29 21:43 UTC, mandarjog commented
@istio/technical-oversight-committee Folks, we did an online review of the open items.
dgn will update the PR and it will be ready for re-review tomorrow.

2021-06-30 07:30 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  SandboxConfig sandbox_config = 8;
I removed the sandbox_config, as it is currently empty anyway. As soon as we add real config options, we can add it back

2021-06-30 08:22 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  string verification_key = 5;
it is now inline

2021-06-30 08:23 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  // Configuration for the Wasm sandbox the plugin will run in.
I completely removed the field. We can add it back once we actually add sandbox_config fields

2021-06-30 08:24 UTC, dgn commented
I addressed all the comments. PTAL.

Note that I removed the dependency on EnvoyFilter for now, and created a duplicate `PluginPhase` in this proto. We can reconcile the one in EnvoyFilter with this one in a follow-up and move it to `types/`.

I also added an example. If people have more examples, please send them to me and I will add them

2021-06-30 11:31 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +//   url: file:///opt/filters/openid.wasm
Should add an example of fetching from an oci registry with secrets.

2021-07-01 01:42 UTC, linsun commented on releasenotes/notes/add-wasm-extensions-api.yaml
> +- https://docs.google.com/document/d/15GQnhOpLfvgyOZ8VDF5KD-q2cjXEMLdTQMm0YPswIu0
Add a TODO to link to the real doc in istio.io when it is avail?

2021-07-01 01:56 UTC, linsun commented on extensions/v1alpha1/wasm.proto
> +//     openid_server: authn
is authn the opened_server that is defined somewhere?

2021-07-01 01:57 UTC, linsun commented on extensions/v1alpha1/wasm.proto
> +//     openid_realm: ingress
for opened_realm: I assume ingress is implied when the selector is `istio:ingressgateway`?  e.g. would it be a prob if I use the selector in line 46-47 but not use ingress as the opened_realm?

2021-07-01 01:58 UTC, linsun commented on extensions/v1alpha1/wasm.proto
> +//   namespace: istio-system
can we use istio-ingress as the namespace as we are recommending users to deploy ingress gateway in a ns that is different from istio-system now?

2021-07-01 02:06 UTC, linsun commented on extensions/v1alpha1/wasm.proto
> +    Always = 1;
which one is configured by default?  Or is the default `IfNotPresent` but `Always` for `latest` image?

2021-07-01 02:08 UTC, linsun commented on extensions/v1alpha1/wasm.proto
> +//   selector:
is this `selector` or `workloadSelector` here?

2021-07-01 02:12 UTC, linsun commented on extensions/v1alpha1/wasm.proto
> +    Always = 1;
Ok, I see later you mentioned default is IfNotPresent.  Would still like to understand behavior for latest image with default pull policy.

2021-07-01 02:13 UTC, linsun commented on extensions/v1alpha1/wasm.proto
> +  // against the registry when pulling the image.
If pull secret is in the root namespace, can I reuse it?  or do I have to copy to my ns first in order to use it?

2021-07-01 02:19 UTC, linsun commented
@dgn @mandarjog thank you and the team for addressing many of the comments. I think this one is getting easier to understand!

2021-07-01 02:28 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  // against the registry when pulling the image.
The pull secret needs to be in the same namespace as the configuration resource. The person configuring the configuration resource can read the secret and by using the api authorizing the secret to be sent to the proxies that need it.
So if the config resource is not in Istio-system then you will need to copy it.

2021-07-01 09:26 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +//   namespace: istio-system
oh, I didn't realize we do that now. sure

2021-07-01 09:27 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +//     openid_realm: ingress
this is arbitrary plugin configuration - it's not real config and only here to show how you would set plugin configuration :)

2021-07-01 18:17 UTC, howardjohn reviewed
A few minor syntax comments, generally looks good though!

2021-07-01 18:17 UTC, howardjohn commented on extensions/v1alpha1/wasm.proto
> +  string pull_secret = 5;
same naming nit as above, image_pull_secrets to match. That would be a list though - should we support a list like k8s does or do we only need a single one?

2021-07-01 18:17 UTC, howardjohn commented on extensions/v1alpha1/wasm.proto
> +  string pull_secret = 5;
I guess one big reason k8s needs a list is there may be multiple images but here we only have one

2021-07-02 09:03 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  optional string sha256 = 3;
this field is really for .wasm modules mostly. I just tried to reuse it for OCI images, but it seem that that is confusing people more than anything

2021-07-02 17:32 UTC, louiscryan commented on extensions/v1alpha1/wasm.proto
> +  // be at the end of the filter chain, right before the Router.
Really this is saying the control-plane will decide which is a little more specific than what UNSPECIFIED implies.

Even if the control-plane decides it seems like there are two forms:
- The plugin is 'well-known', i.e understood by the control plane code
- The plugin is referenced by something else in the API model and the action here is simply making it available. E.g. the provider idiom used elsewhere.

The 'well-known' case I think implies that some other identifying information in the API is used by the control plane to know what this thing is - is 'plugin_name' intended to be that? I think this needs to be clearly specified 

If there is intent to allow referencing from some other API resource a la the provider pattern that should also be called out.

2021-07-02 18:18 UTC, louiscryan commented on extensions/v1alpha1/wasm.proto
> +  // present in the config root namespace, it will be applied to all
@howardjohn @costinm @mandarjog 

I think in general we're trying to move away from config-root namespace and to rely on meshconfig instead for this kind of behavior. If we tie to config-root then we can't use this with revisions.

2021-07-02 18:21 UTC, howardjohn commented on extensions/v1alpha1/wasm.proto
> +  // present in the config root namespace, it will be applied to all
We do have the ability to scope it with an istio.io/rev label on the config, if desired. I actually thought we were moving in the other direction, moving things out of mesh config into proper CRDs which have root-namespace in the hierarchy. The new Telemetry is doing this, as is the proposed Proxyconfig. With DestinationRule, we just moved some mesh config settings into a root-namespace defaults DestinationRule.

2021-07-02 18:44 UTC, mandarjog commented
Inbound / outbound is missing, was somehow dropped from discussion at some point.
Thanks john.

We do not have any override semantics defined in the API.
This makes the current API strictly additive. For the use cases that are in front of us, It is fine.
But lets re-review this in light of the telemetry api that was just merged.

2021-07-02 18:56 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  // present in the config root namespace, it will be applied to all
@louiscryan even in the telemetry api, we do allow things like the following that modify the hardcoded defaults to something else.

```yaml
// apiVersion: telemetry.istio.io/v1alpha1
// kind: Telemetry
// metadata:
//   name: mesh-default
//   namespace: istio-system
// spec:
//   # no selector specified, applies to all workloads
//   metrics:
//   - providers:
//     - name: stackdriver
//     overrides:
//     - match:
//         metric: ALL_METRICS
//         mode: SERVER
//      disabled: true
```

Are you suggesting that we allow it in meshconfig as well?

2021-07-02 19:19 UTC, kyessenov commented
@mandarjog Outbound was explicitly removed from PoC early on. It would definitely complicate the discussion and the runtime does not support selection based on host/routes.

2021-07-02 19:31 UTC, mandarjog commented
@kyessenov in that case we should make it explicit that this is applied only in inbound. In the WIP pr, it seems to add filters in both places. 
inbound is the dominant use case, so it is fine thing to start with. 

I vaguely remember this being discussed in the wg, but the decision was not recorded.

2021-07-02 19:32 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  // present in the config root namespace, it will be applied to all
If we need to make a change , this is the time before 2 new apis get in :-)

2021-07-02 21:06 UTC, mandarjog commented
@mdhume will additive only API suffice for your use case?  At present there is not way for a workload to `remove` a plugin that was enabled at the root.

2021-07-05 12:29 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  // defaults to `docker://`, referencing an OCI image. Valid schemes
It does make more sense - I swapped out `docker://` for `oci://`

2021-07-05 12:30 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  PullPolicy pull_policy = 4;
done

2021-07-05 14:18 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  // be at the end of the filter chain, right before the Router.
I don't think we're planning to have a mechnism to place 'well-known' plugins. They will just be put at the end of the chain. The exact positioning depends on whether there are other plugins with UNSPECIFIED phase, in which case priority will determine ordering within this group (but they'll still all be at the end of the chain)

2021-07-05 14:19 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  string pull_secret = 5;
I made it `image_pull_secret` (not a list). it's a bit inconsistent, but I think that's alright

2021-07-05 16:36 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +    Always = 1;
I clarified the comment. It will be `Always` for `latest` tag

2021-07-07 00:43 UTC, mdhume commented
@mandarjog By additive only, do you mean that removal of the plugin from a workload would require deletion of the WasmPlugin resource? If that is the case, we should be ok since that is the existing behavior for the EnvoyFilter resource too.
What will be the migration plan for users to seamlessly move from EnvoyFilters to WasmPlugin resource?
Also saw a few comments above regarding where the filter will be applied, just wanted tooconfirm that in the current implementation if applied to Ingress gateways it will be attached to the outbound listeners? (since ingress primarily has outbound ones). For sidecars it would be important to have support to apply to only inbound or only outbound as certain functionality may only be applied for incoming or outgoing calls.
Was also wondering if there can be support for matching the proxy version like there is in EnvoyFilters? It's useful during upgrades since sometimes the wasm modules can be backwards incompatible.

2021-07-07 17:51 UTC, dgn commented
> @mandarjog By additive only, do you mean that removal of the plugin from a workload would require deletion of the WasmPlugin resource? If that is the case, we should be ok since that is the existing behavior for the EnvoyFilter resource too.
> 
> What will be the migration plan for users to seamlessly move from EnvoyFilters to WasmPlugin resource?

WasmPlugin will only cover the most basic use cases of injecting .wasm modules into the filter chain; it's not a full-fledged replacement - so having a migration plan for EnvoyFilter -> WasmPlugin won't make a lot of sense because the former covers so many more scenarios.

> Also saw a few comments above regarding where the filter will be applied, just wanted tooconfirm that in the current implementation if applied to Ingress gateways it will be attached to the outbound listeners? (since ingress primarily has outbound ones). For sidecars it would be important to have support to apply to only inbound or only outbound as certain functionality may only be applied for incoming or outgoing calls.

Yes, the WasmPlugin will be attached to outbound listeners for gateways, and inbound listeners for sidecars. Targeting to specific traffic directions and node types as well as support for outbound listeners on sidecars will be added later.

> Was also wondering if there can be support for matching the proxy version like there is in EnvoyFilters? It's useful during upgrades since sometimes the wasm modules can be backwards incompatible.

Not yet planned but we can add something for that. When the OCI packaging lands, the agent will easily be able to detect the supported envoy version and not inject an incompatible plugin. We'll have to see if we can possibly solve this in the packaging layer.

2021-07-07 18:28 UTC, louiscryan commented on extensions/v1alpha1/wasm.proto
> +  // present in the config root namespace, it will be applied to all
@howardjohn and I discussed this some. I'm OK with sticking the with root-ns pattern.

2021-07-07 20:10 UTC, louiscryan commented on extensions/v1alpha1/wasm.proto
> +  // be at the end of the filter chain, right before the Router.
OK, we can set aside well-known and 'referenced'

I think it's still useful to clarify the default behavior here. Can we make the default enum value NONE (i.e not bound) so we require the user to enter their intent. I suggest we use TAIL / LAST / <some-such> as an enum value to explicitly capture the placement intent.

@kyessenov

2021-07-08 17:20 UTC, mdhume commented
> > What will be the migration plan for users to seamlessly move from EnvoyFilters to WasmPlugin resource?
> 
> WasmPlugin will only cover the most basic use cases of injecting .wasm modules into the filter chain; it's not a full-fledged replacement - so having a migration plan for EnvoyFilter -> WasmPlugin won't make a lot of sense because the former covers so many more scenarios.
> 

Sure, I understand that the WasmPlugin will not cover all the features that the EnvoyFilter does, as the latter has a broader scope. However given we are already using EnvoyFilter to add a Wasm based envoy filter, what would be the approach for us to switch to using the WasmPlugin resource without breaking functionality in a production environment? If we add a WasmPlugin resource in addition to the existing EnvoyFilter it will result in the filter being added twice which is not desirable.

2021-07-08 18:12 UTC, dgn commented
> Sure, I understand that the WasmPlugin will not cover all the features that the EnvoyFilter does, as the latter has a broader scope. However given we are already using EnvoyFilter to add a Wasm based envoy filter, what would be the approach for us to switch to using the WasmPlugin resource without breaking functionality in a production environment? If we add a WasmPlugin resource in addition to the existing EnvoyFilter it will result in the filter being added twice which is not desirable.

I suppose the first step would be to verify that WasmPlugin fully covers your use case- we don't support a custom VM yet, for example. If it does, it will likely be removing your EnvoyFilter and adding the WasmPlugin. I don't think there will be guaranteed-no-downtime options as EnvoyFilter doesn't have that kind of support

2021-07-08 18:51 UTC, mandarjog commented
@dgn want to make sure that it is our collective intention to only use Wasm api and no longer need EnvoyFilter api to manipulate all wasm use cases.

wasm api will not cover aspects of EnvoyFilter api that are unrelated to wasm.

@mdhume we would love if you can come up with a proposal for migration from EF to the new API since you are running things in prod.

2021-07-13 02:58 UTC, brian-avery commented on extensions/v1alpha1/wasm.proto
> +// Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata"
https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata"

is actually a dead link and should point to 

https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata

2021-07-13 03:12 UTC, brian-avery commented
This is looking really good to me.

2021-07-13 17:14 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +//   selector:
since we use `workloadSelector` makes sense to use it here.

2021-07-13 20:54 UTC, mandarjog commented on extensions/v1alpha1/wasm.proto
> +  // be at the end of the filter chain, right before the Router.
is NONE considered an invalid selection? If the plugin is independent, then we don't expect users to use this at all.

2021-07-14 03:03 UTC, linsun commented on extensions/v1alpha1/wasm.proto
> +//     openid_realm: ingress
Thanks, sounds like the content within pluginConfig can be free form as long as it is a struct.

2021-07-14 13:10 UTC, linsun commented on extensions/v1alpha1/wasm.proto
> +  google.protobuf.Int64Value priority = 10;
What is the default priority value?  In your scenario above, what if I specify one Wasm resource without priority and one with a priority of 1000 (or 10) within the same phase, how do I know which is prioritized first?

2021-07-14 13:12 UTC, linsun commented
LGTM overall!  would like the following to be addressed:
- use workloadSelector to be consistent with other istio resources?
- clarify priority default value (when it is not specified) and how it compares with a priority value supplied by user?

2021-07-14 14:38 UTC, mandarjog commented
@linsun the new APIs (telemetry) actually uses `selector` so if we change this, then we need to change the other too. selector is consistent with other k8s api.

@dgn we have used  priority in ascending order in EnvoyFilter. I think we should do the same here. The default value is `0`.

2021-07-19 06:58 UTC, dgn commented
> @dgn we have used priority in ascending order in EnvoyFilter. I think we should do the same here. The default value is `0`.

So higher priority means later in the filter chain? That sounds confusing

2021-07-19 15:00 UTC, linsun commented
@mandarjog thanks, SG!

I agree with @dgn - I had thought priority higher means it is first/earlier in the filter chain.  Let's clarify default `0` in the comment.

2021-07-19 15:48 UTC, mandarjog commented
@dgn let’s clarify the comment and merge it!

2021-07-19 15:49 UTC, mandarjog commented
@linsun please lgtm it since you have reviewed it, John and Brian have already indicated so.

2021-07-19 15:50 UTC, mandarjog commented
adding label until we get 3 lgtms.

2021-07-19 15:51 UTC, howardjohn approved these changes

2021-07-19 16:24 UTC, linsun approved these changes
LGTM - pending the priority comment clarification of default.

2021-07-19 17:29 UTC, smawson commented on extensions/v1alpha1/wasm.proto
> +  optional string sha256 = 3;
This is definitely more confusing than is necessary.

For non-OCI usage, I'm assuming this is treated as a checksum, and used to verify that what you fetch is what you wanted to fetch. For the OCI usage it is used to fetch a specific version right? Not just as a checksum.

My assumptions would be for OCI:
- If @sha256 is set in the URL, we raise an error if sha256 is set in the field to something different
- If sha is set (either in URL or field), we also verify that the downloaded image has the correct sha.
- If sha field is set, but not in the URL, the image is still downloaded by tag and sha verified after download (not sure about this one).

It is confusing to have fields used for both fetch and verify, better to make it more explicit and have the sha field always used just for verification.

2021-07-19 17:29 UTC, smawson commented on extensions/v1alpha1/wasm.proto
> +  // Insert plugin before Istio authorization filters.
Is this also after Istio authentication filters? Maybe specify that if so to be explicit (same with STATS being after authorization filters).

2021-07-19 17:29 UTC, smawson commented on extensions/v1alpha1/wasm.proto
> +enum PullPolicy {
I think we need an UNSPECIFIED = 0 here.

Otherwise I think even explicitly setting it to IfNotPresent would get overridden if latest is in the tag, since we couldn't distinguish between default and explicit set to IfNotPresent.

2021-07-20 13:59 UTC, brian-avery approved these changes

2021-07-21 07:32 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  // Insert plugin before Istio authorization filters.
Yes, it's also after the istio auth filters. I made it more explicit, also in the comment for STATS below

2021-07-21 07:32 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +enum PullPolicy {
Good point. I'll add UNSPECIFIED so we can match k8s behaviour

2021-07-21 07:43 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  optional string sha256 = 3;
Thanks, that does make more sense. I clarified the comment

2021-07-21 07:43 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  google.protobuf.Int64Value priority = 10;
Defaults to `0`, I added a sentence to the comment. Thank you!

2021-07-21 09:47 UTC, dgn commented on extensions/v1alpha1/wasm.proto
> +  // namespace.  If omitted, the `WasmPlugin` will be applied to all
fixed

2021-07-22 16:23 UTC, smawson approved these changes

2021-07-22 16:24 UTC, smawson commented
I'm happy with this if you want to remove the hold Mandar.

2021-07-27 21:04 UTC, mandarjog commented
/cherry-pick release-1.10

2021-07-27 21:04 UTC, istio-testing commented
@mandarjog: once the present PR merges, I will cherry-pick it on top of release-1.10 in a new PR and assign it to you.

<details>

In response to [this](https://github.com/istio/api/pull/1940#issuecomment-887833515):

>/cherry-pick release-1.10


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-07-27 21:05 UTC, merged

2021-07-27 21:06 UTC, istio-testing commented
@mandarjog: new pull request created: #2067

<details>

In response to [this](https://github.com/istio/api/pull/1940#issuecomment-887833515):

>/cherry-pick release-1.10


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-07-27 21:23 UTC, mandarjog commented
/cherry-pick release-1.11

2021-07-27 21:23 UTC, istio-testing commented
@mandarjog: new pull request created: #2068

<details>

In response to [this](https://github.com/istio/api/pull/1940#issuecomment-887844434):

>/cherry-pick release-1.11


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>