Change dr MaxConnection int type
istio/api pull request #2160
Opened 2021-11-18 05:08 UTC by ningyougang

- [x] Change dr tcpSetting's MaxConnection int type from int32 to int64
  
  Refer to: https://istio.io/v1.5/docs/reference/config/networking/destination-rule/#ConnectionPoolSettings-TCPSettings
![image](https://user-images.githubusercontent.com/11749867/142347158-69e5edb6-ae9a-4416-b119-6a5e7ae1e15b.png)

  When configure a value to above red part value: `4294967295`, the value can't be parsed due to int32 can't meet it, so need to use `int64` to meet it.

2021-11-18 05:09 UTC, istio-testing commented
Hi @ningyougang. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fapi).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-11-18 05:13 UTC, ningyougang commented
My latest commit's author info as below
![image](https://user-images.githubusercontent.com/11749867/142355908-3f39ce25-aacb-4bff-985a-84718289be52.png)

I don't know why `CLA` check failed
![image](https://user-images.githubusercontent.com/11749867/142355952-c32315f8-aadf-4cfe-84fd-97c011d17695.png)

Someone knows about it? what should i do?

2021-11-18 07:02 UTC, hzxuzhonghu commented
We could not change the type of an API.
The confusing docs actually means, if no value set, the value that istio applied to envoy is max uint32(2^32-1)

2021-11-18 08:21 UTC, ningyougang commented
> We could not change the type of an API. The confusing docs actually means, if no value set, the value that istio applied to envoy is max uint32(2^32-1)

Thanks for your reply.

2021-11-18 16:25 UTC, howardjohn requested changes
Thanks for the PR!

I am not sure this is backwards compatible in protobuf?  Envoy's is a uint32 so I am not sure using int64 here is appropriate as well

2021-11-19 01:16 UTC, ningyougang commented
> Thanks for the PR!
> 
> I am not sure this is backwards compatible in protobuf? Envoy's is a uint32 so I am not sure using int64 here is appropriate as well

uint32 type is in [0 , 4294967295] , also meet the scope.
I already changed it to `uint32`

2021-11-19 17:17 UTC, howardjohn reviewed
Per proto, this does seem ok (https://developers.google.com/protocol-buffers/docs/proto3#updating). However, I am not sure I understand the motivation. Do you really need a number that int32 will not satisfy?

2021-11-22 00:57 UTC, ningyougang commented
> Per proto, this does seem ok (https://developers.google.com/protocol-buffers/docs/proto3#updating). However, I am not sure I understand the motivation. Do you really need a number that int32 will not satisfy?

The motivation is the int32 is not enough for below value
![image](https://user-images.githubusercontent.com/11749867/142786501-e00c50d1-f00c-4422-9ee7-7b8a19449691.png)
so it is better to change it from int32 to uint32.

btw, regarding `Per proto, this does seem ok`
You mean need some changes for some proto file? but i didn't find it.

2022-03-23 22:05 UTC, istio-testing commented
@ningyougang: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2024-05-15 23:35 UTC, closed without merging