Make termination drain duration default to 30s
istio/api pull request #2197
Opened 2021-12-25 03:30 UTC by hzxuzhonghu

The current default value is quite  different from k8s pod default value. (5s vs 30s) So when pod is terminated, envoy will be killed after 5s, but application container can be still there, maybe requiring communication with the outside.  It was  not a graceful way before.

2021-12-25 03:30 UTC, istio-testing commented
@hzxuzhonghu: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_api | 34d18869b047ef66f2138bc8c84de11266fefffe | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/2197/release-notes_api/1474583318560247808) | false | `/test release-notes_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-12-28 17:07 UTC, howardjohn requested changes
This will mean that all pods take 30s to shutdown. I do not think this is a good default, and even if it was the behavioral change is too great to make in a backwards compatible manner, IMO.

Users can easily set this themselves if they desire.

2021-12-28 17:08 UTC, howardjohn commented
Current logic is: `sleep(drain duration)`. There are a number of efforts to make it smarter, which I think are a better investment. When we do that, it should be based on the actual terminationGracePeriodSeconds, IMO, instead of a fixed 30s

2021-12-29 06:42 UTC, hzxuzhonghu commented
The value is to comply with pod default terminationGracePeriodSeconds, otherwise sidecar will exit before application container. Which may cause termination forcibly.

2021-12-29 16:17 UTC, howardjohn commented
Yes, the downside is that ALL pods will take the full 30s now with this
change. At the time the 5s default was introduced this was deemed
unacceptable, and I still feel it is today - especially since we have 2-3
prototypes of proper fixed for this in flight. Changing the default now
will cause a behavioral regression and lots of churn again when we undo it
in the near future.

Users are free to set this themselves

On Tue, Dec 28, 2021, 10:42 PM Zhonghu Xu ***@***.***> wrote:

> The value is to comply with pod default terminationGracePeriodSeconds,
> otherwise sidecar will exit before application container. Which may cause
> termination forcibly.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/api/pull/2197#issuecomment-1002420948>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEYGXMJXI6VYLVU5AYQTETUTKUV3ANCNFSM5KXMA4YA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2021-12-29 16:59 UTC, costinm commented
Envoy stopping before the app is stopped is clearly a bug and needs to be
fixed, we all agree on this.
Keeping envoy and the pod running AFTER the app stopped is also a bug.

The correct behavior is "same as if no sidecar was injected".

I don't think the current TerminationDrainDuration can solve this problem,
regardless of default value.

I only see few possible solutions:
1. (long term) work with k8s for improvements in the pod lifecycle.
2. injection can modify the startup command for the pod, running a 'init'
that handles startup/shutdown.
I have a prototype for the init, but injecting it is tricky and seems too
complicated ( works great for VMs
or containers or with the 'injection-less' mode we discussed - but too
tricky with normal injection)
3. detecting if no connections are in use - I think it's an improvement,
but still not the correct solution.
The app may wait for all connections to be closed (which envoy would also
detect and exit ) - but make
additional outbound requests after that.
4. (long term) when the sidecar is out of the pod, the problem goes away.

We may also be able to use the CNI - which technically has high permissions
and can see all containers
on the host. I think it would be worth moving more functionality into the
CNI and starting to require it,
for example a lot of the logic in pilot-agent could be moved there (cert
provisioning, XDS proxy and DNS are better
handled in the CNI ).  There are some problems - it may require vendor or
CRI-specific plugins,
but that's probably useful for (4) as well.

IMO the best short (and long) term solution is a variant of (2), providing
an 'istio-init' app and
library, that users can explicitly add to their docker images and use as
entry point, and also handle the
init zombie problem.  For proxyless gRPC this would also handle bootstrap
generation - since
proxyless doesn't need a sidecar or init container. It does have the
drawback that users will
have to make a small change to their code and the 'magic' will not work -
but I think serious
users who actually depend on such subtle startup/shutdown logic are better
served if they gain
visibility and control over startup instead of the current magic black box.

By 'library' I mean sample code and documentation for the interaction
between containers, i.e.
a stable and supported mechanism for the app to be notified and send events
about lifecycle,
which might at some point become (1), and also provide a more efficient way
to propagate
readiness/health status to Istiod ( instead of watching Endpoint and using
the periodic probes).


On Wed, Dec 29, 2021 at 8:18 AM John Howard ***@***.***>
wrote:

> Yes, the downside is that ALL pods will take the full 30s now with this
> change. At the time the 5s default was introduced this was deemed
> unacceptable, and I still feel it is today - especially since we have 2-3
> prototypes of proper fixed for this in flight. Changing the default now
> will cause a behavioral regression and lots of churn again when we undo it
> in the near future.
>
> Users are free to set this themselves
>
> On Tue, Dec 28, 2021, 10:42 PM Zhonghu Xu ***@***.***> wrote:
>
> > The value is to comply with pod default terminationGracePeriodSeconds,
> > otherwise sidecar will exit before application container. Which may cause
> > termination forcibly.
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <https://github.com/istio/api/pull/2197#issuecomment-1002420948>, or
> > unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AAEYGXMJXI6VYLVU5AYQTETUTKUV3ANCNFSM5KXMA4YA
> >
> > .
> > Triage notifications on the go with GitHub Mobile for iOS
> > <
> https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675
> >
> > or Android
> > <
> https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub
> >.
> >
> > You are receiving this because your review was requested.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/api/pull/2197#issuecomment-1002671141>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAUR2QQOKGTZQDPI4YWFTTUTMYDVANCNFSM5KXMA4YA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2021-12-30 01:24 UTC, hzxuzhonghu commented
>2. injection can modify the startup command for the pod, running a 'init'
that handles startup/shutdown.

This is also a solution proposed by @howardjohn and @rittneje, but personally, i think it is not a good way

2021-12-30 01:38 UTC, hzxuzhonghu commented
https://github.com/istio/istio/issues/36640

2021-12-30 03:39 UTC, costinm commented
On Wed, Dec 29, 2021 at 5:24 PM Zhonghu Xu ***@***.***> wrote:

>
>    1. injection can modify the startup command for the pod, running a
>    'init'
>    that handles startup/shutdown.
>
> This is also a solution proposed by @howardjohn
> <https://github.com/howardjohn> and @rittneje
> <https://github.com/rittneje>, but personally, i think it is not a good
> way
>
I tend to agree with you - it is certainly not the ideal solution for k8s,
but I think it's the most realistic
short-term option for users who refuse to make small changes to their
docker images.

The bottom line is that we must have some coordination for startup and
shutdown, and until K8S
provides it we must find some way to do it - either in the CNI (or some
other node-level solution) or in the
pod itself. We need to at least detect when the app container(s) are done
before stopping envoy.

I don't see another choice for detecting container status - has to be
either on the node or in the pod.
And if it is on the pod - either we inject it or the user adds it to their
container explicitly.

Unless someone finds a different way to get the app exit status - it's all
we have, since it's not safe
to stop envoy before.

> Message ID: ***@***.***>
>

2022-01-12 02:15 UTC, hzxuzhonghu commented
> This will mean that all pods take 30s to shutdown. I do not think this is a good default, and even if it was the behavioral change is too great to make in a backwards compatible manner, IMO.

@howardjohn  If user really wants to shutdown application container with sidecar container at the same time, we have /quitquitquit for them, what all we need to do is https://github.com/istio/istio/pull/36624.   And also how could this related to compatibility.

2022-01-12 03:26 UTC, rittneje commented
@hzxuzhonghu Fundamentally, `terminationDrainDuration` is not the right solution for any use case.

1. If your application meets the "normal" use case of just processing incoming requests that are routed through Envoy, and doesn't do anything unusual at shutdown, then the recently add `terminateOnZeroActiveConnections` is sufficient.
2. For all other use cases, there is no proper solution at present. You are forced to just guess how long your application takes to finish, which means you have to go with the worst case always, which is probably the same as your pod termination grace period anyway. In these cases, some explicit synchronization between the containers is really needed, to tell istio-proxy when to exit. Either you need to call /quitquitquit at the end (and fix it to make the sidecar exit immediately), or you need to leverage a UDS. The former can work well within a prestop hook, while the latter is much more robust and flexible, but does require amending application code. Neither of these can work "magically", with no explicit effort on the client's part.

With regards to compatibility, one thing I will say about this change is that since pod shutdown will be artificially delayed, you may end up putting more pressure on the cluster autoscaler during rolling updates, and it will lead to greater latency during deployments, which annoys developers. And in any case, 30 seconds is still a completely arbitrary number. Why not 60 seconds? Or 5 minutes?

2022-01-12 03:46 UTC, hzxuzhonghu commented
We are in a diverge way, this has been discussed in several issues. We should get to a concensue  ASAP. 

If user really cares about one second speed, they have to notify sidecar to exit immediately. Otherwise it is no easy for us to do

2022-03-16 22:03 UTC, istio-testing commented
@hzxuzhonghu: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-07-21 03:28 UTC, closed without merging