Enable configuring Envoy private key provider through ProxyConfig
istio/api pull request #2261
Opened 2022-03-03 12:00 UTC by rveerama1

**Introduction**

Since 1.20 Envoy has supported configuring private key providers over xDS. Also, the first in-tree private key provider (CryptoMB) was released in Envoy 1.20 contrib build (Ref PR: https://github.com/envoyproxy/envoy/pull/17826 ).

The idea in CryptoMB private key provider is that incoming TLS handshakes’ RSA operations are accelerated using AVX-512 multi-buffer instructions. For more details, see this Intel whitepaper which contains some more information about the AVX-512 instructions and potential performance increase: https://www.intel.com/content/www/us/en/architecture-and-technology/crypto-acceleration-in-xeon-scalable-processors-wp.html. 
An introductory presentation is available here :  https://www.intel.com/content/www/us/en/developer/videos/accelerate-envoy-with-advanced-vector-extensions.html

The private key providers can be configured using SDS protocol: the private_key field in Envoy Secret is replaced with the private key provider configuration. For example,

```
tls_certificates:
   certificate_chain: { "filename": "/path/cert.pem" }
   private_key: { "filename": "/path/key.pem" }

could be replaced with:

 tls_certificates:
   certificate_chain: { "filename": "/path/cert.pem" }
   private_key_provider:
     provider_name: cryptomb
     typed_config:
       "@type": type.googleapis.com/envoy.extensions.private_key_providers.cryptomb.v3alpha.CryptoMbPrivateKeyMethodConfig
       private_key: { "filename": "/path/key.pem" }
       poll_delay: 0.1s
```

The problem is that private key providers are typically host-dependent: for example, CryptoMb provider requires a host with support for AVX-512 instruction set. Therefore, we propose an extension mechanism, which allows for dynamic configuration of private key providers.

To set the mesh wide defaults, configure the `defaultConfig` section of `meshConfig`. For example:
```
    meshConfig:
      defaultConfig:
        privateKeyProvider:
          name: "cryptomb"
          config:
            "@type": type.googleapis.com/envoy.extensions.private_key_providers.cryptomb.v3alpha.CryptoMbPrivateKeyMethodConfig
            pollDelay: 0.01s
```
This can also be configured on a per-workload basis by configuring the `proxy.istio.io/config` annotation on the pod.
For example:
```
    annotations:
      proxy.istio.io/config: |
        privateKeyProvider:
          name: "cryptomb"
          config:
            "@type": type.googleapis.com/envoy.extensions.private_key_providers.cryptomb.v3alpha.CryptoMbPrivateKeyMethodConfig
            pollDelay: 0.01s
```

2022-03-03 12:00 UTC, istio-testing commented
Hi @rveerama1. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fapi).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-03-04 00:55 UTC, irisdingbj commented
/ok-to-test

2022-03-04 00:56 UTC, istio-testing commented
@rveerama1: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_api | 5ec83188e936a4cd84469c189b289afab6451a63 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/2261/release-notes_api/1499549201254584320) | false | `/test release-notes_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-04 01:00 UTC, irisdingbj commented on mesh/v1alpha1/proxy.proto
> +// PrivateKeyProvider defines configuration for gateways and sidecars. This can be confgured
// PrivateKeyProvider defines private key configuration for gateways and sidecars. This can be configured

2022-03-04 01:12 UTC, irisdingbj commented
@howardjohn  This is the API change part PR and the relevant istio change PR is https://github.com/istio/istio/pull/37681
Please help to give a review for this, Thanks!

2022-03-04 09:20 UTC, rveerama1 commented
Istio proxy relevant change is here: https://github.com/istio/proxy/pull/3752

2022-03-04 10:29 UTC, istio-testing commented
@rveerama1: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_api | a4086c383f75ed273356f4b601c602ad2af7cc19 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/2261/release-notes_api/1499693417108606976) | false | `/test release-notes_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-04 10:32 UTC, istio-testing commented
@rveerama1: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_api | 187bcaf0add4ac328c84e6be3cbf5e20c34a1274 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/2261/release-notes_api/1499694237233451008) | false | `/test release-notes_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-04 10:32 UTC, istio-testing commented
@rveerama1: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_api | 187bcaf0add4ac328c84e6be3cbf5e20c34a1274 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/2261/release-notes_api/1499694237233451008) | false | `/test release-notes_api`
gencheck_api | 187bcaf0add4ac328c84e6be3cbf5e20c34a1274 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/2261/gencheck_api/1499694237183119360) | true | `/test gencheck_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-04 16:23 UTC, howardjohn requested changes
I am not a huge fan of exposing users to the raw underlying Envoy types -- especially since they are NOT passthrough and istio needs to have code to handle each type.

2022-03-04 16:23 UTC, howardjohn commented on mesh/v1alpha1/proxy.proto
> +  google.protobuf.Struct config = 2;
Why we need a whole generic config struct? Should we just have an Enum with options like `DEFAULT, CRYPTOMB, ...`?

2022-03-07 05:02 UTC, irisdingbj commented on mesh/v1alpha1/proxy.proto
> +  google.protobuf.Struct config = 2;
generic type is  used here to make sure we do not  expose users to the raw underlying Envoy type.  We can not limit supported private key provider via Enum --suppose in the future there might be other new private key provider be introduced in envoy.  

@rveerama1 please add any info I am missing here.

2022-03-07 08:49 UTC, rveerama1 commented on mesh/v1alpha1/proxy.proto
> +  google.protobuf.Struct config = 2;
1). If we are expecting some values from the user (e.g poll_delay value from user in CryptoMB private key provider configuration, private_key will be filled by istiod/istio-agent). It will allow us to validate and map from struct to respective type in source code.

2.) [EnvoyFilter](https://github.com/istio/api/blob/master/networking/v1alpha3/envoy_filter.proto#L771) uses generic struct type to pass different types of dynamic data. Thought this kind of mechanism is recommended.

3) It will allow others to introduce new private key providers for Envoy without affecting istio.io/api. Just add relevant code in istio.io/istio sources.

2022-03-07 18:31 UTC, lambdai commented
The happy path is exciting. 
How wide is the AVX-512? What if the the host doesn't offer AVX-512, e.g on a stale VM?

2022-03-08 10:36 UTC, rveerama1 commented on mesh/v1alpha1/proxy.proto
> +  google.protobuf.Struct config = 2;
How about something like this ?
`
// CryptoMBPrivateKeyProvider configuration
message CryptoMBPrivateKeyProvider {
  google.protobuf.Duration poll_delay = 1;
}

// PrivateKeyProvider defines private key configuration for gateways and sidecars. This can be configured
// mesh wide or individual per-workload basis.
message PrivateKeyProvider {
  // REQUIRED. PrivateKeyProvider name ("cryptomb").
  string name = 1;

  // REQUIRED. Specifies detailed configuration for the Private key provider.
  oneof provider {
    CryptoMBPrivateKeyProvider cryptomb = 2;
  }
}
`

2022-03-08 10:42 UTC, rveerama1 commented
> What if the the host doesn't offer AVX-512, e.g on a stale VM?

This can be configured mesh wide and per-workload. In this case, user/admin has to configure per-workload basis and deploy it based on some label to that particular node which supports AVX-512.

2022-03-08 15:40 UTC, ipuustin commented
> The happy path is exciting. How wide is the AVX-512? What if the the host doesn't offer AVX-512, e.g on a stale VM?

The operations are https://en.wikipedia.org/wiki/AVX-512#IFMA calls, so the registers are 512 bits wide. Internally https://github.com/intel/ipp-crypto/tree/develop/sources/ippcp/crypto_mb library is called to perform the cryptographic operations.

2022-03-11 01:51 UTC, irisdingbj commented
/test-all

2022-03-11 01:52 UTC, irisdingbj commented
@howardjohn Can you please review the latest change? Thanks!

2022-03-11 02:09 UTC, zirain commented on mesh/v1alpha1/proxy.proto
> +message PrivateKeyProvider {
I'm not sure can we make this as an kind of ExtensionProvider? 
I think there's a long term goal about move all things like this out of `MeshConfig`, https://docs.google.com/document/d/1WDKX-Rk_FYD2L8Ner_w7kic93ZUMPvyG84ymcZZ9BGY/edit#

2022-03-14 00:40 UTC, irisdingbj commented on mesh/v1alpha1/proxy.proto
> +message PrivateKeyProvider {
Thanks for the review!  we have explored the possibility to make it part of extensionProvider.    However it does not work due to two reasons:
1.  We do not have a specific CRD as telemetry API or authorization CRD to reference extensionProvider from meshconfig for a specific workload
2. We need support per pod/workload defination besides one global mesh one.

2022-03-15 02:18 UTC, howardjohn reviewed
This LGTM other than the small comment.

I would like to see approval from some set of @shankgan @myidpt @jacob-delgado @costinm before merging though to make sure there is broader agreement (not all of them needed)

2022-03-15 02:18 UTC, howardjohn commented on mesh/v1alpha1/proxy.proto
> +  // REQUIRED. PrivateKeyProvider name (e.g: "cryptomb").
name is no longer required, right? It is implied by the oneof type

2022-03-15 03:18 UTC, jacob-delgado commented
~~We are trying to get rid of `meshConfig` and `meshConfig.defaultConfig`. I'm thinking this should this be moved to `networking/v1beta1/proxy_config.proto` and not be used in`meshConfig.defaultConfig` or annotations. I'd like to see what the status is of `ProxyConfig` though before we commit a change.~~

Since the user cannot put node labels/tolerations and use affinity/anti-affinity on namespaces it needs to go on something that can be placed on a deployment, statefulset or daemonset. For this case `ProxyConfig` won't suffice and this is the right place to put it.

2022-03-15 03:34 UTC, jacob-delgado commented on mesh/v1alpha1/proxy.proto
> +  // REQUIRED. PrivateKeyProvider name (e.g: "cryptomb").
I looked at the WIP PR, if this is kept then this should be an enum and not a string. Ideally we could key off of the provider type.

2022-03-15 03:38 UTC, jacob-delgado commented
LGTM, but it'd be nice to get rid of the `name` field so that we don't have magic strings in the istio codebase.

2022-03-15 09:37 UTC, rveerama1 commented
Thanks for the reviews @howardjohn @jacob-delgado, I have removed the 'name' part and updated the PR. PTAL.

2022-03-15 17:54 UTC, ericvn approved these changes

2022-03-15 17:55 UTC, merged