Document new sidecar annotation to exclude interfaces
istio/api pull request #2374
Opened 2022-06-03 12:32 UTC by obaranov1

Regarding the added feature [https://github.com/istio/istio/pull/34832](url)

2022-06-03 12:32 UTC, istio-testing commented
Hi @obaranov1. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fapi).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-06-03 14:46 UTC, ramaraochavali commented
incorrect PR link in the description

2022-06-03 14:56 UTC, howardjohn requested changes
I don't see such an annotation anywhere in the codebase?

2022-06-03 15:49 UTC, obaranov1 commented
the link has been updated. the codebase is there

2022-06-03 16:09 UTC, howardjohn commented
But no annotation was ever defined? If you grep the code there is no mention

2022-06-03 20:41 UTC, rveerama1 commented
We have a use case around this feature. When we were exploring about this feature in the documentation https://istio.io/latest/docs/reference/config/annotations/ we didn't find any thing. Later we noticed about this https://github.com/istio/istio/pull/34832. We haven't tried it on any environment yet. Thought only documentation might be missing. If there are no objections can we proceed with adding pod annotation in the code base?

2022-06-06 13:15 UTC, linsun commented
Is annotation better than label here? We are trying to shift away from annotation for sidecar injection.

Can you please document your scenario in a doc as well?

2022-06-08 15:39 UTC, howardjohn commented
Annotation is fine here, label is only needed for the webhook stuff since
its used in label selectors

On Wed, Jun 8, 2022 at 5:34 AM Ravi kumar Veeramally <
***@***.***> wrote:

> Is annotation better than label here? We are trying to shift away from
> annotation for sidecar injection.
>
> I am not an expert here about annotation or label. But if there is a work
> going on already about shifting sidecar annotations to labels, please share
> any WIP PRs or submitted ones. We will follow that. Otherwise we continue
> with annotation as it is like other sidecar annotations and the move it
> label if necessary.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/api/pull/2374#issuecomment-1149856457>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEYGXL5DX4QNHOZWNBGUDDVOCHNVANCNFSM5XYRW6YA>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-06-14 09:56 UTC, rveerama1 commented
@howardjohn PTAL about documentation.

2022-06-14 09:57 UTC, istio-testing commented
@obaranov1: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_api | fa218168919269bb7578d52d3f112bc11072c609 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/2374/release-notes_api/1536648647238750208) | false | `/test release-notes_api`
gencheck_api | fa218168919269bb7578d52d3f112bc11072c609 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/2374/gencheck_api/1536648647205195776) | true | `/test gencheck_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-06-14 10:35 UTC, istio-testing commented
@obaranov1: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
gencheck_api | 3054eb5a5f036b4fe6d7177dcb85f7f0080884a5 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/2374/gencheck_api/1536658243009384448) | true | `/test gencheck_api`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-06-14 15:48 UTC, howardjohn approved these changes

2022-06-14 16:10 UTC, ericvn commented on releasenotes/notes/2374.yaml
> +  - https://github.com/istio/api/pull/2374
Nit: Maybe point to feature: https://github.com/istio/istio/pull/34832

2022-06-14 16:12 UTC, ericvn approved these changes
Approved. Marked DNM for the nit. Feel free to fix or not. Then remove the DNM to let this in. Thanks.

2022-06-14 16:39 UTC, merged