security policy graduation to v1
istio/api pull request #2553
Opened 2022-11-07 19:42 UTC by aryan16

This PR involves API changes required to graduate security policies from V1beta1 to V1.

2022-11-07 19:42 UTC, istio-testing commented
@aryan16: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_api | 544c11d9261656a0e608caf7d7d08187636192ec | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/2553/release-notes_api/1589704799845093376) | false | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-11-07 19:43 UTC, istio-testing commented
@aryan16: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_api | 544c11d9261656a0e608caf7d7d08187636192ec | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/2553/release-notes_api/1589704799845093376) | false | `/test release-notes`
gencheck_api | 544c11d9261656a0e608caf7d7d08187636192ec | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/2553/gencheck_api/1589704799807344640) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-11-07 19:47 UTC, istio-testing commented
@aryan16: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
gencheck_api | d6e7a49cd7006c6f9e0c9e36d584b423d1a0463f | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/2553/gencheck_api/1589705974015332352) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-11-07 19:49 UTC, howardjohn commented on security/v1/jwt.proto
> +// Copyright 2019 Istio Authors
We should be adding the `istio.io/sync-from` indicators like we have for networking protos so we don't need to manually keep them in sync.

2022-11-07 19:50 UTC, howardjohn reviewed
Can we split out new docs from the rest of the changes? They are ~unrelated and make it harder to review

2022-11-07 22:27 UTC, istio-testing commented
@aryan16: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
gencheck_api | 293c4355fdf028b64096134d1101cbb7d630126c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/2553/gencheck_api/1589746098707107840) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-11-07 22:29 UTC, aryan16 commented on security/v1/jwt.proto
> +// Copyright 2019 Istio Authors
done, thanks

2022-11-07 22:33 UTC, istio-testing commented
@aryan16: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
gencheck_api | 46dc5eca4ceec0570f575e676b48854b7d21fd7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/2553/gencheck_api/1589747575961948160) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-11-18 22:01 UTC, howardjohn approved these changes

2022-11-21 20:42 UTC, linsun requested changes
Only concern I have is the JWT.proto - some of the changes are too recent, for example ClaimToHeaders were changed few days ago and this feature is still relatively new IMHO, I don't feel comfortable promoting them to stable.  Others are fine.

Thoughts?

2022-11-22 18:58 UTC, aryan16 commented
cc : @liminw

2022-11-22 20:03 UTC, linsun approved these changes
Thanks @aryan16 for clarifying the claimtoheader. Given we don't have a better way to track each field other than the comment, LGTM

2022-11-22 20:03 UTC, merged