make inbound port configurable
istio/api pull request #2702
Opened 2023-03-01 09:03 UTC by zirain

xref:  https://github.com/istio/istio/issues/43655

cc @howardjohn @ramaraochavali

2023-03-01 09:04 UTC, istio-testing commented
@zirain: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_api | 6464915df3778c30fd7b7fa700fd68fe20706ae3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/2702/release-notes_api/1630856301711986688) | false | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-03-01 09:06 UTC, zirain commented
/test release-notes

2023-03-01 15:25 UTC, costinm commented on mesh/v1alpha1/config.proto
> +  // $hide_from_docs
Ok with the other 2, they apply to sidecar and config generation which is implemented in istiod.

For hbone:
- I don't think we are ready for the complexity of using a custom port. What happens in multi-cluster if different clusters have different ports ? Is ztunnel and all 'native hbone' aware of mesh config setting ? Would other non-Istio implementations have to somehow get MeshConfig to know the port ?
- if there are strong use cases - it should be an option on the ztunnel chart itself. It is bad practice to share mesh config across multiple independent deployments , mesh config is 'owned' by Istiod chart and used by Istiod.

2023-03-01 15:28 UTC, costinm commented on mesh/v1alpha1/config.proto
> +  // $hide_from_docs
Even for the other 2 ports I have doubts - I don't think I've seen a lot of tests using custom envoy interception port, nor a good use case or doc. I remember in the past we discussed about 'promote to beta or deprecate' for configs that linger without tests/docs - this is one example. 

Maybe a doc explaining the use cases and plans for testing/promotion/etc would be best ?

2023-03-01 16:43 UTC, howardjohn requested changes

2023-03-01 16:43 UTC, howardjohn commented on mesh/v1alpha1/config.proto
> +  // $hide_from_docs
I am very against this

2023-03-01 16:44 UTC, howardjohn commented
15001 or 15006 are internal implementation details. 15008 is a public API

2023-03-01 18:32 UTC, kyessenov commented on mesh/v1alpha1/config.proto
> +  // $hide_from_docs
Can someone start IANA process to claim the port? It looks like Azure claimed the same range of ports so every installation there is affected.

2023-03-02 01:30 UTC, zirain commented on mesh/v1alpha1/config.proto
> +  // $hide_from_docs
@costinm linked with user's  comment.

2023-03-02 01:36 UTC, zirain commented
> 15001 or 15006 are internal implementation details. 15008 is a public API

revert 15008 part as suggested.

2023-03-09 20:38 UTC, howardjohn approved these changes
I don't particularly love this type of customization but will admit it brings consistency with 15001 being customizable, so I am ok with this. We should not add HBONE to this at any point, though

2023-03-10 01:17 UTC, hzxuzhonghu reviewed
should better update L1151   // Next available field number: 65

2023-03-10 01:53 UTC, zirain commented
> should better update L1151 // Next available field number: 65

done.

2023-03-10 01:56 UTC, hzxuzhonghu approved these changes

2023-03-10 01:56 UTC, merged