Added transport socket match patch
istio/api pull request #2988
Opened 2023-11-13 08:56 UTC by hzxuzhonghu

For https://github.com/istio/istio/issues/44342 https://github.com/istio/istio/issues/44342 https://discuss.istio.io/t/config-istio-proxy-protocol/14911 https://discuss.istio.io/t/enable-proxy-protocol-from-istio-to-upstreams/10321

2023-11-13 08:57 UTC, istio-testing commented
@hzxuzhonghu: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_api | 576d95fc56f3c7246d38195fa8695eb11c746b5a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/2988/release-notes_api/1723988251636666368) | false | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-11-14 01:12 UTC, hzxuzhonghu commented
It is for adding or replacing a transportsocket match,  from the original issues, adding upstream proxy protocol support is the most required

2023-11-14 01:13 UTC, hzxuzhonghu commented
The semantics is very similar to listener filters patching

2023-11-14 01:26 UTC, howardjohn commented
I mean can we add in the comments how it works? if I cannot understand it
probably users cannot?



On Mon, Nov 13, 2023, 5:14 PM Zhonghu Xu ***@***.***> wrote:

> The semantics is very similar to listener filters patching
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/api/pull/2988#issuecomment-1809385228>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEYGXMTMY7E6YL7K25C2PTYELAV3AVCNFSM6AAAAAA7IZP6OCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMBZGM4DKMRSHA>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-11-14 01:26 UTC, howardjohn commented
and will be good to know why the existing support we have doesn't work

On Mon, Nov 13, 2023, 5:25 PM John Howard ***@***.***> wrote:

> I mean can we add in the comments how it works? if I cannot understand it
> probably users cannot?
>
>
>
> On Mon, Nov 13, 2023, 5:14 PM Zhonghu Xu ***@***.***> wrote:
>
>> The semantics is very similar to listener filters patching
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/istio/api/pull/2988#issuecomment-1809385228>, or
>> unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AAEYGXMTMY7E6YL7K25C2PTYELAV3AVCNFSM6AAAAAA7IZP6OCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMBZGM4DKMRSHA>
>> .
>> You are receiving this because your review was requested.Message ID:
>> ***@***.***>
>>
>

2023-11-14 01:58 UTC, hzxuzhonghu commented
Understand, will add that

2023-11-15 15:56 UTC, linsun reviewed
left 1 comment, LG

2023-11-15 15:56 UTC, linsun commented on networking/v1alpha3/envoy_filter.proto
> +    // Applies the patch to the cluster's transport socket match.
I saw the example is for `context: SIDECAR_OUTBOUND` - can you clarify if it can be used for other contexts as well in the comments?

2023-11-16 02:09 UTC, hzxuzhonghu commented on networking/v1alpha3/envoy_filter.proto
> +    // Applies the patch to the cluster's transport socket match.
In theory it can be added to any ctx,  I do believe this will be mostly used for gateway and sidecar outbound

2023-11-16 03:20 UTC, linsun commented on networking/v1alpha3/envoy_filter.proto
> +// The following example adds an `envoy.transport_sockets.upstream_proxy_protocol` transport socket match.
Could you explain what this achieve for users?

2023-11-16 03:22 UTC, linsun commented on networking/v1alpha3/envoy_filter.proto
> +    // Applies the patch to the cluster's transport socket match.
Any usage difference from gateway vs sidecar outbound that we should highlight?

2023-11-16 03:33 UTC, hzxuzhonghu commented on networking/v1alpha3/envoy_filter.proto
> +    // Applies the patch to the cluster's transport socket match.
no, juts the CTX

2023-11-16 03:36 UTC, hzxuzhonghu commented on networking/v1alpha3/envoy_filter.proto
> +// The following example adds an `envoy.transport_sockets.upstream_proxy_protocol` transport socket match.
Yes.  This example is to add an upstream proxy protocol support, which can be used to keep the original ip of this pod.

On the server side, it can parse the proxy protocol to get the original src ip address.

2023-11-16 03:42 UTC, hzxuzhonghu commented on networking/v1alpha3/envoy_filter.proto
> +// The following example adds an `envoy.transport_sockets.upstream_proxy_protocol` transport socket match.
BTW, proxy protocol is not the only transportsocket that can be added. https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/transport_socket/transport_socket listed all that supported by envoy

2023-11-16 03:54 UTC, istio-testing commented
@hzxuzhonghu: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_api | 18171fd7241bdbb0be22d546e7bf9df31928fc78 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/2988/release-notes_api/1724999299097432064) | false | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-11-16 08:37 UTC, hzxuzhonghu commented
/test release-notes

2023-11-16 16:28 UTC, howardjohn requested changes
Can you please explain why https://github.com/istio/istio/blob/bd9e52d05817b03b9811a761a818b2e76d356018/pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go#L85 doesn't work?

Is it because there is no way to remove an element, and they are matched in order?

cc @kyessenov

2023-11-16 16:28 UTC, howardjohn commented on networking/v1alpha3/envoy_filter.proto
> +//        match: {}
Not sure how this would work, Istio will already have a `match: {}`?

2023-11-17 01:43 UTC, hzxuzhonghu commented on networking/v1alpha3/envoy_filter.proto
> +//        match: {}
For eds cluster, we generated two transport socket by default. A match {} will hijack all the ts after it.
```
        "transportSocketMatches": [
            {
                "name": "tlsMode-istio",
                "match": {
                    "tlsMode": "istio"
                },

            {
                "name": "tlsMode-disabled",
                "match": {
                    "tlsMode": "istio"
                },
```

2023-11-17 01:49 UTC, hzxuzhonghu commented
>Is it because there is no way to remove an element, and they are matched in order?

There is no way to insert a upstream proxy tranport socket now. The existing hack ts merge is to handle tls/raw buffer

2023-11-17 01:51 UTC, hzxuzhonghu commented on networking/v1alpha3/envoy_filter.proto
> +//        match: {}
Actually the most graceful way would be  add two `upstream_proxy_protocol`, once with match `"tlsMode": "istio"`, and the other with `"tlsMode": "disabled"`,

2023-11-17 01:55 UTC, kyessenov commented
We have PROXY on downstream now in ProxyConfig? What does this feature look like as a first class API? Is this intended only on egress gateways?

2023-11-17 03:46 UTC, hzxuzhonghu commented
> We have PROXY on downstream now in ProxyConfig?

NO, the downstream proxy can be set on listener filter with envoyfilter. There are many usage in ingress gateway.

>What does this feature look like as a first class API? Is this intended only on egress gateways?

This is for upstream transport socket setting. Which means the outbound traffic will be sent with proxy protocol, so the upstream server could acquire the real IP address of the client.

TBH, it is not only for egress gateway, as the issues and also from https://discuss.istio.io/t/enable-proxy-protocol-from-istio-to-upstreams/10321, i can see user want to apply it to ingress gateway also.

2023-11-17 03:53 UTC, kyessenov commented
@hzxuzhonghu upstream proxy protocol is very different from downstream proxy protocol. Why do we need in-mesh PROXY? Isn't it the same as HBONE? You can fully implement HBONE with just PROXY.

2023-11-17 04:09 UTC, hzxuzhonghu commented
TBH, I can not distinguish in mesh or out mesh sometimes, For a sidecar, it may need to access an external service. I understand this case is still in mesh. So inoder to apply a proxy protocol TS,  need to specify `SIDECAR_OUTBOUND`

2023-11-17 04:38 UTC, hzxuzhonghu commented
i agree with you on simplicity.. Here i want to provide the general supporting

2023-11-18 00:34 UTC, hzxuzhonghu commented
@howardjohn any other question

2023-11-18 04:29 UTC, howardjohn commented
> Can you please explain why https://github.com/istio/istio/blob/bd9e52d05817b03b9811a761a818b2e76d356018/pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go#L85 doesn't work?
> 
> Is it because there is no way to remove an element, and they are matched in order?


still waiting to see the answer to this, might have gotten lost?

2023-11-20 02:12 UTC, hzxuzhonghu commented
>Is it because there is no way to remove an element, and they are matched in order?


This can be an important reason, we can not remove an element currently.
And we cannot insert a element in front/after of a specific one.
We can't also replace a specific element.

2023-11-21 01:59 UTC, hzxuzhonghu commented
>What if we just make it so you can set transportSocket?   Or we always merge TSMatch first instead of last?

If the transport socket match set, it can take precedence over transportSocket. 

What do you mean by ` merge TSMatch first instead of last`? Is this a hack merge, which is different from the protobuf merge, so how we can tell user this semantics.

**mergeTransportSocketCluster** is already a hack way, i am not sure what it does until after reading the whole code, and wonder how can normal users like me to know.

2023-11-21 02:01 UTC, hzxuzhonghu commented
> There are literally 100s of fields we can special case, the API will grow crazy (already is...).

This is an enum, not adding a new field under the EnvoyFilter. If it can resolve the upstream proxy protocol insert issues, i would rather not adding anything

2023-11-21 02:04 UTC, howardjohn commented
> > What if we just make it so you can set transportSocket?   Or we always merge TSMatch first instead of last?
> 
> If the transport socket match set, it can take precedence over transportSocket.
> 
> What do you mean by ` merge TSMatch first instead of last`? Is this a hack merge, which is different from the protobuf merge, so how we can tell user this semantics.
> 
> **mergeTransportSocketCluster** is already a hack way, i am not sure what it does until after reading the whole code, and wonder how can normal users like me to know.

Users already need to understand Istio and envoy internals for using envoy filter so I don't mind it being challenging to use really. plus we can always improve documentation 

> > There are literally 100s of fields we can special case, the API will grow crazy (already is...).
> 
> This is an enum, not adding a new field under the EnvoyFilter. If it can resolve the upstream proxy protocol insert issues, i would rather not adding anything

It has about the same cost, we still need a full bespoke implementation for this in istiod, etc. There are literally 100s of nested types within envoy, it's not sustainable to slowly add all of them one by one

2023-11-21 02:27 UTC, hzxuzhonghu commented
>Users already need to understand Istio and envoy internals for using envoy filter so I don't mind it being challenging to use really. plus we can always improve documentation

If you mean `mergeTransportSocketCluster ` looks good to you, I do not care much.  Come back to our target to make upstream proxy protocol work.

2023-11-27 07:28 UTC, hzxuzhonghu commented
@howardjohn Suggested to add native proxy protocol support in DestinationRule, rather than using envoyfilter. So would add new API design, and I've seen gateway API has protocol support too. Will align with it.

2023-11-27 15:28 UTC, linsun commented
> @howardjohn Suggested to add native proxy protocol support in DestinationRule, rather than using envoyfilter. So would add new API design, and I've seen gateway API has protocol support too. Will align with it.

I like it!  the upgrade to h2(https://istio.io/latest/docs/reference/config/networking/destination-rule/#ConnectionPoolSettings-HTTPSettings-H2UpgradePolicy) is also defined in DR so this is quite intuitive for users to use.

2023-11-28 02:44 UTC, closed without merging

2023-11-28 02:44 UTC, hzxuzhonghu commented
Thank you, will start to design it within DR in another pr.