adding meshConfig for waypoint class names
istio/api pull request #3006
Opened 2023-11-27 23:05 UTC by ilrudie

adds a field to configure gateway class names which are being used as ambient waypoint proxies

resolve #3005

2023-11-27 23:06 UTC, istio-testing commented
@ilrudie: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_api | 7ee6b1d5bb5997ce70f054d5177ac9d26db53e1f | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/3006/release-notes_api/1729275362535280640) | false | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-11-27 23:41 UTC, howardjohn requested changes
Hold for discussion in https://github.com/istio/api/issues/3005#issuecomment-1828750090

2023-12-11 18:08 UTC, ilrudie commented
Should we just go ahead and close this? It likely isn't necessary on the current track as John has mentioned. 

@keithmattix, you had commented on this in Louis's doc a little. WDYT now that we've all had some time for thinking about John's proposal more?

2023-12-14 21:14 UTC, closed without merging

2023-12-14 21:14 UTC, ilrudie commented
Going to close this just to clean up since it doesn't look like there's much support or need for it at the moment. We can circle back if need arises.