meshconfig: add compliance policy
istio/api pull request #3082
Opened 2024-02-09 22:17 UTC by kyessenov

Ref: https://github.com/istio/istio/issues/49081

Change-Id: I43bb205b5b62e557f61852e08b5084b63453ba6e

2024-02-09 22:17 UTC, istio-testing commented
@kyessenov: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_api | 5f75cfe7d3527e662e51b79e34d88a3be3f7a8a2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/3082/release-notes_api/1756079802613239808) | false | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-02-09 22:42 UTC, howardjohn commented on mesh/v1alpha1/config.proto
> +  string compliance_policy = 67;
What happens if you use compliancePolicy=fips with non-fips builds?

2024-02-09 22:42 UTC, howardjohn commented on mesh/v1alpha1/config.proto
> +  // If set, applies policy-specific restrictions over all existing TLS settings, including in-mesh mTLS and external TLS.
What is the scope? Inbound, outbound, gateway? control plane communication?

2024-02-09 22:43 UTC, kyessenov commented on mesh/v1alpha1/config.proto
> +  string compliance_policy = 67;
No-op. FIPS requires that both validated modules are used, and that they are configured with compliance policy. If you do only one of those things, it's not compliant.

2024-02-09 22:43 UTC, kyessenov commented on mesh/v1alpha1/config.proto
> +  // If set, applies policy-specific restrictions over all existing TLS settings, including in-mesh mTLS and external TLS.
All TLS communication.

2024-02-09 22:44 UTC, kyessenov commented
/retest

2024-02-09 22:45 UTC, howardjohn commented on mesh/v1alpha1/config.proto
> +  // If set, applies policy-specific restrictions over all existing TLS settings, including in-mesh mTLS and external TLS.
Just TLS or all crypto as well (JWT, etc)? We should clarify the scope in the docs. Especially if this about compliance, being verbose in the documentation is probably handy

2024-02-09 22:51 UTC, keithmattix requested changes
I think having an easy field to enable configuration that's consistent with FIPS guidelines is a great idea, but I'm concerned that the prescribed values may not be sufficient

2024-02-09 22:51 UTC, keithmattix commented on mesh/v1alpha1/config.proto
> +  // Valid values: "", "fips".
What version of FIPS? 140-2? 140-3 (which supersedes, 140-2)?

2024-02-09 22:54 UTC, kyessenov commented on mesh/v1alpha1/config.proto
> +  // If set, applies policy-specific restrictions over all existing TLS settings, including in-mesh mTLS and external TLS.
It says "all TLS settings" in the doc. JWT is not in scope since JWT is not needed by default, and you can simply not use JWT features to remain compliant.

2024-02-09 22:56 UTC, kyessenov commented on mesh/v1alpha1/config.proto
> +  // Valid values: "", "fips".
Istio almost entirely relies on this certificate: https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4407, which is 140-2. I left it a string precisely because the standards change, but I can make it explicitly call out that certificate.

2024-02-09 22:59 UTC, howardjohn commented on mesh/v1alpha1/config.proto
> +  // Valid values: "", "fips".
_Istio_ doesn't rely on any certificate as it doesn't offer FIPS compliance or even builds with the FIPS crypto modules. Vendors sell Istio that has these properties.

Which to me makes this a bit awkward to have as an Istio configuration rather than a vendor configuration

2024-02-09 23:01 UTC, keithmattix commented on mesh/v1alpha1/config.proto
> +  // Valid values: "", "fips".
Yeah I would make the string value more specific than just FIPS; maybe "fips-140-2" and then a comment above associating the string value to the certification 👍🏾

2024-02-09 23:04 UTC, kyessenov commented on mesh/v1alpha1/config.proto
> +  // Valid values: "", "fips".
Vendors rely on the ability of Istio to configure FIPS compliance policies since they can substitute the module and satisfy 1 of 2 conditions. Without an API, a small fork is needed which makes it hard to audit compliance.

2024-02-09 23:06 UTC, kyessenov commented on mesh/v1alpha1/config.proto
> +  // Valid values: "", "fips".
Applied your suggestion, @keithmattix .

2024-02-09 23:15 UTC, keithmattix commented on mesh/v1alpha1/config.proto
> +  string compliance_policy = 67;
Is it a no-op or ignored? That is, will the cryptographic algos be filtered even though the build is non-FIPS?

2024-02-09 23:15 UTC, keithmattix commented on mesh/v1alpha1/config.proto
> +  // Valid values: "", "fips".
Yep completely agree. Thanks!@

2024-02-09 23:30 UTC, kyessenov commented on mesh/v1alpha1/config.proto
> +  string compliance_policy = 67;
It'll do what the comment does: apply the restrictions according to the compliance policy. Whether that is enough  for FIPS depends on whether the build is also using the CMVP TLS crypto module.

So it's not really no-op or ignored - it'll do the same thing regardless of what the build is.

2024-02-10 00:04 UTC, keithmattix commented on mesh/v1alpha1/config.proto
> +  string compliance_policy = 67;
Ack that's what I would expect. Probably worth a big warning sign in the documentation saying that this flag is not sufficient for FIPS

2024-02-10 03:39 UTC, ramaraochavali commented on mesh/v1alpha1/config.proto
> +  string compliance_policy = 67;
And with the current implementation if we set fips-140-2 - is the plan to disable TLS 1.3 and set Max version as 1.2?

2024-02-11 00:09 UTC, kyessenov commented on mesh/v1alpha1/config.proto
> +  string compliance_policy = 67;
@ramaraochavali Yes.

2024-02-13 19:17 UTC, kyessenov commented
@keithmattix @pmerrison @ZackButcher 

Please provide feedback. We'd like to restore compliance for all Istio deployments, and this is a necessary step to minimize the work for all vendors.

2024-02-13 19:23 UTC, keithmattix commented on mesh/v1alpha1/config.proto
> +  string compliance_policy = 67;
If we either:
1. Hide this from docs for now and add more warnings later or
2. Add a warning like Envoy has: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/ssl#fips-140-2

Then I'm good to approve

2024-02-14 21:34 UTC, kyessenov commented
@keithmattix @howardjohn  Thanks for reviewing. I expanded the explanation.

2024-02-14 21:39 UTC, keithmattix approved these changes
LGTM

2024-02-15 07:55 UTC, pmerrison commented
Had a chat with Kuat in Slack, and this looks good to me too.  Thanks for doing this Kuat, it saves us all work.

2024-02-15 07:55 UTC, pmerrison approved these changes

2024-02-15 09:35 UTC, ramaraochavali commented
@kyessenov just to clarify, in future based on FIPS compliance do you plan to configure cipher suites  also?  What else is configurable via this option?

2024-02-15 16:58 UTC, howardjohn approved these changes

2024-02-15 17:03 UTC, merged

2024-02-15 17:25 UTC, kyessenov commented
> @kyessenov just to clarify, in future based on FIPS compliance do you plan to configure cipher suites also? What else is configurable via this option?

Yes, ciphersuites and curves for TLSv1.2 must be configured for FIPS now and in the future with the updated boringssl.

> I am wondering if we enhance TLSSettings to have MaxVersion and provide guidance in docs on what values need to be set to be FIPSCompliant instead of having an additional API?

That doesn't work because there's more TLS configuration than xDS. gRPC C++, Go SDK, and gRPC Go SDKs are all in scope and don't use this setting.

> * While we have added docs about using FIPS image, I wonder if users might incorrectly think based on this mode, Istio would inject FIPS version of Envoy

I made it clear that this setting is not sufficient. At a minimum, certified builds must be used as well. However, it's necessary.

> * We need document what fips mode does exactly in the current version? Today it is just setting MaxVersion and tomorrow it might change some cipher suites.

We'll make restrictions clear in the implementation PR and put it into change notes. FIPS is evolving, Ed25519 was recently approved, so it's expected that we respond by allowing when appropriate.

2024-02-15 17:41 UTC, howardjohn commented
Is there somewhat a bootstrapping problem? To read meshconfig we need to connect to k8s api server (over TLS)

2024-02-15 17:47 UTC, kyessenov commented
@howardjohn k8s in FIPS mode should not be negotiating non-FIPS ciphers, it's not our responsibility. We're responsible when the server can choose non-FIPS ciphers, e.g. with GCP or Envoy/sidecars.

2024-02-15 19:18 UTC, keithmattix commented
+1 - for any real FIPS solution, k8s has to be FIPS as well otherwise the whole thing is pointless.

2024-02-15 19:19 UTC, howardjohn commented
The question is the clients responsibility to not pick a non-compliant
cipher, or the servers, or both?

I think in GCP the server will offer whatever. And that may also apply to
the GKE control plane

On Thu, Feb 15, 2024 at 11:18 AM Keith Mattix II ***@***.***>
wrote:

> +1 - for any real FIPS solution, k8s has to be FIPS as well otherwise the
> whole thing is pointless.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/api/pull/3082#issuecomment-1947036980>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEYGXJCRADVYYHK5AEXDZTYTZNQNAVCNFSM6AAAAABDCEW5MWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNBXGAZTMOJYGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-15 19:22 UTC, kyessenov commented
@howardjohn We might need a startup variable to Istiod. This change is needed to control injection and proxy containers, but it's not the only thing that is needed, as I already mentioned. Compliance is complicated, and requires a thorough audit - but we have to provide the flags to make it possible since we don't have any way to set restrictions anywhere.

2024-02-15 19:26 UTC, howardjohn commented
If it needs a startup flag then this should probably be a startup flag only, not sure we need mesh config also?

2024-02-15 19:31 UTC, kyessenov commented
@howardjohn GCP uses mesh config as a way to provision a custom control plane. I haven't validated that _we need a startup flag_ - we might not need it if we wait to connect to k8s a bit.

2024-02-20 23:48 UTC, kyessenov commented
@howardjohn @keithmattix @pmerrison We got some feedback that suggests reverting this change. 1) MeshConfig implies dynamic response, which is not possible for this fields, 2) We use TLS to read MeshConfig which causes a bootstrapping problem. The replacement is startup flags.