New Status proto for ServiceEntry
istio/api pull request #3244
Opened 2024-06-26 22:37 UTC by ilrudie

Adds a new proto based on IstioStatus to be used in ServiceEntry. This adds an addresses field to support the auto-allocation v2 controller's persistence requirement.

2024-06-26 22:38 UTC, istio-testing commented
@ilrudie: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_api | 796bba4ac2a9d6e4f3e93d0005a6448376b762a4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/3244/release-notes_api/1806094559004856320) | false | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-06-26 22:38 UTC, istio-testing commented
@ilrudie: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_api | 796bba4ac2a9d6e4f3e93d0005a6448376b762a4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/3244/release-notes_api/1806094559004856320) | false | `/test release-notes`
build_api | 796bba4ac2a9d6e4f3e93d0005a6448376b762a4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/3244/build_api/1806094558895804416) | true | `/test build`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-06-26 22:42 UTC, istio-testing commented
@ilrudie: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
build_api | 796bba4ac2a9d6e4f3e93d0005a6448376b762a4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/3244/build_api/1806094558895804416) | true | `/test build`
release-notes_api | 480a5a2ec1dc4a296ac7ae1690f502001e8f8b29 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/3244/release-notes_api/1806095692041555968) | false | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-06-27 01:52 UTC, hzxuzhonghu commented on meta/v1alpha1/serviceentry-status.proto
> +  // Current service state of pod.
??? what pod

2024-06-27 01:52 UTC, hzxuzhonghu commented on meta/v1alpha1/serviceentry-status.proto
> +  int64 observed_generation = 3;
Not sure the relationship with Generation in K8s Meta

2024-06-27 01:52 UTC, hzxuzhonghu commented on meta/v1alpha1/serviceentry-status.proto
> +// minor abstraction to allow for adding hostnames if relevant
why adding hostname?

2024-06-27 15:28 UTC, ilrudie commented on meta/v1alpha1/serviceentry-status.proto
> +// minor abstraction to allow for adding hostnames if relevant
We aren't adding hostname, and at present can't come up with a good reason to. The abstraction is there in case we want to add it at some point in the future (and to make it align better with gtwapi addresses field).

2024-06-27 15:30 UTC, ilrudie commented on meta/v1alpha1/serviceentry-status.proto
> +  // Current service state of pod.
fair question which I can't answer, it is verbatim copied from the existing istiostatus though

https://github.com/istio/api/blob/7c6732ba7766b7188bfaa69bcd244733da7f368e/meta/v1alpha1/status.proto#L29

2024-06-27 15:30 UTC, ilrudie commented on meta/v1alpha1/serviceentry-status.proto
> +  int64 observed_generation = 3;
another verbatim copy from istiostatus

https://github.com/istio/api/blob/7c6732ba7766b7188bfaa69bcd244733da7f368e/meta/v1alpha1/status.proto#L46

2024-06-27 15:33 UTC, ilrudie commented on meta/v1alpha1/serviceentry-status.proto
> +// minor abstraction to allow for adding hostnames if relevant
For some added context, This was something which was asked for in the WG where we discussed the api change. Costin wanted thins to align pretty close with an existing impl so that things which scrape status for addresses (namely external DNS) don't need to deal with us reinventing the wheel. gtwapi seemed as good as any though its not set in stone

2024-06-28 00:06 UTC, costinm requested changes
I'm not sure Istio status - and adding all the baggage and unrelated API - is the right approach.

John had a good point that adding the full K8S Gateway status is too much - but this is a different level of too much.

How about adding just the IP - and a small comment with a point to someone else that uses the same structure. Istio status doesn't have IP, so it's not relevant.

2024-06-28 00:07 UTC, costinm commented on meta/v1alpha1/serviceentry-status.proto
> +  repeated analysis.v1alpha1.AnalysisMessageBase validation_messages = 2;
If we decide to support validation_message in ServiceEntry - that should be a completely separate PR and discussion. I would rather follow the patterns for status in K8S Gateway - but I don't see how adding an IP is related to adding validation_messages.

2024-06-28 00:09 UTC, costinm commented on meta/v1alpha1/serviceentry-status.proto
> +// minor abstraction to allow for adding hostnames if relevant
I don't think K8S Gateway is using 'value' as field name - how does the yaml look like ?

2024-06-28 00:10 UTC, costinm commented on meta/v1alpha1/serviceentry-status.proto
> +// minor abstraction to allow for adding hostnames if relevant
And I think in the WG the conclusion was to not add hostname now, but keep the structure in place so we can add hostname later.

If you look at Service - there are several cases where they had to add hostname ( usually for integrating with specific vendors and LBs), so there is a good chance we'll need it at some point.

2024-06-28 00:11 UTC, howardjohn commented on meta/v1alpha1/serviceentry-status.proto
> +  repeated analysis.v1alpha1.AnalysisMessageBase validation_messages = 2;
Its already there. Not including this would mean removing a field from an existing v1 API.

This is basically a wonky diff since we had a shared message before and now we don't

2024-06-28 01:11 UTC, costinm commented on meta/v1alpha1/serviceentry-status.proto
> +  repeated analysis.v1alpha1.AnalysisMessageBase validation_messages = 2;
I see, so we no longer have a shared status - but we have to keep the old status.

Ok, nothing we can do about this. But at least we can use the same style and keywords for anything we add to match K8S Gateway - since I assume we want all our resources to also be consistent with the new API. 

How did we add the status for the other attached resources ? Can we share that ?

2024-06-28 15:03 UTC, ilrudie commented on meta/v1alpha1/serviceentry-status.proto
> +// minor abstraction to allow for adding hostnames if relevant
https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.GatewayStatusAddress is what I based this on. It has optional field `type` which I did not include since for the time being the type is known to be ip address and required field `value`. My thought process was if we ever want to support hostname we can decide at that time if we include type to help denote hostname vs ip address. [Here is the golang type](https://github.com/kubernetes-sigs/gateway-api/blob/cb5bf1541fa70f0692aebde8c64bba434cf331b6/apis/v1/gateway_types.go#L610).

2024-06-28 15:12 UTC, ilrudie commented
> I'm not sure Istio status - and adding all the baggage and unrelated API - is the right approach.
> 
> John had a good point that adding the full K8S Gateway status is too much - but this is a different level of too much.
> 
> How about adding just the IP - and a small comment with a point to someone else that uses the same structure. Istio status doesn't have IP, so it's not relevant.

I think we should at least include conditions. I was thinking about this some more last night and currently in v1 we have a situation where everything is ephemeral so if something about an SE changes such that we no longer do auto allocation we quietly ignore that se and possibly reshuffle the state of the world 2-tier hashing... With persistence via status we may not wish to immediately remove the assigned IPs though. Perhaps the IPs stay assigned, at least for some time until we garbage collect, but we note in a condition that the IPs will not be used due to reason X. User maybe corrects that and then the IP go back into effect without needing a new assign.

Maybe this need is not sufficient to duplicate all the IstioStatus fields though.

2024-06-29 00:03 UTC, costinm commented on meta/v1alpha1/serviceentry-status.proto
> +// minor abstraction to allow for adding hostnames if relevant
Ok, got it. 

Thanks for the explanation. the large copy confused me. 

Looks good to me.

2024-06-29 00:03 UTC, costinm approved these changes

2024-06-29 02:39 UTC, hzxuzhonghu commented on meta/v1alpha1/serviceentry-status.proto
> +  // Current service state of pod.
In the SE sceanario, We can change to state of the SE

2024-07-01 16:44 UTC, ilrudie commented on meta/v1alpha1/serviceentry-status.proto
> +  // Current service state of pod.
we could do but it would have to be kept consistently slightly different from the status it is based on. Perhaps we just circle back and correct the comment everywhere to be "Istio resource"? I'm not really clear if `pod` is just a typo in the first place

2024-07-01 16:46 UTC, ilrudie commented on meta/v1alpha1/serviceentry-status.proto
> +// minor abstraction to allow for adding hostnames if relevant
Yeah, I would not call the large copy ideal but as far as I can tell proto supports nothing like embedding so this manual copy is correct for proto. Happy to be proven wrong and learn a better way though.

2024-07-02 22:39 UTC, howardjohn commented on meta/v1alpha1/serviceentry-status.proto
> +// minor abstraction to allow for adding hostnames if relevant
This LGTM but we need to cleanup the comments; these are use facing API docs.

2024-07-04 17:20 UTC, howardjohn reviewed
Core lgtm just naming and comment issues

2024-07-04 17:20 UTC, howardjohn commented on meta/v1alpha1/serviceentry-status.proto
> +package istio.meta.v1alpha1;
should we put this in networking package?

2024-07-04 17:20 UTC, howardjohn commented on meta/v1alpha1/serviceentry-status.proto
> +message IstioServiceEntryStatus {
ServiceEntryStatus (drop Istio)

2024-07-04 17:20 UTC, howardjohn commented on meta/v1alpha1/serviceentry-status.proto
> +  // Current service state of pod.
Let's change to SE here and follow up to change the rest

2024-07-04 17:20 UTC, howardjohn commented on meta/v1alpha1/serviceentry-status.proto
> +  // Above this is just a copy of the common IstioStatus since proto cannot embed an anonymous message whole cloth
make sure this doesn't show up in generated html

2024-07-04 17:20 UTC, howardjohn commented on meta/v1alpha1/serviceentry-status.proto
> +  // List of addresses which were automatically allocated by istiod
```suggestion
  // List of addresses which were assigned to this ServiceEntry.
```

2024-07-04 17:20 UTC, howardjohn commented on meta/v1alpha1/serviceentry-status.proto
> +message IstioServiceEntryAddress{
Drop Istio prefix

2024-07-05 18:44 UTC, istio-testing commented
@ilrudie: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_api | 7158d2ca9182bea5a137cbc6d915f753f8f10a03 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/3244/release-notes_api/1809297281774522368) | false | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-07-05 18:44 UTC, istio-testing commented
@ilrudie: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_api | 7158d2ca9182bea5a137cbc6d915f753f8f10a03 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/3244/release-notes_api/1809297281774522368) | false | `/test release-notes`
gencheck_api | 7158d2ca9182bea5a137cbc6d915f753f8f10a03 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/3244/gencheck_api/1809297281724190720) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-07-05 18:45 UTC, ilrudie commented on meta/v1alpha1/serviceentry-status.proto
> +// minor abstraction to allow for adding hostnames if relevant
sounds good. thanks for the feedback!

2024-07-05 19:14 UTC, istio-testing commented
@ilrudie: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
gencheck_api | 7158d2ca9182bea5a137cbc6d915f753f8f10a03 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/3244/gencheck_api/1809297281724190720) | true | `/test gencheck`
release-notes_api | c5ede4833938d810a74752edce60aed86dc01910 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/3244/release-notes_api/1809304741121888256) | false | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-07-05 19:14 UTC, istio-testing commented
@ilrudie: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
release-notes_api | c5ede4833938d810a74752edce60aed86dc01910 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/3244/release-notes_api/1809304741121888256) | false | `/test release-notes`
gencheck_api | c5ede4833938d810a74752edce60aed86dc01910 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/3244/gencheck_api/1809304741071556608) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-07-05 19:16 UTC, ilrudie commented on meta/v1alpha1/serviceentry-status.proto
> +  // Current service state of pod.
fixed in service entry. could fix `pod` in status in this PR if folks don't mind but didn't want to make it larger than necessary unless folks want it

2024-07-05 19:18 UTC, ilrudie commented on meta/v1alpha1/serviceentry-status.proto
> +package istio.meta.v1alpha1;
moved it

2024-07-05 19:18 UTC, ilrudie commented on meta/v1alpha1/serviceentry-status.proto
> +  // Above this is just a copy of the common IstioStatus since proto cannot embed an anonymous message whole cloth
I don't see this or the other similar comments in the generated html, I think it is OK unless I misunderstand

2024-07-05 19:23 UTC, istio-testing commented
@ilrudie: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
gencheck_api | c5ede4833938d810a74752edce60aed86dc01910 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/3244/gencheck_api/1809304741071556608) | true | `/test gencheck`
release-notes_api | 7c9a9ee5eb59fda807bd59b374ba764f174d611e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/3244/release-notes_api/1809307087595900928) | false | `/test release-notes`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-07-05 22:10 UTC, howardjohn approved these changes

2024-07-05 22:10 UTC, merged

2024-07-05 22:10 UTC, howardjohn commented on networking/v1alpha3/serviceentry-status.proto
> +// $title: ServiceEntry Status
nit: maybe we should just put this in servicentry.proto directly. I don't think we want a whole new docs page for it

2024-07-05 22:10 UTC, howardjohn commented on networking/v1alpha3/serviceentry-status.proto
> +// minor abstraction to allow for adding hostnames if relevant
Dev comment should not end up in public docs