Add StatefulFormatter to ProxyConfig
istio/api pull request #3350
Opened 2024-11-06 07:49 UTC by whitneygriffith

Part of https://github.com/istio/istio/issues/53680

2024-11-06 07:49 UTC, istio-testing commented
@whitneygriffith: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
gencheck_api | 1a29603b436c28aca6c30f69eba54fa3acf30f94 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/3350/gencheck_api/1854068561002106880) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-11-06 07:52 UTC, istio-testing commented
@whitneygriffith: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
gencheck_api | f1c0513bf0f2865240c5b77ccd172aeb2c39aada | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/3350/gencheck_api/1854069246741450752) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-11-06 17:34 UTC, istio-testing commented
@whitneygriffith: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
gencheck_api | 6580464c3a49f4b13dadd9f8d96de97c9fd82daf | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/3350/gencheck_api/1854215799162540032) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-11-06 19:57 UTC, keithmattix requested changes

2024-11-06 19:57 UTC, keithmattix commented on networking/v1beta1/proxy_config.proto
> +// kind: ProxyConfig
I don't think we want to add this to the ProxyConfig resource; only the proxyConfig annotation

2024-11-06 19:57 UTC, keithmattix commented on mesh/v1alpha1/proxy.proto
> +  istio.networking.v1beta1.StatefulFormatter stateful_formatter = 40;
I'm not sure I like the idea of passing the complexity of "stateful formatters" to the users who just want to preserve their header casing. Can we utilize the proxyHeaders struct in some way to make this more intuitive?

2024-11-06 20:49 UTC, whitneygriffith commented on mesh/v1alpha1/proxy.proto
> +  istio.networking.v1beta1.StatefulFormatter stateful_formatter = 40;
I agree that we should avoid exposing the complexity of stateful formatters directly to users who are using the higher level `meshConfig` to enable header case preservation. I will look into adding `preserveCase` or `preserveHeaderCase`  to the `proxyHeaders` struct.

2024-11-06 20:53 UTC, whitneygriffith commented on networking/v1beta1/proxy_config.proto
> +// kind: ProxyConfig
Can you point me to the `proxyConfig` annotation? From what I understand to enable `preserveCase` at the namespace or workload level this feature should be apart of the `proxyConfig` resource. Where the annotation is used to apply a specific `proxyConfig` resource to a workload.

2024-11-06 21:29 UTC, keithmattix commented on networking/v1beta1/proxy_config.proto
> +// kind: ProxyConfig
If you check the recording of the community meeting, the consensus was that we didn't want to make this too flexible/easy to use since we want to encourage users to adopt http2. Adding the field to the annotation and not the resource allows us to do so. Notice that the networking/v1beta1/proxy_config.proto file and the mesh/v1alpha1/proxy.proto files have different fields. The former is the CRD and the latter is the annotation struct; please add the new fields there

2024-11-19 18:23 UTC, keithmattix approved these changes
This shape LGTM, but the PR may need a rebase to include some reason changes around deeplinks

2024-11-20 06:44 UTC, hzxuzhonghu commented on mesh/v1alpha1/proxy.proto
> +    bool preserve_http1_header_case = 40;
should we use `google.protobuf.BoolValue` type

2024-11-22 01:38 UTC, hzxuzhonghu approved these changes

2024-11-26 19:19 UTC, howardjohn approved these changes

2024-12-03 20:04 UTC, istio-testing commented
@whitneygriffith: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
gencheck_api | 1dd42d8740fd555261757eaff426b155199c9e7e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/3350/gencheck_api/1864037964221255680) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-12-03 20:07 UTC, merged